package ccse

import (
	"github.com/ctyun-it/terraform-provider-ctyun/internal/core/core"
)

const EndpointName = "ccse"

type Apis struct {
	CcseQueryClusterSubUserApi                   *CcseQueryClusterSubUserApi
	CcseGetClusterTempKubeConfigApi              *CcseGetClusterTempKubeConfigApi
	CcseModifyNodeApi                            *CcseModifyNodeApi
	CcseQueryNodeApi                             *CcseQueryNodeApi
	CcseListNodesApi                             *CcseListNodesApi
	CcseDeleteCronHorizontalPodAutoscalerApi     *CcseDeleteCronHorizontalPodAutoscalerApi
	CcseUpdateCronHorizontalPodAutoscalerApi     *CcseUpdateCronHorizontalPodAutoscalerApi
	CcseGetCronHorizontalPodAutoscalerApi        *CcseGetCronHorizontalPodAutoscalerApi
	CcseListCronHorizontalPodAutoscalersApi      *CcseListCronHorizontalPodAutoscalersApi
	CcseGetNodeDetailApi                         *CcseGetNodeDetailApi
	CcseUpdateHorizontalPodAutoscalerApi         *CcseUpdateHorizontalPodAutoscalerApi
	CcseRemoveHorizontalPodAutoscalerV2Api       *CcseRemoveHorizontalPodAutoscalerV2Api
	CcseCreateCronHorizontalPodAutoscalerApi     *CcseCreateCronHorizontalPodAutoscalerApi
	CcseGetHorizontalPodAutoscalerApi            *CcseGetHorizontalPodAutoscalerApi
	CcseDeleteJobApi                             *CcseDeleteJobApi
	CcseUpdateJobApi                             *CcseUpdateJobApi
	CcseGetJobApi                                *CcseGetJobApi
	CcseListJobsApi                              *CcseListJobsApi
	CcseCreateJobApi                             *CcseCreateJobApi
	CcseListEventsApi                            *CcseListEventsApi
	CcseDeleteReplicaSetApi                      *CcseDeleteReplicaSetApi
	CcseUpdateReplicaSetApi                      *CcseUpdateReplicaSetApi
	CcseGetReplicaSetApi                         *CcseGetReplicaSetApi
	CcseListReplicaSetsApi                       *CcseListReplicaSetsApi
	CcseCreateReplicaSetApi                      *CcseCreateReplicaSetApi
	CcseListHorizontalPodAutoscalersApi          *CcseListHorizontalPodAutoscalersApi
	CcseCreateHorizontalPodAutoscalerApi         *CcseCreateHorizontalPodAutoscalerApi
	CcseDeletePersistentVolumeApi                *CcseDeletePersistentVolumeApi
	CcseUpdatePersistentVolumeApi                *CcseUpdatePersistentVolumeApi
	CcseGetPersistentVolumeApi                   *CcseGetPersistentVolumeApi
	CcseListPersistentVolumesApi                 *CcseListPersistentVolumesApi
	CcseCreatePersistentVolumeApi                *CcseCreatePersistentVolumeApi
	CcseUpdateServiceApi                         *CcseUpdateServiceApi
	CcseListServicesApi                          *CcseListServicesApi
	CcseGetServiceApi                            *CcseGetServiceApi
	CcseDeleteServiceApi                         *CcseDeleteServiceApi
	CcseCreateServiceApi                         *CcseCreateServiceApi
	CcseCreateSecretApi                          *CcseCreateSecretApi
	CcseListSecretsApi                           *CcseListSecretsApi
	CcseDeleteSecretApi                          *CcseDeleteSecretApi
	CcseUpdateSecretApi                          *CcseUpdateSecretApi
	CcseGetSecretApi                             *CcseGetSecretApi
	CcseCreateConfigMapApi                       *CcseCreateConfigMapApi
	CcseListConfigMapsApi                        *CcseListConfigMapsApi
	CcseDeleteConfigMapApi                       *CcseDeleteConfigMapApi
	CcseUpdateConfigMapApi                       *CcseUpdateConfigMapApi
	CcseGetConfigMapApi                          *CcseGetConfigMapApi
	CcseUpdatePersistentVolumeClaimApi           *CcseUpdatePersistentVolumeClaimApi
	CcseGetPersistentVolumeClaimApi              *CcseGetPersistentVolumeClaimApi
	CcseListPersistentVolumeClaimsApi            *CcseListPersistentVolumeClaimsApi
	CcseDeletePersistentVolumeClaimApi           *CcseDeletePersistentVolumeClaimApi
	CcseCreatePersistentVolumeClaimApi           *CcseCreatePersistentVolumeClaimApi
	CcseListClusterAutoscalerPoliciesApi         *CcseListClusterAutoscalerPoliciesApi
	CcseGetClusterAutoscalerPolicyApi            *CcseGetClusterAutoscalerPolicyApi
	CcseDeleteClusterAutoscalerPolicyApi         *CcseDeleteClusterAutoscalerPolicyApi
	CcseUpdateClusterAutoscalerPolicyApi         *CcseUpdateClusterAutoscalerPolicyApi
	CcseCreateClusterAutoscalerPolicyApi         *CcseCreateClusterAutoscalerPolicyApi
	CcseRenewClusterApi                          *CcseRenewClusterApi
	CcseCreateClusterDelegateApi                 *CcseCreateClusterDelegateApi
	CcseGetKubernetesVersionsApi                 *CcseGetKubernetesVersionsApi
	CcseGetClusterQuotaApi                       *CcseGetClusterQuotaApi
	CcseDeleteClusterApi                         *CcseDeleteClusterApi
	CcseCreateClusterApi                         *CcseCreateClusterApi
	CcseRepairNodePoolApi                        *CcseRepairNodePoolApi
	CcseGetPolicyTemplateApi                     *CcseGetPolicyTemplateApi
	CcseListPolicyRulesApi                       *CcseListPolicyRulesApi
	CcseListPodApi                               *CcseListPodApi
	CcseDeletePodApi                             *CcseDeletePodApi
	CcseUpdatePodApi                             *CcseUpdatePodApi
	CcseCreatePodApi                             *CcseCreatePodApi
	CcsePauseClusterTaskApi                      *CcsePauseClusterTaskApi
	CcseResumeClusterTaskApi                     *CcseResumeClusterTaskApi
	CcseCancelClusterTaskApi                     *CcseCancelClusterTaskApi
	CcseDeleteStorageClassApi                    *CcseDeleteStorageClassApi
	CcseGetStorageClassApi                       *CcseGetStorageClassApi
	CcseUpdateStorageClassApi                    *CcseUpdateStorageClassApi
	CcseListStorageClassesApi                    *CcseListStorageClassesApi
	CcseCreateStorageClassApi                    *CcseCreateStorageClassApi
	CcseListVolumeSnapshotsApi                   *CcseListVolumeSnapshotsApi
	CcseDeleteVolumeSnapshotApi                  *CcseDeleteVolumeSnapshotApi
	CcseUpdateVolumeSnapshotApi                  *CcseUpdateVolumeSnapshotApi
	CcseGetVolumeSnapshotApi                     *CcseGetVolumeSnapshotApi
	CcseCreateVolumeSnapshotApi                  *CcseCreateVolumeSnapshotApi
	CcseListVolumeSnapshotClassesApi             *CcseListVolumeSnapshotClassesApi
	CcseDeleteVolumeSnapshotClassApi             *CcseDeleteVolumeSnapshotClassApi
	CcseUpdateVolumeSnapshotClassApi             *CcseUpdateVolumeSnapshotClassApi
	CcseGetVolumeSnapshotClassApi                *CcseGetVolumeSnapshotClassApi
	CcseCreateVolumeSnapshotClassApi             *CcseCreateVolumeSnapshotClassApi
	CcseGetClusterResourcesApi                   *CcseGetClusterResourcesApi
	CcseGetClusterApi                            *CcseGetClusterApi
	CcseGetClusterKubeConfigApi                  *CcseGetClusterKubeConfigApi
	CcseGetSubUserClusterKubeConfigApi           *CcseGetSubUserClusterKubeConfigApi
	CcseGetSubUserPermissionApi                  *CcseGetSubUserPermissionApi
	CcseUpdateSubUserPermissionsApi              *CcseUpdateSubUserPermissionsApi
	CcseUpdateClusterApi                         *CcseUpdateClusterApi
	CcseGetUpgradeClusterStatusApi               *CcseGetUpgradeClusterStatusApi
	CcseUpgradeClusterApi                        *CcseUpgradeClusterApi
	CcseListClustersApi                          *CcseListClustersApi
	CcseListClusterTagsApi                       *CcseListClusterTagsApi
	CcseUpdateClusterTagsApi                     *CcseUpdateClusterTagsApi
	CcseUnbindClusterTagsApi                     *CcseUnbindClusterTagsApi
	CcseBindClusterTagsApi                       *CcseBindClusterTagsApi
	CcseGetPolicyGovernanceApi                   *CcseGetPolicyGovernanceApi
	CcseListClusterPolicyInstancesApi            *CcseListClusterPolicyInstancesApi
	CcseGetClusterPolicyStatusApi                *CcseGetClusterPolicyStatusApi
	CcseUpdateClusterPolicyInstanceApi           *CcseUpdateClusterPolicyInstanceApi
	CcseDeleteClusterPolicyInstanceApi           *CcseDeleteClusterPolicyInstanceApi
	CcseCreateClusterPolicyInstanceApi           *CcseCreateClusterPolicyInstanceApi
	CcseListClusterNodesApi                      *CcseListClusterNodesApi
	CcseCreateNodePoolApi                        *CcseCreateNodePoolApi
	CcseListNodePoolsApi                         *CcseListNodePoolsApi
	CcseGetNodePoolApi                           *CcseGetNodePoolApi
	CcseDeleteNodePoolApi                        *CcseDeleteNodePoolApi
	CcseBatchDeleteNodePoolApi                   *CcseBatchDeleteNodePoolApi
	CcseScaleUpNodePoolApi                       *CcseScaleUpNodePoolApi
	CcseScaleDownNodePoolApi                     *CcseScaleDownNodePoolApi
	CcseHasPluginInstanceExistedApi              *CcseHasPluginInstanceExistedApi
	CcseDeletePluginInstanceApi                  *CcseDeletePluginInstanceApi
	CcseUpgradePluginInstanceApi                 *CcseUpgradePluginInstanceApi
	CcseRedeployPluginInstanceApi                *CcseRedeployPluginInstanceApi
	CcseListPluginInstancesApi                   *CcseListPluginInstancesApi
	CcseGetPluginInstanceApi                     *CcseGetPluginInstanceApi
	CcseDeployPluginInstanceApi                  *CcseDeployPluginInstanceApi
	CcseGetPodApi                                *CcseGetPodApi
	CcseListDeploymentsApi                       *CcseListDeploymentsApi
	CcseHasTemplateInstanceExistedApi            *CcseHasTemplateInstanceExistedApi
	CcseGetTemplateInstanceApi                   *CcseGetTemplateInstanceApi
	CcseDeleteTemplateInstanceApi                *CcseDeleteTemplateInstanceApi
	CcseDeployTemplateInstanceApi                *CcseDeployTemplateInstanceApi
	CcseAttachClusterNodesApi                    *CcseAttachClusterNodesApi
	CcseRemoveNodeV2Api                          *CcseRemoveNodeV2Api
	CcseGetSubUserClusterNamespacesApi           *CcseGetSubUserClusterNamespacesApi
	CcseClusterUpgradePrecheckApi                *CcseClusterUpgradePrecheckApi
	CcseUpdateClusterKubeConfigExpirationTimeApi *CcseUpdateClusterKubeConfigExpirationTimeApi
	CcseCheckControlPlaneLogEnabledApi           *CcseCheckControlPlaneLogEnabledApi
	CcseEnableControlPlaneLogApi                 *CcseEnableControlPlaneLogApi
	CcseUpdateNodePoolApi                        *CcseUpdateNodePoolApi
	CcseUpdateNodePoolKubeletConfigApi           *CcseUpdateNodePoolKubeletConfigApi
	CcseSyncNodePoolApi                          *CcseSyncNodePoolApi
	CcseGetClusterTaskApi                        *CcseGetClusterTaskApi
	CcseListClusterTasksApi                      *CcseListClusterTasksApi
	CcseGetClusterEventsApi                      *CcseGetClusterEventsApi
	CcseListClusterTaskEventsApi                 *CcseListClusterTaskEventsApi
	CcseGetDeploymentApi                         *CcseGetDeploymentApi
	CcseUpdateDeploymentApi                      *CcseUpdateDeploymentApi
	CcseDeleteDeploymentApi                      *CcseDeleteDeploymentApi
	CcseCreateDeploymentApi                      *CcseCreateDeploymentApi
	CcseListStatefulSetsApi                      *CcseListStatefulSetsApi
	CcseGetStatefulSetApi                        *CcseGetStatefulSetApi
	CcseUpdateStatefulSetApi                     *CcseUpdateStatefulSetApi
	CcseDeleteStatefulSetApi                     *CcseDeleteStatefulSetApi
	CcseCreateStatefulSetApi                     *CcseCreateStatefulSetApi
	CcseListDaemonSetsApi                        *CcseListDaemonSetsApi
	CcseGetDaemonSetApi                          *CcseGetDaemonSetApi
	CcseUpdateDaemonSetApi                       *CcseUpdateDaemonSetApi
	CcseDeleteDaemonSetApi                       *CcseDeleteDaemonSetApi
	CcseCreateDaemonSetApi                       *CcseCreateDaemonSetApi
	CcseUpgradeNodePoolApi                       *CcseUpgradeNodePoolApi
}

func NewApis(endpointUrl string, client *core.CtyunClient) *Apis {
	client.RegisterEndpoint(core.Endpoint{
		Name: EndpointName,
		Url:  endpointUrl,
	})
	return &Apis{
		CcseQueryClusterSubUserApi:                   NewCcseQueryClusterSubUserApi(client),
		CcseGetClusterTempKubeConfigApi:              NewCcseGetClusterTempKubeConfigApi(client),
		CcseModifyNodeApi:                            NewCcseModifyNodeApi(client),
		CcseQueryNodeApi:                             NewCcseQueryNodeApi(client),
		CcseListNodesApi:                             NewCcseListNodesApi(client),
		CcseDeleteCronHorizontalPodAutoscalerApi:     NewCcseDeleteCronHorizontalPodAutoscalerApi(client),
		CcseUpdateCronHorizontalPodAutoscalerApi:     NewCcseUpdateCronHorizontalPodAutoscalerApi(client),
		CcseGetCronHorizontalPodAutoscalerApi:        NewCcseGetCronHorizontalPodAutoscalerApi(client),
		CcseListCronHorizontalPodAutoscalersApi:      NewCcseListCronHorizontalPodAutoscalersApi(client),
		CcseGetNodeDetailApi:                         NewCcseGetNodeDetailApi(client),
		CcseUpdateHorizontalPodAutoscalerApi:         NewCcseUpdateHorizontalPodAutoscalerApi(client),
		CcseRemoveHorizontalPodAutoscalerV2Api:       NewCcseRemoveHorizontalPodAutoscalerV2Api(client),
		CcseCreateCronHorizontalPodAutoscalerApi:     NewCcseCreateCronHorizontalPodAutoscalerApi(client),
		CcseGetHorizontalPodAutoscalerApi:            NewCcseGetHorizontalPodAutoscalerApi(client),
		CcseDeleteJobApi:                             NewCcseDeleteJobApi(client),
		CcseUpdateJobApi:                             NewCcseUpdateJobApi(client),
		CcseGetJobApi:                                NewCcseGetJobApi(client),
		CcseListJobsApi:                              NewCcseListJobsApi(client),
		CcseCreateJobApi:                             NewCcseCreateJobApi(client),
		CcseListEventsApi:                            NewCcseListEventsApi(client),
		CcseDeleteReplicaSetApi:                      NewCcseDeleteReplicaSetApi(client),
		CcseUpdateReplicaSetApi:                      NewCcseUpdateReplicaSetApi(client),
		CcseGetReplicaSetApi:                         NewCcseGetReplicaSetApi(client),
		CcseListReplicaSetsApi:                       NewCcseListReplicaSetsApi(client),
		CcseCreateReplicaSetApi:                      NewCcseCreateReplicaSetApi(client),
		CcseListHorizontalPodAutoscalersApi:          NewCcseListHorizontalPodAutoscalersApi(client),
		CcseCreateHorizontalPodAutoscalerApi:         NewCcseCreateHorizontalPodAutoscalerApi(client),
		CcseDeletePersistentVolumeApi:                NewCcseDeletePersistentVolumeApi(client),
		CcseUpdatePersistentVolumeApi:                NewCcseUpdatePersistentVolumeApi(client),
		CcseGetPersistentVolumeApi:                   NewCcseGetPersistentVolumeApi(client),
		CcseListPersistentVolumesApi:                 NewCcseListPersistentVolumesApi(client),
		CcseCreatePersistentVolumeApi:                NewCcseCreatePersistentVolumeApi(client),
		CcseUpdateServiceApi:                         NewCcseUpdateServiceApi(client),
		CcseListServicesApi:                          NewCcseListServicesApi(client),
		CcseGetServiceApi:                            NewCcseGetServiceApi(client),
		CcseDeleteServiceApi:                         NewCcseDeleteServiceApi(client),
		CcseCreateServiceApi:                         NewCcseCreateServiceApi(client),
		CcseCreateSecretApi:                          NewCcseCreateSecretApi(client),
		CcseListSecretsApi:                           NewCcseListSecretsApi(client),
		CcseDeleteSecretApi:                          NewCcseDeleteSecretApi(client),
		CcseUpdateSecretApi:                          NewCcseUpdateSecretApi(client),
		CcseGetSecretApi:                             NewCcseGetSecretApi(client),
		CcseCreateConfigMapApi:                       NewCcseCreateConfigMapApi(client),
		CcseListConfigMapsApi:                        NewCcseListConfigMapsApi(client),
		CcseDeleteConfigMapApi:                       NewCcseDeleteConfigMapApi(client),
		CcseUpdateConfigMapApi:                       NewCcseUpdateConfigMapApi(client),
		CcseGetConfigMapApi:                          NewCcseGetConfigMapApi(client),
		CcseUpdatePersistentVolumeClaimApi:           NewCcseUpdatePersistentVolumeClaimApi(client),
		CcseGetPersistentVolumeClaimApi:              NewCcseGetPersistentVolumeClaimApi(client),
		CcseListPersistentVolumeClaimsApi:            NewCcseListPersistentVolumeClaimsApi(client),
		CcseDeletePersistentVolumeClaimApi:           NewCcseDeletePersistentVolumeClaimApi(client),
		CcseCreatePersistentVolumeClaimApi:           NewCcseCreatePersistentVolumeClaimApi(client),
		CcseListClusterAutoscalerPoliciesApi:         NewCcseListClusterAutoscalerPoliciesApi(client),
		CcseGetClusterAutoscalerPolicyApi:            NewCcseGetClusterAutoscalerPolicyApi(client),
		CcseDeleteClusterAutoscalerPolicyApi:         NewCcseDeleteClusterAutoscalerPolicyApi(client),
		CcseUpdateClusterAutoscalerPolicyApi:         NewCcseUpdateClusterAutoscalerPolicyApi(client),
		CcseCreateClusterAutoscalerPolicyApi:         NewCcseCreateClusterAutoscalerPolicyApi(client),
		CcseRenewClusterApi:                          NewCcseRenewClusterApi(client),
		CcseCreateClusterDelegateApi:                 NewCcseCreateClusterDelegateApi(client),
		CcseGetKubernetesVersionsApi:                 NewCcseGetKubernetesVersionsApi(client),
		CcseGetClusterQuotaApi:                       NewCcseGetClusterQuotaApi(client),
		CcseDeleteClusterApi:                         NewCcseDeleteClusterApi(client),
		CcseCreateClusterApi:                         NewCcseCreateClusterApi(client),
		CcseRepairNodePoolApi:                        NewCcseRepairNodePoolApi(client),
		CcseGetPolicyTemplateApi:                     NewCcseGetPolicyTemplateApi(client),
		CcseListPolicyRulesApi:                       NewCcseListPolicyRulesApi(client),
		CcseListPodApi:                               NewCcseListPodApi(client),
		CcseDeletePodApi:                             NewCcseDeletePodApi(client),
		CcseUpdatePodApi:                             NewCcseUpdatePodApi(client),
		CcseCreatePodApi:                             NewCcseCreatePodApi(client),
		CcsePauseClusterTaskApi:                      NewCcsePauseClusterTaskApi(client),
		CcseResumeClusterTaskApi:                     NewCcseResumeClusterTaskApi(client),
		CcseCancelClusterTaskApi:                     NewCcseCancelClusterTaskApi(client),
		CcseDeleteStorageClassApi:                    NewCcseDeleteStorageClassApi(client),
		CcseGetStorageClassApi:                       NewCcseGetStorageClassApi(client),
		CcseUpdateStorageClassApi:                    NewCcseUpdateStorageClassApi(client),
		CcseListStorageClassesApi:                    NewCcseListStorageClassesApi(client),
		CcseCreateStorageClassApi:                    NewCcseCreateStorageClassApi(client),
		CcseListVolumeSnapshotsApi:                   NewCcseListVolumeSnapshotsApi(client),
		CcseDeleteVolumeSnapshotApi:                  NewCcseDeleteVolumeSnapshotApi(client),
		CcseUpdateVolumeSnapshotApi:                  NewCcseUpdateVolumeSnapshotApi(client),
		CcseGetVolumeSnapshotApi:                     NewCcseGetVolumeSnapshotApi(client),
		CcseCreateVolumeSnapshotApi:                  NewCcseCreateVolumeSnapshotApi(client),
		CcseListVolumeSnapshotClassesApi:             NewCcseListVolumeSnapshotClassesApi(client),
		CcseDeleteVolumeSnapshotClassApi:             NewCcseDeleteVolumeSnapshotClassApi(client),
		CcseUpdateVolumeSnapshotClassApi:             NewCcseUpdateVolumeSnapshotClassApi(client),
		CcseGetVolumeSnapshotClassApi:                NewCcseGetVolumeSnapshotClassApi(client),
		CcseCreateVolumeSnapshotClassApi:             NewCcseCreateVolumeSnapshotClassApi(client),
		CcseGetClusterResourcesApi:                   NewCcseGetClusterResourcesApi(client),
		CcseGetClusterApi:                            NewCcseGetClusterApi(client),
		CcseGetClusterKubeConfigApi:                  NewCcseGetClusterKubeConfigApi(client),
		CcseGetSubUserClusterKubeConfigApi:           NewCcseGetSubUserClusterKubeConfigApi(client),
		CcseGetSubUserPermissionApi:                  NewCcseGetSubUserPermissionApi(client),
		CcseUpdateSubUserPermissionsApi:              NewCcseUpdateSubUserPermissionsApi(client),
		CcseUpdateClusterApi:                         NewCcseUpdateClusterApi(client),
		CcseGetUpgradeClusterStatusApi:               NewCcseGetUpgradeClusterStatusApi(client),
		CcseUpgradeClusterApi:                        NewCcseUpgradeClusterApi(client),
		CcseListClustersApi:                          NewCcseListClustersApi(client),
		CcseListClusterTagsApi:                       NewCcseListClusterTagsApi(client),
		CcseUpdateClusterTagsApi:                     NewCcseUpdateClusterTagsApi(client),
		CcseUnbindClusterTagsApi:                     NewCcseUnbindClusterTagsApi(client),
		CcseBindClusterTagsApi:                       NewCcseBindClusterTagsApi(client),
		CcseGetPolicyGovernanceApi:                   NewCcseGetPolicyGovernanceApi(client),
		CcseListClusterPolicyInstancesApi:            NewCcseListClusterPolicyInstancesApi(client),
		CcseGetClusterPolicyStatusApi:                NewCcseGetClusterPolicyStatusApi(client),
		CcseUpdateClusterPolicyInstanceApi:           NewCcseUpdateClusterPolicyInstanceApi(client),
		CcseDeleteClusterPolicyInstanceApi:           NewCcseDeleteClusterPolicyInstanceApi(client),
		CcseCreateClusterPolicyInstanceApi:           NewCcseCreateClusterPolicyInstanceApi(client),
		CcseListClusterNodesApi:                      NewCcseListClusterNodesApi(client),
		CcseCreateNodePoolApi:                        NewCcseCreateNodePoolApi(client),
		CcseListNodePoolsApi:                         NewCcseListNodePoolsApi(client),
		CcseGetNodePoolApi:                           NewCcseGetNodePoolApi(client),
		CcseDeleteNodePoolApi:                        NewCcseDeleteNodePoolApi(client),
		CcseBatchDeleteNodePoolApi:                   NewCcseBatchDeleteNodePoolApi(client),
		CcseScaleUpNodePoolApi:                       NewCcseScaleUpNodePoolApi(client),
		CcseScaleDownNodePoolApi:                     NewCcseScaleDownNodePoolApi(client),
		CcseHasPluginInstanceExistedApi:              NewCcseHasPluginInstanceExistedApi(client),
		CcseDeletePluginInstanceApi:                  NewCcseDeletePluginInstanceApi(client),
		CcseUpgradePluginInstanceApi:                 NewCcseUpgradePluginInstanceApi(client),
		CcseRedeployPluginInstanceApi:                NewCcseRedeployPluginInstanceApi(client),
		CcseListPluginInstancesApi:                   NewCcseListPluginInstancesApi(client),
		CcseGetPluginInstanceApi:                     NewCcseGetPluginInstanceApi(client),
		CcseDeployPluginInstanceApi:                  NewCcseDeployPluginInstanceApi(client),
		CcseGetPodApi:                                NewCcseGetPodApi(client),
		CcseListDeploymentsApi:                       NewCcseListDeploymentsApi(client),
		CcseHasTemplateInstanceExistedApi:            NewCcseHasTemplateInstanceExistedApi(client),
		CcseGetTemplateInstanceApi:                   NewCcseGetTemplateInstanceApi(client),
		CcseDeleteTemplateInstanceApi:                NewCcseDeleteTemplateInstanceApi(client),
		CcseDeployTemplateInstanceApi:                NewCcseDeployTemplateInstanceApi(client),
		CcseAttachClusterNodesApi:                    NewCcseAttachClusterNodesApi(client),
		CcseGetSubUserClusterNamespacesApi:           NewCcseGetSubUserClusterNamespacesApi(client),
		CcseClusterUpgradePrecheckApi:                NewCcseClusterUpgradePrecheckApi(client),
		CcseUpdateClusterKubeConfigExpirationTimeApi: NewCcseUpdateClusterKubeConfigExpirationTimeApi(client),
		CcseCheckControlPlaneLogEnabledApi:           NewCcseCheckControlPlaneLogEnabledApi(client),
		CcseEnableControlPlaneLogApi:                 NewCcseEnableControlPlaneLogApi(client),
		CcseUpdateNodePoolApi:                        NewCcseUpdateNodePoolApi(client),
		CcseUpdateNodePoolKubeletConfigApi:           NewCcseUpdateNodePoolKubeletConfigApi(client),
		CcseSyncNodePoolApi:                          NewCcseSyncNodePoolApi(client),
		CcseGetClusterTaskApi:                        NewCcseGetClusterTaskApi(client),
		CcseListClusterTasksApi:                      NewCcseListClusterTasksApi(client),
		CcseGetClusterEventsApi:                      NewCcseGetClusterEventsApi(client),
		CcseListClusterTaskEventsApi:                 NewCcseListClusterTaskEventsApi(client),
		CcseGetDeploymentApi:                         NewCcseGetDeploymentApi(client),
		CcseUpdateDeploymentApi:                      NewCcseUpdateDeploymentApi(client),
		CcseDeleteDeploymentApi:                      NewCcseDeleteDeploymentApi(client),
		CcseCreateDeploymentApi:                      NewCcseCreateDeploymentApi(client),
		CcseListStatefulSetsApi:                      NewCcseListStatefulSetsApi(client),
		CcseGetStatefulSetApi:                        NewCcseGetStatefulSetApi(client),
		CcseUpdateStatefulSetApi:                     NewCcseUpdateStatefulSetApi(client),
		CcseDeleteStatefulSetApi:                     NewCcseDeleteStatefulSetApi(client),
		CcseCreateStatefulSetApi:                     NewCcseCreateStatefulSetApi(client),
		CcseListDaemonSetsApi:                        NewCcseListDaemonSetsApi(client),
		CcseGetDaemonSetApi:                          NewCcseGetDaemonSetApi(client),
		CcseUpdateDaemonSetApi:                       NewCcseUpdateDaemonSetApi(client),
		CcseDeleteDaemonSetApi:                       NewCcseDeleteDaemonSetApi(client),
		CcseCreateDaemonSetApi:                       NewCcseCreateDaemonSetApi(client),
		CcseUpgradeNodePoolApi:                       NewCcseUpgradeNodePoolApi(client),
		CcseRemoveNodeV2Api:                          NewCcseRemoveNodeV2Api(client),
	}
}
