package ctvpc

import (
	"github.com/ctyun-it/terraform-provider-ctyun/internal/core/core"
)

const EndpointName = "ctvpc"

type Apis struct {
	CtvpcL2gwQueryCreatePriceApi                 *CtvpcL2gwQueryCreatePriceApi
	CtvpcL2gwQueryRenewPriceApi                  *CtvpcL2gwQueryRenewPriceApi
	CtvpcL2gwRenewApi                            *CtvpcL2gwRenewApi
	CtvpcModifyEndpointServiceIpVersionApi       *CtvpcModifyEndpointServiceIpVersionApi
	CtvpcModifyEndpointIpVersionApi              *CtvpcModifyEndpointIpVersionApi
	CtvpcModifyVpcAccessLogApi                   *CtvpcModifyVpcAccessLogApi
	CtvpcDeleteVpcAccessLogApi                   *CtvpcDeleteVpcAccessLogApi
	CtvpcAddVpcAccessLogApi                      *CtvpcAddVpcAccessLogApi
	CtvpcListVpcAccessLogApi                     *CtvpcListVpcAccessLogApi
	CtvpcGetVpcPeerRouteApi                      *CtvpcGetVpcPeerRouteApi
	CtvpcDeleteVpcPeerRouteApi                   *CtvpcDeleteVpcPeerRouteApi
	CtvpcCreateVpcPeerRouteApi                   *CtvpcCreateVpcPeerRouteApi
	CtvpcAclCloneApi                             *CtvpcAclCloneApi
	CtvpcShowEndpointServiceApi                  *CtvpcShowEndpointServiceApi
	CtvpcVpceServiceListLabelApi                 *CtvpcVpceServiceListLabelApi
	CtvpcVpceServiceUnbindLabelApi               *CtvpcVpceServiceUnbindLabelApi
	CtvpcVpceServiceBindLabelApi                 *CtvpcVpceServiceBindLabelApi
	CtvpcVpceEndpointListLabelApi                *CtvpcVpceEndpointListLabelApi
	CtvpcVpceEndpointUnbindLabelApi              *CtvpcVpceEndpointUnbindLabelApi
	CtvpcVpceEndpointBindLabelApi                *CtvpcVpceEndpointBindLabelApi
	CtvpcVpceDeleteBackendApi                    *CtvpcVpceDeleteBackendApi
	CtvpcVpceListBackendApi                      *CtvpcVpceListBackendApi
	CtvpcVpceUpdateBackendApi                    *CtvpcVpceUpdateBackendApi
	CtvpcVpcVpcpeerListLabelsApi                 *CtvpcVpcVpcpeerListLabelsApi
	CtvpcVpcVpcpeerUnbindLabelApi                *CtvpcVpcVpcpeerUnbindLabelApi
	CtvpcVpcVpcpeerBindLabelApi                  *CtvpcVpcVpcpeerBindLabelApi
	CtvpcCheckLogAuthApi                         *CtvpcCheckLogAuthApi
	CtvpcListLogUnitApi                          *CtvpcListLogUnitApi
	CtvpcListLogProjectApi                       *CtvpcListLogProjectApi
	CtvpcCreateDelegateRoleApi                   *CtvpcCreateDelegateRoleApi
	CtvpcQueryDelegateRoleApi                    *CtvpcQueryDelegateRoleApi
	CtvpcPrivateZoneRealtimeMetricApi            *CtvpcPrivateZoneRealtimeMetricApi
	CtvpcPrivateZoneHistoryMetricApi             *CtvpcPrivateZoneHistoryMetricApi
	CtvpcPrivateZoneVpcRealtimeMetricApi         *CtvpcPrivateZoneVpcRealtimeMetricApi
	CtvpcPrivateZoneVpcHistoryMetricApi          *CtvpcPrivateZoneVpcHistoryMetricApi
	CtvpcGetFlowPackageMetricApi                 *CtvpcGetFlowPackageMetricApi
	CtvpcEndpointGetOssPolicyApi                 *CtvpcEndpointGetOssPolicyApi
	CtvpcEndpointDeleteOssPolicyApi              *CtvpcEndpointDeleteOssPolicyApi
	CtvpcEndpointCreateOssPolicyApi              *CtvpcEndpointCreateOssPolicyApi
	CtvpcShowNetworkPathReportApi                *CtvpcShowNetworkPathReportApi
	CtvpcListNetworkPathReportApi                *CtvpcListNetworkPathReportApi
	CtvpcVniaDeleteNetworkPathReportApi          *CtvpcVniaDeleteNetworkPathReportApi
	CtvpcVniaShowNetworkPathApi                  *CtvpcVniaShowNetworkPathApi
	CtvpcVniaListNetworkPathApi                  *CtvpcVniaListNetworkPathApi
	CtvpcVniaDeleteNetworkPathApi                *CtvpcVniaDeleteNetworkPathApi
	CtvpcVniaShowNetworkPathAnalysisApi          *CtvpcVniaShowNetworkPathAnalysisApi
	CtvpcVniaListNetworkPathAnalysisApi          *CtvpcVniaListNetworkPathAnalysisApi
	CtvpcVniaDeleteNetworkPathAnalysisApi        *CtvpcVniaDeleteNetworkPathAnalysisApi
	CtvpcVniaCreateNetworkPathAnalysisApi        *CtvpcVniaCreateNetworkPathAnalysisApi
	CtvpcVniaCreateNetworkPathApi                *CtvpcVniaCreateNetworkPathApi
	CtvpcVniaShowInstanceDiagnosisApi            *CtvpcVniaShowInstanceDiagnosisApi
	CtvpcVniaListInstanceDiagnosisReportApi      *CtvpcVniaListInstanceDiagnosisReportApi
	CtvpcVniaListInstanceDiagnosisApi            *CtvpcVniaListInstanceDiagnosisApi
	CtvpcVniaDeleteInstanceDiagnosisReportApi    *CtvpcVniaDeleteInstanceDiagnosisReportApi
	CtvpcVniaDeleteInstanceDiagnosisApi          *CtvpcVniaDeleteInstanceDiagnosisApi
	CtvpcVniaShowInstanceDiagnosisRecordApi      *CtvpcVniaShowInstanceDiagnosisRecordApi
	CtvpcVniaListInstanceDiagnosisRecordApi      *CtvpcVniaListInstanceDiagnosisRecordApi
	CtvpcVniaDeleteInstanceDiagnosisRecordApi    *CtvpcVniaDeleteInstanceDiagnosisRecordApi
	CtvpcVniaCreateInstanceDiagnosisRecordApi    *CtvpcVniaCreateInstanceDiagnosisRecordApi
	CtvpcCreateInstanceDiagnosisApi              *CtvpcCreateInstanceDiagnosisApi
	CtvpcPrefixlistGetAssociationsApi            *CtvpcPrefixlistGetAssociationsApi
	CtvpcPrefixlistShowApi                       *CtvpcPrefixlistShowApi
	CtvpcFlowsessionUpdateTargetApi              *CtvpcFlowsessionUpdateTargetApi
	CtvpcFlowsessionRemoveSourceApi              *CtvpcFlowsessionRemoveSourceApi
	CtvpcFlowsessionAddSourceApi                 *CtvpcFlowsessionAddSourceApi
	CtvpcBandwidthBandwidthUtilizationApi        *CtvpcBandwidthBandwidthUtilizationApi
	CtvpcBandwidthIngerssBandwidthUtilizationApi *CtvpcBandwidthIngerssBandwidthUtilizationApi
	CtvpcBandwidthEgerssBandwidthUtilizationApi  *CtvpcBandwidthEgerssBandwidthUtilizationApi
	CtvpcFlowsessionBuyApi                       *CtvpcFlowsessionBuyApi
	CtvpcEipBandwidthUtilizationApi              *CtvpcEipBandwidthUtilizationApi
	CtvpcEipEgerssBandwidthUtilizationApi        *CtvpcEipEgerssBandwidthUtilizationApi
	CtvpcEipIngerssBandwidthUtilizationApi       *CtvpcEipIngerssBandwidthUtilizationApi
	CtvpcDhcpoptionsetsShowApi                   *CtvpcDhcpoptionsetsShowApi
	CtvpcPrefixlistRuleCreateApi                 *CtvpcPrefixlistRuleCreateApi
	CtvpcPrefixlistCreateApi                     *CtvpcPrefixlistCreateApi
	CtvpcPrefixlistRuleDeleteApi                 *CtvpcPrefixlistRuleDeleteApi
	CtvpcPrefixlistRuleUpdateApi                 *CtvpcPrefixlistRuleUpdateApi
	CtvpcPrefixlistQueryApi                      *CtvpcPrefixlistQueryApi
	CtvpcPrefixlistCloneApi                      *CtvpcPrefixlistCloneApi
	CtvpcPrefixlistDeleteApi                     *CtvpcPrefixlistDeleteApi
	CtvpcPrefixlistUpdateApi                     *CtvpcPrefixlistUpdateApi
	CtvpcV4PortsAsyncAttachBmApi                 *CtvpcV4PortsAsyncAttachBmApi
	CtvpcV4PortsAsyncDetachBmApi                 *CtvpcV4PortsAsyncDetachBmApi
	CtvpcGwlbListTargetGroupApi                  *CtvpcGwlbListTargetGroupApi
	CtvpcGwlbShowTargetGroupApi                  *CtvpcGwlbShowTargetGroupApi
	CtvpcGwlbDeleteTargetGroupApi                *CtvpcGwlbDeleteTargetGroupApi
	CtvpcGwlbUpdateTargetGroupApi                *CtvpcGwlbUpdateTargetGroupApi
	CtvpcGwlbCreateTargetGroupApi                *CtvpcGwlbCreateTargetGroupApi
	CtvpcGwlbListTargetApi                       *CtvpcGwlbListTargetApi
	CtvpcGwlbShowTargetApi                       *CtvpcGwlbShowTargetApi
	CtvpcGwlbDeleteTargetApi                     *CtvpcGwlbDeleteTargetApi
	CtvpcGwlbUpdateTargetApi                     *CtvpcGwlbUpdateTargetApi
	CtvpcGwlbCreateTargetApi                     *CtvpcGwlbCreateTargetApi
	CtvpcIplistenerListApi                       *CtvpcIplistenerListApi
	CtvpcIplistenerShowApi                       *CtvpcIplistenerShowApi
	CtvpcIplistenerDeleteApi                     *CtvpcIplistenerDeleteApi
	CtvpcIplistenerUpdateApi                     *CtvpcIplistenerUpdateApi
	CtvpcIplistenerCreateApi                     *CtvpcIplistenerCreateApi
	CtvpcGwlbListApi                             *CtvpcGwlbListApi
	CtvpcGwlbShowApi                             *CtvpcGwlbShowApi
	CtvpcGwlbEnableDeleteProtectionApi           *CtvpcGwlbEnableDeleteProtectionApi
	CtvpcGwlbEnableIpv6Api                       *CtvpcGwlbEnableIpv6Api
	CtvpcGwlbDisableIpv6Api                      *CtvpcGwlbDisableIpv6Api
	CtvpcGwlbDisableDeleteProtectionApi          *CtvpcGwlbDisableDeleteProtectionApi
	CtvpcGwlbDeleteApi                           *CtvpcGwlbDeleteApi
	CtvpcGwlbUpdateApi                           *CtvpcGwlbUpdateApi
	CtvpcFlowsessionRefundApi                    *CtvpcFlowsessionRefundApi
	CtvpcShowSnatApi                             *CtvpcShowSnatApi
	CtvpcListSnatsApi                            *CtvpcListSnatsApi
	CtvpcGwlbCreateApi                           *CtvpcGwlbCreateApi
	CtvpcQueryCtyunServiceApi                    *CtvpcQueryCtyunServiceApi
	CtvpcTerminateCycleApi                       *CtvpcTerminateCycleApi
	CtvpcChangeToNeedApi                         *CtvpcChangeToNeedApi
	CtvpcChangeToCycleApi                        *CtvpcChangeToCycleApi
	CtvpcQueryToCyclePriceApi                    *CtvpcQueryToCyclePriceApi
	CtvpcQueryToNeedPriceApi                     *CtvpcQueryToNeedPriceApi
	CtvpcQueryLabelsByResourceApi                *CtvpcQueryLabelsByResourceApi
	CtvpcQueryResourcesByLabelApi                *CtvpcQueryResourcesByLabelApi
	CtvpcResourceUnbindLabelApi                  *CtvpcResourceUnbindLabelApi
	CtvpcResourceBindLabelApi                    *CtvpcResourceBindLabelApi
	CtvpcSgRulePreCheckApi                       *CtvpcSgRulePreCheckApi
	CtvpcSubnetDisassociateRouteTableApi         *CtvpcSubnetDisassociateRouteTableApi
	CtvpcShowSgRuleApi                           *CtvpcShowSgRuleApi
	CtvpcDhcpreplacevpcApi                       *CtvpcDhcpreplacevpcApi
	CtvpcDhcpdisassociatevpcApi                  *CtvpcDhcpdisassociatevpcApi
	CtvpcDhcpassociatevpcApi                     *CtvpcDhcpassociatevpcApi
	CtvpcDhcplistunbindvpcApi                    *CtvpcDhcplistunbindvpcApi
	CtvpcDhcplistvpcApi                          *CtvpcDhcplistvpcApi
	CtvpcDhcpoptionsetsqueryApi                  *CtvpcDhcpoptionsetsqueryApi
	CtvpcDhcpoptionsetsdeleteApi                 *CtvpcDhcpoptionsetsdeleteApi
	CtvpcUpdatedhcpoptionsetsApi                 *CtvpcUpdatedhcpoptionsetsApi
	CtvpcDhcpoptionsetscreateApi                 *CtvpcDhcpoptionsetscreateApi
	CtvpcTunnelCheckApi                          *CtvpcTunnelCheckApi
	CtvpcGwQueryApi                              *CtvpcGwQueryApi
	CtvpcL2gwConnectionQueryApi                  *CtvpcL2gwConnectionQueryApi
	CtvpcL2gwConnectionUpdateApi                 *CtvpcL2gwConnectionUpdateApi
	CtvpcL2gwConnectionDeleteApi                 *CtvpcL2gwConnectionDeleteApi
	CtvpcL2gwConnectionCreateApi                 *CtvpcL2gwConnectionCreateApi
	CtvpcL2gwQueryApi                            *CtvpcL2gwQueryApi
	CtvpcL2gwUpdateApi                           *CtvpcL2gwUpdateApi
	CtvpcL2gwDeleteApi                           *CtvpcL2gwDeleteApi
	CtvpcL2gwCreateApi                           *CtvpcL2gwCreateApi
	CtvpcAcceptEndpointApplyApi                  *CtvpcAcceptEndpointApplyApi
	CtvpcRefuseEndpointApplyApi                  *CtvpcRefuseEndpointApplyApi
	CtvpcModifyEndpointServiceApi                *CtvpcModifyEndpointServiceApi
	CtvpcModifyNatSpecApi                        *CtvpcModifyNatSpecApi
	CtvpcCheckPtrRecordApi                       *CtvpcCheckPtrRecordApi
	CtvpcCheckPtrApi                             *CtvpcCheckPtrApi
	CtvpcCheckAAAAApi                            *CtvpcCheckAAAAApi
	CtvpcQueryCreateEndpointPriceApi             *CtvpcQueryCreateEndpointPriceApi
	CtvpcGetSgAssociateVmsApi                    *CtvpcGetSgAssociateVmsApi
	CtvpcListZoneBindLabelsApi                   *CtvpcListZoneBindLabelsApi
	CtvpcZoneUnbindLabelsApi                     *CtvpcZoneUnbindLabelsApi
	CtvpcZoneBindLabelsApi                       *CtvpcZoneBindLabelsApi
	CtvpcSetZoneProxyPatternApi                  *CtvpcSetZoneProxyPatternApi
	CtvpcGetZoneQuotaApi                         *CtvpcGetZoneQuotaApi
	CtvpcGetZoneRecordQuotaApi                   *CtvpcGetZoneRecordQuotaApi
	CtvpcListSharedZoneRecordsApi                *CtvpcListSharedZoneRecordsApi
	CtvpcGetZoneBindVpcsApi                      *CtvpcGetZoneBindVpcsApi
	CtvpcQueryAllZonesAndVpcsApi                 *CtvpcQueryAllZonesAndVpcsApi
	CtvpcGetNameserverApi                        *CtvpcGetNameserverApi
	CtvpcCheckZoneNameApi                        *CtvpcCheckZoneNameApi
	CtvpcCheckTxtApi                             *CtvpcCheckTxtApi
	CtvpcCheckMxApi                              *CtvpcCheckMxApi
	CtvpcCheckCnameApi                           *CtvpcCheckCnameApi
	CtvpcGetVpcBindedZonesApi                    *CtvpcGetVpcBindedZonesApi
	CtvpcEnablePrivateZoneRecordApi              *CtvpcEnablePrivateZoneRecordApi
	CtvpcDisablePrivateZoneRecordApi             *CtvpcDisablePrivateZoneRecordApi
	CtvpcModifyPrivateZoneRecordDescApi          *CtvpcModifyPrivateZoneRecordDescApi
	CtvpcNatQueryRenewPriceApi                   *CtvpcNatQueryRenewPriceApi
	CtvpcNatQueryModifyPriceApi                  *CtvpcNatQueryModifyPriceApi
	CtvpcNatQueryCreatePriceApi                  *CtvpcNatQueryCreatePriceApi
	CtvpcIpv6BandwidthRenewApi                   *CtvpcIpv6BandwidthRenewApi
	CtvpcIpv6BandwidthQueryRenewPriceApi         *CtvpcIpv6BandwidthQueryRenewPriceApi
	CtvpcIpv6BandwidthQueryModifyPriceApi        *CtvpcIpv6BandwidthQueryModifyPriceApi
	CtvpcIpv6BandwidthQueryCreatePriceApi        *CtvpcIpv6BandwidthQueryCreatePriceApi
	CtvpcEipQueryRenewPriceApi                   *CtvpcEipQueryRenewPriceApi
	CtvpcEipQueryModifyPriceApi                  *CtvpcEipQueryModifyPriceApi
	CtvpcEipQueryCreatePriceApi                  *CtvpcEipQueryCreatePriceApi
	CtvpcBandwidthRenewApi                       *CtvpcBandwidthRenewApi
	CtvpcBandwidthQueryRenewPriceApi             *CtvpcBandwidthQueryRenewPriceApi
	CtvpcBandwidthQueryModifyPriceApi            *CtvpcBandwidthQueryModifyPriceApi
	CtvpcBandwidthQueryCreatePriceApi            *CtvpcBandwidthQueryCreatePriceApi
	CtvpcShowFlowSessionApi                      *CtvpcShowFlowSessionApi
	CtvpcListFlowSessionsApi                     *CtvpcListFlowSessionsApi
	CtvpcUpdateFlowSessionApi                    *CtvpcUpdateFlowSessionApi
	CtvpcStopFlowSessionApi                      *CtvpcStopFlowSessionApi
	CtvpcStartFlowSessionApi                     *CtvpcStartFlowSessionApi
	CtvpcDeleteFlowSessionApi                    *CtvpcDeleteFlowSessionApi
	CtvpcCreateFlowSessionApi                    *CtvpcCreateFlowSessionApi
	CtvpcChangeFilteRulePriorityApi              *CtvpcChangeFilteRulePriorityApi
	CtvpcListMirrorFlowFilterRuleApi             *CtvpcListMirrorFlowFilterRuleApi
	CtvpcShowMirrorFlowFilterApi                 *CtvpcShowMirrorFlowFilterApi
	CtvpcListMirrorFlowFilterApi                 *CtvpcListMirrorFlowFilterApi
	CtvpcUpdateMirrorFlowFilterRuleApi           *CtvpcUpdateMirrorFlowFilterRuleApi
	CtvpcUpdateMirrorFlowFilterApi               *CtvpcUpdateMirrorFlowFilterApi
	CtvpcDeleteMirrorFlowFilterRuleApi           *CtvpcDeleteMirrorFlowFilterRuleApi
	CtvpcDeleteMirrorFlowFilterApi               *CtvpcDeleteMirrorFlowFilterApi
	CtvpcCreateMirrorFlowFilterApi               *CtvpcCreateMirrorFlowFilterApi
	CtvpcCreateOutFilterRuleApi                  *CtvpcCreateOutFilterRuleApi
	CtvpcCreateInFilterRuleApi                   *CtvpcCreateInFilterRuleApi
	CtvpcAttachPortBmApi                         *CtvpcAttachPortBmApi
	CtvpcNewPrivateZoneRecordListApi             *CtvpcNewPrivateZoneRecordListApi
	CtvpcNewPrivateZoneListApi                   *CtvpcNewPrivateZoneListApi
	CtvpcNewACLListApi                           *CtvpcNewACLListApi
	CtvpcNewEndpointServiceWhiteListApi          *CtvpcNewEndpointServiceWhiteListApi
	CtvpcNewEndpointServicesListApi              *CtvpcNewEndpointServicesListApi
	CtvpcNewEndpointsListApi                     *CtvpcNewEndpointsListApi
	CtvpcNewPortsListApi                         *CtvpcNewPortsListApi
	CtvpcNewIPv6ListApi                          *CtvpcNewIPv6ListApi
	CtvpcNewRouteRulesListApi                    *CtvpcNewRouteRulesListApi
	CtvpcNewRouteTableListApi                    *CtvpcNewRouteTableListApi
	CtvpcNewQuerySecurityGroupsApi               *CtvpcNewQuerySecurityGroupsApi
	CtvpcNewSubnetListApi                        *CtvpcNewSubnetListApi
	CtvpcNewVpcListApi                           *CtvpcNewVpcListApi
	CtvpcNewIPv6BandwidthListApi                 *CtvpcNewIPv6BandwidthListApi
	CtvpcNewBandwidthListApi                     *CtvpcNewBandwidthListApi
	CtvpcNewEipListApi                           *CtvpcNewEipListApi
	CtvpcNewQueryEIPRealtimeMonitorApi           *CtvpcNewQueryEIPRealtimeMonitorApi
	CtvpcNewQueryEIPHistoryMonitorApi            *CtvpcNewQueryEIPHistoryMonitorApi
	CtvpcCreateEipWithIpAddressApi               *CtvpcCreateEipWithIpAddressApi
	CtvpcGetEipFilingStatusApi                   *CtvpcGetEipFilingStatusApi
	CtvpcSubnetEnableIPv6Api                     *CtvpcSubnetEnableIPv6Api
	CtvpcSgBatchDetachPortsApi                   *CtvpcSgBatchDetachPortsApi
	CtvpcSgBatchAttachPortsApi                   *CtvpcSgBatchAttachPortsApi
	CtvpcDeleteRouteRuleApi                      *CtvpcDeleteRouteRuleApi
	CtvpcModifyRouteRuleApi                      *CtvpcModifyRouteRuleApi
	CtvpcCreateRouteRuleApi                      *CtvpcCreateRouteRuleApi
	CtvpcCreateSubnetACLApi                      *CtvpcCreateSubnetACLApi
	CtvpcListVpcPeerRequestsApi                  *CtvpcListVpcPeerRequestsApi
	CtvpcAgreeVpcPeerRequestApi                  *CtvpcAgreeVpcPeerRequestApi
	CtvpcRejectVpcPeerRequestApi                 *CtvpcRejectVpcPeerRequestApi
	CtvpcListIPv4GwApi                           *CtvpcListIPv4GwApi
	CtvpcShowIPv4GwApi                           *CtvpcShowIPv4GwApi
	CtvpcIpv4GwUnbindRouteTableApi               *CtvpcIpv4GwUnbindRouteTableApi
	CtvpcIpv4GwBindRouteTableApi                 *CtvpcIpv4GwBindRouteTableApi
	CtvpcListSubnetUsedIPsApi                    *CtvpcListSubnetUsedIPsApi
	CtvpcCreateGatewayRouteTableApi              *CtvpcCreateGatewayRouteTableApi
	CtvpcPortReplaceSubnetApi                    *CtvpcPortReplaceSubnetApi
	CtvpcPortReplaceVPCApi                       *CtvpcPortReplaceVPCApi
	CtvpcShowEndpointServiceConnectionsApi       *CtvpcShowEndpointServiceConnectionsApi
	CtvpcUpdateEndpointServiceConnectionsApi     *CtvpcUpdateEndpointServiceConnectionsApi
	CtvpcListEndpointServiceWhitelistApi         *CtvpcListEndpointServiceWhitelistApi
	CtvpcDeleteEndpointServiceWhitelistApi       *CtvpcDeleteEndpointServiceWhitelistApi
	CtvpcCreateEndpointServiceWhitelistApi       *CtvpcCreateEndpointServiceWhitelistApi
	CtvpcListEndpointServiceApi                  *CtvpcListEndpointServiceApi
	CtvpcDeleteEndpointServiceApi                *CtvpcDeleteEndpointServiceApi
	CtvpcCreateEndpointServiceApi                *CtvpcCreateEndpointServiceApi
	CtvpcDeleteEndpointWhitelistApi              *CtvpcDeleteEndpointWhitelistApi
	CtvpcShowEndpointWhitelistApi                *CtvpcShowEndpointWhitelistApi
	CtvpcAddEndpointWhitelistApi                 *CtvpcAddEndpointWhitelistApi
	CtvpcDeleteEndpointApi                       *CtvpcDeleteEndpointApi
	CtvpcShowEndpointApi                         *CtvpcShowEndpointApi
	CtvpcListEndpointApi                         *CtvpcListEndpointApi
	CtvpcUpdateEndpointApi                       *CtvpcUpdateEndpointApi
	CtvpcCreateEndpointApi                       *CtvpcCreateEndpointApi
	CtvpcListEndpointServiceTransitIPApi         *CtvpcListEndpointServiceTransitIPApi
	CtvpcDeleteEndpointServiceTransitIPApi       *CtvpcDeleteEndpointServiceTransitIPApi
	CtvpcCreateEndpointServiceTransitIPApi       *CtvpcCreateEndpointServiceTransitIPApi
	CtvpcDeleteEndpointServiceReverseRuleApi     *CtvpcDeleteEndpointServiceReverseRuleApi
	CtvpcListEndpointServiceReverseRuleApi       *CtvpcListEndpointServiceReverseRuleApi
	CtvpcCreateEndpointServiceReverseRuleApi     *CtvpcCreateEndpointServiceReverseRuleApi
	CtvpcDeleteEndpointServiceRuleApi            *CtvpcDeleteEndpointServiceRuleApi
	CtvpcCreateEndpointServiceRuleApi            *CtvpcCreateEndpointServiceRuleApi
	CtvpcBatchDeleteZoneRecordsApi               *CtvpcBatchDeleteZoneRecordsApi
	CtvpcChangeEipNameApi                        *CtvpcChangeEipNameApi
	CtvpcShowFlowPackageApi                      *CtvpcShowFlowPackageApi
	CtvpcListFlowPackageApi                      *CtvpcListFlowPackageApi
	CtvpcRefundFlowPackageApi                    *CtvpcRefundFlowPackageApi
	CtvpcBuyFlowPackageApi                       *CtvpcBuyFlowPackageApi
	CtvpcQueryFlowPackagePriceApi                *CtvpcQueryFlowPackagePriceApi
	CtvpcModifyIPv6BandwidthSpecApi              *CtvpcModifyIPv6BandwidthSpecApi
	CtvpcDeleteIPv6BandwidthApi                  *CtvpcDeleteIPv6BandwidthApi
	CtvpcCreateIPv6BandwidthApi                  *CtvpcCreateIPv6BandwidthApi
	CtvpcUpdateIPv6BandwidthAttributeApi         *CtvpcUpdateIPv6BandwidthAttributeApi
	CtvpcListIPv6BandwidthApi                    *CtvpcListIPv6BandwidthApi
	CtvpcShowIPv6BandwidthApi                    *CtvpcShowIPv6BandwidthApi
	CtvpcRemoveIPv6FromIPv6BandwidthApi          *CtvpcRemoveIPv6FromIPv6BandwidthApi
	CtvpcAddIPv6ToIPv6BandwidthApi               *CtvpcAddIPv6ToIPv6BandwidthApi
	CtvpcQueryEipRealtimeMonitorApi              *CtvpcQueryEipRealtimeMonitorApi
	CtvpcQueryEipHistoryMonitorApi               *CtvpcQueryEipHistoryMonitorApi
	CtvpcBatchCheckEipAddressApi                 *CtvpcBatchCheckEipAddressApi
	CtvpcCheckEipAddressApi                      *CtvpcCheckEipAddressApi
	CtvpcBatchJoinSecurityGroupApi               *CtvpcBatchJoinSecurityGroupApi
	CtvpcUpdateSecurityGroupAttributeApi         *CtvpcUpdateSecurityGroupAttributeApi
	CtvpcShowEipApi                              *CtvpcShowEipApi
	CtvpcAttachEipToPortApi                      *CtvpcAttachEipToPortApi
	CtvpcUpdateIPv6StatusForVpcApi               *CtvpcUpdateIPv6StatusForVpcApi
	CtvpcDeleteHavipApi                          *CtvpcDeleteHavipApi
	CtvpcShowHavipApi                            *CtvpcShowHavipApi
	CtvpcUnassignSecondaryPrivateIPsFromPortApi  *CtvpcUnassignSecondaryPrivateIPsFromPortApi
	CtvpcDetachPortApi                           *CtvpcDetachPortApi
	CtvpcAttachPortApi                           *CtvpcAttachPortApi
	CtvpcAssignSecondaryPrivateIPsToPortApi      *CtvpcAssignSecondaryPrivateIPsToPortApi
	CtvpcCheckPortStatusApi                      *CtvpcCheckPortStatusApi
	CtvpcVpcListPortApi                          *CtvpcVpcListPortApi
	CtvpcBatchCheckPortStatusApi                 *CtvpcBatchCheckPortStatusApi
	CtvpcBatchUnassignIPv6FromPortApi            *CtvpcBatchUnassignIPv6FromPortApi
	CtvpcBatchAssignIPv6ToPortApi                *CtvpcBatchAssignIPv6ToPortApi
	CtvpcUnassignIPv6FromPortApi                 *CtvpcUnassignIPv6FromPortApi
	CtvpcAssignIPv6ToPortApi                     *CtvpcAssignIPv6ToPortApi
	CtvpcDeletePortApi                           *CtvpcDeletePortApi
	CtvpcCreatePortApi                           *CtvpcCreatePortApi
	CtvpcUpdatePortApi                           *CtvpcUpdatePortApi
	CtvpcShowDnatEntryApi                        *CtvpcShowDnatEntryApi
	CtvpcListDnatEntriesApi                      *CtvpcListDnatEntriesApi
	CtvpcRenewNatGatewayApi                      *CtvpcRenewNatGatewayApi
	CtvpcShowNatGatewayApi                       *CtvpcShowNatGatewayApi
	CtvpcListNatGatewaysApi                      *CtvpcListNatGatewaysApi
	CtvpcDeleteSnatEntryApi                      *CtvpcDeleteSnatEntryApi
	CtvpcDeleteNatGatewayApi                     *CtvpcDeleteNatGatewayApi
	CtvpcDeleteDnatEntryApi                      *CtvpcDeleteDnatEntryApi
	CtvpcCreateSnatEntryApi                      *CtvpcCreateSnatEntryApi
	CtvpcCreateNatGatewayApi                     *CtvpcCreateNatGatewayApi
	CtvpcCreateDnatEntryApi                      *CtvpcCreateDnatEntryApi
	CtvpcUpdateSnatEntryAttributeApi             *CtvpcUpdateSnatEntryAttributeApi
	CtvpcUpdateNatGatewayAttributeApi            *CtvpcUpdateNatGatewayAttributeApi
	CtvpcUpdateDnatEntryAttributeApi             *CtvpcUpdateDnatEntryAttributeApi
	CtvpcDisassociateEipsFromSnatApi             *CtvpcDisassociateEipsFromSnatApi
	CtvpcAssociateEipsToSnatApi                  *CtvpcAssociateEipsToSnatApi
	CtvpcDeleteAclRuleApi                        *CtvpcDeleteAclRuleApi
	CtvpcDeleteAclApi                            *CtvpcDeleteAclApi
	CtvpcCreateAclRuleApi                        *CtvpcCreateAclRuleApi
	CtvpcCreateAclApi                            *CtvpcCreateAclApi
	CtvpcUpdateAclRuleAttributeApi               *CtvpcUpdateAclRuleAttributeApi
	CtvpcUpdateAclAttributeApi                   *CtvpcUpdateAclAttributeApi
	CtvpcShowAclApi                              *CtvpcShowAclApi
	CtvpcListAclApi                              *CtvpcListAclApi
	CtvpcListAclRuleApi                          *CtvpcListAclRuleApi
	CtvpcShowIPv6GatewayApi                      *CtvpcShowIPv6GatewayApi
	CtvpcListIPv6GatewayApi                      *CtvpcListIPv6GatewayApi
	CtvpcDeleteIPv6GatewayApi                    *CtvpcDeleteIPv6GatewayApi
	CtvpcCreateIPv6GatewayApi                    *CtvpcCreateIPv6GatewayApi
	CtvpcShowPrivateZoneRecordApi                *CtvpcShowPrivateZoneRecordApi
	CtvpcListPrivateZoneRecordApi                *CtvpcListPrivateZoneRecordApi
	CtvpcDeletePrivateZoneRecordApi              *CtvpcDeletePrivateZoneRecordApi
	CtvpcUpdatePrivateZoneRecordAttributeApi     *CtvpcUpdatePrivateZoneRecordAttributeApi
	CtvpcCreatePrivateZoneRecordApi              *CtvpcCreatePrivateZoneRecordApi
	CtvpcShowPrivateZoneApi                      *CtvpcShowPrivateZoneApi
	CtvpcListPrivateZoneApi                      *CtvpcListPrivateZoneApi
	CtvpcDisassociatePrivateZoneFromVpcApi       *CtvpcDisassociatePrivateZoneFromVpcApi
	CtvpcAssociatePrivateZoneToVpcApi            *CtvpcAssociatePrivateZoneToVpcApi
	CtvpcUpdatePrivateZoneAttributeApi           *CtvpcUpdatePrivateZoneAttributeApi
	CtvpcDeletePrivateZoneApi                    *CtvpcDeletePrivateZoneApi
	CtvpcCreatePrivateZoneApi                    *CtvpcCreatePrivateZoneApi
	CtvpcShowRouteTableApi                       *CtvpcShowRouteTableApi
	CtvpcListRouteTableRulesApi                  *CtvpcListRouteTableRulesApi
	CtvpcListRouteTableApi                       *CtvpcListRouteTableApi
	CtvpcDeleteRouteTableRulesApi                *CtvpcDeleteRouteTableRulesApi
	CtvpcDeleteRouteTableApi                     *CtvpcDeleteRouteTableApi
	CtvpcCreateRouteTableRulesApi                *CtvpcCreateRouteTableRulesApi
	CtvpcDisassociateEipApi                      *CtvpcDisassociateEipApi
	CtvpcCreateRouteTableApi                     *CtvpcCreateRouteTableApi
	CtvpcUpdateRouteTableRulesAttributeApi       *CtvpcUpdateRouteTableRulesAttributeApi
	CtvpcUpdateRouteTableAttributeApi            *CtvpcUpdateRouteTableAttributeApi
	CtvpcShowVpcPeerConnectionApi                *CtvpcShowVpcPeerConnectionApi
	CtvpcModifyEipSpecApi                        *CtvpcModifyEipSpecApi
	CtvpcListVpcPeerConnectionApi                *CtvpcListVpcPeerConnectionApi
	CtvpcUpdateVpcPeerConnectionAttributeApi     *CtvpcUpdateVpcPeerConnectionAttributeApi
	CtvpcShowIPv6Api                             *CtvpcShowIPv6Api
	CtvpcListIPv6Api                             *CtvpcListIPv6Api
	CtvpcDeleteVpcPeerConnectionApi              *CtvpcDeleteVpcPeerConnectionApi
	CtvpcAssociateEipApi                         *CtvpcAssociateEipApi
	CtvpcCreateVpcPeerConnectionApi              *CtvpcCreateVpcPeerConnectionApi
	CtvpcRenewEipApi                             *CtvpcRenewEipApi
	CtvpcDisassociateSubnetAclApi                *CtvpcDisassociateSubnetAclApi
	CtvpcReplaceSubnetRouteTableApi              *CtvpcReplaceSubnetRouteTableApi
	CtvpcReplaceSubnetAclApi                     *CtvpcReplaceSubnetAclApi
	CtvpcCreateEipApi                            *CtvpcCreateEipApi
	CtvpcDeleteEipApi                            *CtvpcDeleteEipApi
	CtvpcListEipApi                              *CtvpcListEipApi
	CtvpcVpcDeleteSubnetApi                      *CtvpcVpcDeleteSubnetApi
	CtvpcUpDateSubnetApi                         *CtvpcUpDateSubnetApi
	CtvpcDeleteVpcApi                            *CtvpcDeleteVpcApi
	CtvpcUpdateSubnetIPv6StatusApi               *CtvpcUpdateSubnetIPv6StatusApi
	CtvpcUpdateVpcAttributeApi                   *CtvpcUpdateVpcAttributeApi
	CtvpcDisassociateSecondaryCidrsFromVpcApi    *CtvpcDisassociateSecondaryCidrsFromVpcApi
	CtvpcAssociateSecondaryCidrsToVpcApi         *CtvpcAssociateSecondaryCidrsToVpcApi
	CtvpcDisassociateIPv6FromBandwidthApi        *CtvpcDisassociateIPv6FromBandwidthApi
	CtvpcAssociateIPv6ToBandwidthApi             *CtvpcAssociateIPv6ToBandwidthApi
	CtvpcDisassociateEipFromBandwidthApi         *CtvpcDisassociateEipFromBandwidthApi
	CtvpcAssociateEipToBandwidthApi              *CtvpcAssociateEipToBandwidthApi
	CtvpcListBandwidthApi                        *CtvpcListBandwidthApi
	CtvpcShowBandwidthApi                        *CtvpcShowBandwidthApi
	CtvpcUpdateBandwidthAttributeApi             *CtvpcUpdateBandwidthAttributeApi
	CtvpcModifyBandwidthSpecApi                  *CtvpcModifyBandwidthSpecApi
	CtvpcDeleteBandwidthApi                      *CtvpcDeleteBandwidthApi
	CtvpcCreateBandwidthApi                      *CtvpcCreateBandwidthApi
	CtvpcShowPortApi                             *CtvpcShowPortApi
	CtvpcUnbindHavipApi                          *CtvpcUnbindHavipApi
	CtvpcListHavipApi                            *CtvpcListHavipApi
	CtvpcBindHavipApi                            *CtvpcBindHavipApi
	CtvpcCreateHavipApi                          *CtvpcCreateHavipApi
	CtvpcRevokeSgEngressRuleApi                  *CtvpcRevokeSgEngressRuleApi
	CtvpcRevokeSgIngressRuleApi                  *CtvpcRevokeSgIngressRuleApi
	CtvpcModifySgEngressRuleApi                  *CtvpcModifySgEngressRuleApi
	CtvpcModifySgIngressRuleApi                  *CtvpcModifySgIngressRuleApi
	CtvpcCreateSgEgressRuleApi                   *CtvpcCreateSgEgressRuleApi
	CtvpcCreateSgIngressRuleApi                  *CtvpcCreateSgIngressRuleApi
	CtvpcVpcDeleteSecurityGroupApi               *CtvpcVpcDeleteSecurityGroupApi
	CtvpcVpcCreateSecurityGroupApi               *CtvpcVpcCreateSecurityGroupApi
	CtvpcLeaveSecurityGroupApi                   *CtvpcLeaveSecurityGroupApi
	CtvpcJoinSecurityGroupApi                    *CtvpcJoinSecurityGroupApi
	CtvpcShowSecurityGroupApi                    *CtvpcShowSecurityGroupApi
	CtvpcListSecurityGroupsApi                   *CtvpcListSecurityGroupsApi
	CtvpcListSubnetApi                           *CtvpcListSubnetApi
	CtvpcShowSubnetApi                           *CtvpcShowSubnetApi
	CtvpcListVpcApi                              *CtvpcListVpcApi
	CtvpcShowVpcApi                              *CtvpcShowVpcApi
	CtvpcVpcCreateSubnetApi                      *CtvpcVpcCreateSubnetApi
	CtvpcCreateVpc1Api                           *CtvpcCreateVpc1Api
}

func NewApis(endpointUrl string, client *core.CtyunClient) *Apis {
	client.RegisterEndpoint(core.Endpoint{
		Name: EndpointName,
		Url:  endpointUrl,
	})
	return &Apis{
		CtvpcL2gwQueryCreatePriceApi:                 NewCtvpcL2gwQueryCreatePriceApi(client),
		CtvpcL2gwQueryRenewPriceApi:                  NewCtvpcL2gwQueryRenewPriceApi(client),
		CtvpcL2gwRenewApi:                            NewCtvpcL2gwRenewApi(client),
		CtvpcModifyEndpointServiceIpVersionApi:       NewCtvpcModifyEndpointServiceIpVersionApi(client),
		CtvpcModifyEndpointIpVersionApi:              NewCtvpcModifyEndpointIpVersionApi(client),
		CtvpcModifyVpcAccessLogApi:                   NewCtvpcModifyVpcAccessLogApi(client),
		CtvpcDeleteVpcAccessLogApi:                   NewCtvpcDeleteVpcAccessLogApi(client),
		CtvpcAddVpcAccessLogApi:                      NewCtvpcAddVpcAccessLogApi(client),
		CtvpcListVpcAccessLogApi:                     NewCtvpcListVpcAccessLogApi(client),
		CtvpcGetVpcPeerRouteApi:                      NewCtvpcGetVpcPeerRouteApi(client),
		CtvpcDeleteVpcPeerRouteApi:                   NewCtvpcDeleteVpcPeerRouteApi(client),
		CtvpcCreateVpcPeerRouteApi:                   NewCtvpcCreateVpcPeerRouteApi(client),
		CtvpcAclCloneApi:                             NewCtvpcAclCloneApi(client),
		CtvpcShowEndpointServiceApi:                  NewCtvpcShowEndpointServiceApi(client),
		CtvpcVpceServiceListLabelApi:                 NewCtvpcVpceServiceListLabelApi(client),
		CtvpcVpceServiceUnbindLabelApi:               NewCtvpcVpceServiceUnbindLabelApi(client),
		CtvpcVpceServiceBindLabelApi:                 NewCtvpcVpceServiceBindLabelApi(client),
		CtvpcVpceEndpointListLabelApi:                NewCtvpcVpceEndpointListLabelApi(client),
		CtvpcVpceEndpointUnbindLabelApi:              NewCtvpcVpceEndpointUnbindLabelApi(client),
		CtvpcVpceEndpointBindLabelApi:                NewCtvpcVpceEndpointBindLabelApi(client),
		CtvpcVpceDeleteBackendApi:                    NewCtvpcVpceDeleteBackendApi(client),
		CtvpcVpceListBackendApi:                      NewCtvpcVpceListBackendApi(client),
		CtvpcVpceUpdateBackendApi:                    NewCtvpcVpceUpdateBackendApi(client),
		CtvpcVpcVpcpeerListLabelsApi:                 NewCtvpcVpcVpcpeerListLabelsApi(client),
		CtvpcVpcVpcpeerUnbindLabelApi:                NewCtvpcVpcVpcpeerUnbindLabelApi(client),
		CtvpcVpcVpcpeerBindLabelApi:                  NewCtvpcVpcVpcpeerBindLabelApi(client),
		CtvpcCheckLogAuthApi:                         NewCtvpcCheckLogAuthApi(client),
		CtvpcListLogUnitApi:                          NewCtvpcListLogUnitApi(client),
		CtvpcListLogProjectApi:                       NewCtvpcListLogProjectApi(client),
		CtvpcCreateDelegateRoleApi:                   NewCtvpcCreateDelegateRoleApi(client),
		CtvpcQueryDelegateRoleApi:                    NewCtvpcQueryDelegateRoleApi(client),
		CtvpcPrivateZoneRealtimeMetricApi:            NewCtvpcPrivateZoneRealtimeMetricApi(client),
		CtvpcPrivateZoneHistoryMetricApi:             NewCtvpcPrivateZoneHistoryMetricApi(client),
		CtvpcPrivateZoneVpcRealtimeMetricApi:         NewCtvpcPrivateZoneVpcRealtimeMetricApi(client),
		CtvpcPrivateZoneVpcHistoryMetricApi:          NewCtvpcPrivateZoneVpcHistoryMetricApi(client),
		CtvpcGetFlowPackageMetricApi:                 NewCtvpcGetFlowPackageMetricApi(client),
		CtvpcEndpointGetOssPolicyApi:                 NewCtvpcEndpointGetOssPolicyApi(client),
		CtvpcEndpointDeleteOssPolicyApi:              NewCtvpcEndpointDeleteOssPolicyApi(client),
		CtvpcEndpointCreateOssPolicyApi:              NewCtvpcEndpointCreateOssPolicyApi(client),
		CtvpcShowNetworkPathReportApi:                NewCtvpcShowNetworkPathReportApi(client),
		CtvpcListNetworkPathReportApi:                NewCtvpcListNetworkPathReportApi(client),
		CtvpcVniaDeleteNetworkPathReportApi:          NewCtvpcVniaDeleteNetworkPathReportApi(client),
		CtvpcVniaShowNetworkPathApi:                  NewCtvpcVniaShowNetworkPathApi(client),
		CtvpcVniaListNetworkPathApi:                  NewCtvpcVniaListNetworkPathApi(client),
		CtvpcVniaDeleteNetworkPathApi:                NewCtvpcVniaDeleteNetworkPathApi(client),
		CtvpcVniaShowNetworkPathAnalysisApi:          NewCtvpcVniaShowNetworkPathAnalysisApi(client),
		CtvpcVniaListNetworkPathAnalysisApi:          NewCtvpcVniaListNetworkPathAnalysisApi(client),
		CtvpcVniaDeleteNetworkPathAnalysisApi:        NewCtvpcVniaDeleteNetworkPathAnalysisApi(client),
		CtvpcVniaCreateNetworkPathAnalysisApi:        NewCtvpcVniaCreateNetworkPathAnalysisApi(client),
		CtvpcVniaCreateNetworkPathApi:                NewCtvpcVniaCreateNetworkPathApi(client),
		CtvpcVniaShowInstanceDiagnosisApi:            NewCtvpcVniaShowInstanceDiagnosisApi(client),
		CtvpcVniaListInstanceDiagnosisReportApi:      NewCtvpcVniaListInstanceDiagnosisReportApi(client),
		CtvpcVniaListInstanceDiagnosisApi:            NewCtvpcVniaListInstanceDiagnosisApi(client),
		CtvpcVniaDeleteInstanceDiagnosisReportApi:    NewCtvpcVniaDeleteInstanceDiagnosisReportApi(client),
		CtvpcVniaDeleteInstanceDiagnosisApi:          NewCtvpcVniaDeleteInstanceDiagnosisApi(client),
		CtvpcVniaShowInstanceDiagnosisRecordApi:      NewCtvpcVniaShowInstanceDiagnosisRecordApi(client),
		CtvpcVniaListInstanceDiagnosisRecordApi:      NewCtvpcVniaListInstanceDiagnosisRecordApi(client),
		CtvpcVniaDeleteInstanceDiagnosisRecordApi:    NewCtvpcVniaDeleteInstanceDiagnosisRecordApi(client),
		CtvpcVniaCreateInstanceDiagnosisRecordApi:    NewCtvpcVniaCreateInstanceDiagnosisRecordApi(client),
		CtvpcCreateInstanceDiagnosisApi:              NewCtvpcCreateInstanceDiagnosisApi(client),
		CtvpcPrefixlistGetAssociationsApi:            NewCtvpcPrefixlistGetAssociationsApi(client),
		CtvpcPrefixlistShowApi:                       NewCtvpcPrefixlistShowApi(client),
		CtvpcFlowsessionUpdateTargetApi:              NewCtvpcFlowsessionUpdateTargetApi(client),
		CtvpcFlowsessionRemoveSourceApi:              NewCtvpcFlowsessionRemoveSourceApi(client),
		CtvpcFlowsessionAddSourceApi:                 NewCtvpcFlowsessionAddSourceApi(client),
		CtvpcBandwidthBandwidthUtilizationApi:        NewCtvpcBandwidthBandwidthUtilizationApi(client),
		CtvpcBandwidthIngerssBandwidthUtilizationApi: NewCtvpcBandwidthIngerssBandwidthUtilizationApi(client),
		CtvpcBandwidthEgerssBandwidthUtilizationApi:  NewCtvpcBandwidthEgerssBandwidthUtilizationApi(client),
		CtvpcFlowsessionBuyApi:                       NewCtvpcFlowsessionBuyApi(client),
		CtvpcEipBandwidthUtilizationApi:              NewCtvpcEipBandwidthUtilizationApi(client),
		CtvpcEipEgerssBandwidthUtilizationApi:        NewCtvpcEipEgerssBandwidthUtilizationApi(client),
		CtvpcEipIngerssBandwidthUtilizationApi:       NewCtvpcEipIngerssBandwidthUtilizationApi(client),
		CtvpcDhcpoptionsetsShowApi:                   NewCtvpcDhcpoptionsetsShowApi(client),
		CtvpcPrefixlistRuleCreateApi:                 NewCtvpcPrefixlistRuleCreateApi(client),
		CtvpcPrefixlistCreateApi:                     NewCtvpcPrefixlistCreateApi(client),
		CtvpcPrefixlistRuleDeleteApi:                 NewCtvpcPrefixlistRuleDeleteApi(client),
		CtvpcPrefixlistRuleUpdateApi:                 NewCtvpcPrefixlistRuleUpdateApi(client),
		CtvpcPrefixlistQueryApi:                      NewCtvpcPrefixlistQueryApi(client),
		CtvpcPrefixlistCloneApi:                      NewCtvpcPrefixlistCloneApi(client),
		CtvpcPrefixlistDeleteApi:                     NewCtvpcPrefixlistDeleteApi(client),
		CtvpcPrefixlistUpdateApi:                     NewCtvpcPrefixlistUpdateApi(client),
		CtvpcV4PortsAsyncAttachBmApi:                 NewCtvpcV4PortsAsyncAttachBmApi(client),
		CtvpcV4PortsAsyncDetachBmApi:                 NewCtvpcV4PortsAsyncDetachBmApi(client),
		CtvpcGwlbListTargetGroupApi:                  NewCtvpcGwlbListTargetGroupApi(client),
		CtvpcGwlbShowTargetGroupApi:                  NewCtvpcGwlbShowTargetGroupApi(client),
		CtvpcGwlbDeleteTargetGroupApi:                NewCtvpcGwlbDeleteTargetGroupApi(client),
		CtvpcGwlbUpdateTargetGroupApi:                NewCtvpcGwlbUpdateTargetGroupApi(client),
		CtvpcGwlbCreateTargetGroupApi:                NewCtvpcGwlbCreateTargetGroupApi(client),
		CtvpcGwlbListTargetApi:                       NewCtvpcGwlbListTargetApi(client),
		CtvpcGwlbShowTargetApi:                       NewCtvpcGwlbShowTargetApi(client),
		CtvpcGwlbDeleteTargetApi:                     NewCtvpcGwlbDeleteTargetApi(client),
		CtvpcGwlbUpdateTargetApi:                     NewCtvpcGwlbUpdateTargetApi(client),
		CtvpcGwlbCreateTargetApi:                     NewCtvpcGwlbCreateTargetApi(client),
		CtvpcIplistenerListApi:                       NewCtvpcIplistenerListApi(client),
		CtvpcIplistenerShowApi:                       NewCtvpcIplistenerShowApi(client),
		CtvpcIplistenerDeleteApi:                     NewCtvpcIplistenerDeleteApi(client),
		CtvpcIplistenerUpdateApi:                     NewCtvpcIplistenerUpdateApi(client),
		CtvpcIplistenerCreateApi:                     NewCtvpcIplistenerCreateApi(client),
		CtvpcGwlbListApi:                             NewCtvpcGwlbListApi(client),
		CtvpcGwlbShowApi:                             NewCtvpcGwlbShowApi(client),
		CtvpcGwlbEnableDeleteProtectionApi:           NewCtvpcGwlbEnableDeleteProtectionApi(client),
		CtvpcGwlbEnableIpv6Api:                       NewCtvpcGwlbEnableIpv6Api(client),
		CtvpcGwlbDisableIpv6Api:                      NewCtvpcGwlbDisableIpv6Api(client),
		CtvpcGwlbDisableDeleteProtectionApi:          NewCtvpcGwlbDisableDeleteProtectionApi(client),
		CtvpcGwlbDeleteApi:                           NewCtvpcGwlbDeleteApi(client),
		CtvpcGwlbUpdateApi:                           NewCtvpcGwlbUpdateApi(client),
		CtvpcFlowsessionRefundApi:                    NewCtvpcFlowsessionRefundApi(client),
		CtvpcShowSnatApi:                             NewCtvpcShowSnatApi(client),
		CtvpcListSnatsApi:                            NewCtvpcListSnatsApi(client),
		CtvpcGwlbCreateApi:                           NewCtvpcGwlbCreateApi(client),
		CtvpcQueryCtyunServiceApi:                    NewCtvpcQueryCtyunServiceApi(client),
		CtvpcTerminateCycleApi:                       NewCtvpcTerminateCycleApi(client),
		CtvpcChangeToNeedApi:                         NewCtvpcChangeToNeedApi(client),
		CtvpcChangeToCycleApi:                        NewCtvpcChangeToCycleApi(client),
		CtvpcQueryToCyclePriceApi:                    NewCtvpcQueryToCyclePriceApi(client),
		CtvpcQueryToNeedPriceApi:                     NewCtvpcQueryToNeedPriceApi(client),
		CtvpcQueryLabelsByResourceApi:                NewCtvpcQueryLabelsByResourceApi(client),
		CtvpcQueryResourcesByLabelApi:                NewCtvpcQueryResourcesByLabelApi(client),
		CtvpcResourceUnbindLabelApi:                  NewCtvpcResourceUnbindLabelApi(client),
		CtvpcResourceBindLabelApi:                    NewCtvpcResourceBindLabelApi(client),
		CtvpcSgRulePreCheckApi:                       NewCtvpcSgRulePreCheckApi(client),
		CtvpcSubnetDisassociateRouteTableApi:         NewCtvpcSubnetDisassociateRouteTableApi(client),
		CtvpcShowSgRuleApi:                           NewCtvpcShowSgRuleApi(client),
		CtvpcDhcpreplacevpcApi:                       NewCtvpcDhcpreplacevpcApi(client),
		CtvpcDhcpdisassociatevpcApi:                  NewCtvpcDhcpdisassociatevpcApi(client),
		CtvpcDhcpassociatevpcApi:                     NewCtvpcDhcpassociatevpcApi(client),
		CtvpcDhcplistunbindvpcApi:                    NewCtvpcDhcplistunbindvpcApi(client),
		CtvpcDhcplistvpcApi:                          NewCtvpcDhcplistvpcApi(client),
		CtvpcDhcpoptionsetsqueryApi:                  NewCtvpcDhcpoptionsetsqueryApi(client),
		CtvpcDhcpoptionsetsdeleteApi:                 NewCtvpcDhcpoptionsetsdeleteApi(client),
		CtvpcUpdatedhcpoptionsetsApi:                 NewCtvpcUpdatedhcpoptionsetsApi(client),
		CtvpcDhcpoptionsetscreateApi:                 NewCtvpcDhcpoptionsetscreateApi(client),
		CtvpcTunnelCheckApi:                          NewCtvpcTunnelCheckApi(client),
		CtvpcGwQueryApi:                              NewCtvpcGwQueryApi(client),
		CtvpcL2gwConnectionQueryApi:                  NewCtvpcL2gwConnectionQueryApi(client),
		CtvpcL2gwConnectionUpdateApi:                 NewCtvpcL2gwConnectionUpdateApi(client),
		CtvpcL2gwConnectionDeleteApi:                 NewCtvpcL2gwConnectionDeleteApi(client),
		CtvpcL2gwConnectionCreateApi:                 NewCtvpcL2gwConnectionCreateApi(client),
		CtvpcL2gwQueryApi:                            NewCtvpcL2gwQueryApi(client),
		CtvpcL2gwUpdateApi:                           NewCtvpcL2gwUpdateApi(client),
		CtvpcL2gwDeleteApi:                           NewCtvpcL2gwDeleteApi(client),
		CtvpcL2gwCreateApi:                           NewCtvpcL2gwCreateApi(client),
		CtvpcAcceptEndpointApplyApi:                  NewCtvpcAcceptEndpointApplyApi(client),
		CtvpcRefuseEndpointApplyApi:                  NewCtvpcRefuseEndpointApplyApi(client),
		CtvpcModifyEndpointServiceApi:                NewCtvpcModifyEndpointServiceApi(client),
		CtvpcModifyNatSpecApi:                        NewCtvpcModifyNatSpecApi(client),
		CtvpcCheckPtrRecordApi:                       NewCtvpcCheckPtrRecordApi(client),
		CtvpcCheckPtrApi:                             NewCtvpcCheckPtrApi(client),
		CtvpcCheckAAAAApi:                            NewCtvpcCheckAAAAApi(client),
		CtvpcQueryCreateEndpointPriceApi:             NewCtvpcQueryCreateEndpointPriceApi(client),
		CtvpcGetSgAssociateVmsApi:                    NewCtvpcGetSgAssociateVmsApi(client),
		CtvpcListZoneBindLabelsApi:                   NewCtvpcListZoneBindLabelsApi(client),
		CtvpcZoneUnbindLabelsApi:                     NewCtvpcZoneUnbindLabelsApi(client),
		CtvpcZoneBindLabelsApi:                       NewCtvpcZoneBindLabelsApi(client),
		CtvpcSetZoneProxyPatternApi:                  NewCtvpcSetZoneProxyPatternApi(client),
		CtvpcGetZoneQuotaApi:                         NewCtvpcGetZoneQuotaApi(client),
		CtvpcGetZoneRecordQuotaApi:                   NewCtvpcGetZoneRecordQuotaApi(client),
		CtvpcListSharedZoneRecordsApi:                NewCtvpcListSharedZoneRecordsApi(client),
		CtvpcGetZoneBindVpcsApi:                      NewCtvpcGetZoneBindVpcsApi(client),
		CtvpcQueryAllZonesAndVpcsApi:                 NewCtvpcQueryAllZonesAndVpcsApi(client),
		CtvpcGetNameserverApi:                        NewCtvpcGetNameserverApi(client),
		CtvpcCheckZoneNameApi:                        NewCtvpcCheckZoneNameApi(client),
		CtvpcCheckTxtApi:                             NewCtvpcCheckTxtApi(client),
		CtvpcCheckMxApi:                              NewCtvpcCheckMxApi(client),
		CtvpcCheckCnameApi:                           NewCtvpcCheckCnameApi(client),
		CtvpcGetVpcBindedZonesApi:                    NewCtvpcGetVpcBindedZonesApi(client),
		CtvpcEnablePrivateZoneRecordApi:              NewCtvpcEnablePrivateZoneRecordApi(client),
		CtvpcDisablePrivateZoneRecordApi:             NewCtvpcDisablePrivateZoneRecordApi(client),
		CtvpcModifyPrivateZoneRecordDescApi:          NewCtvpcModifyPrivateZoneRecordDescApi(client),
		CtvpcNatQueryRenewPriceApi:                   NewCtvpcNatQueryRenewPriceApi(client),
		CtvpcNatQueryModifyPriceApi:                  NewCtvpcNatQueryModifyPriceApi(client),
		CtvpcNatQueryCreatePriceApi:                  NewCtvpcNatQueryCreatePriceApi(client),
		CtvpcIpv6BandwidthRenewApi:                   NewCtvpcIpv6BandwidthRenewApi(client),
		CtvpcIpv6BandwidthQueryRenewPriceApi:         NewCtvpcIpv6BandwidthQueryRenewPriceApi(client),
		CtvpcIpv6BandwidthQueryModifyPriceApi:        NewCtvpcIpv6BandwidthQueryModifyPriceApi(client),
		CtvpcIpv6BandwidthQueryCreatePriceApi:        NewCtvpcIpv6BandwidthQueryCreatePriceApi(client),
		CtvpcEipQueryRenewPriceApi:                   NewCtvpcEipQueryRenewPriceApi(client),
		CtvpcEipQueryModifyPriceApi:                  NewCtvpcEipQueryModifyPriceApi(client),
		CtvpcEipQueryCreatePriceApi:                  NewCtvpcEipQueryCreatePriceApi(client),
		CtvpcBandwidthRenewApi:                       NewCtvpcBandwidthRenewApi(client),
		CtvpcBandwidthQueryRenewPriceApi:             NewCtvpcBandwidthQueryRenewPriceApi(client),
		CtvpcBandwidthQueryModifyPriceApi:            NewCtvpcBandwidthQueryModifyPriceApi(client),
		CtvpcBandwidthQueryCreatePriceApi:            NewCtvpcBandwidthQueryCreatePriceApi(client),
		CtvpcShowFlowSessionApi:                      NewCtvpcShowFlowSessionApi(client),
		CtvpcListFlowSessionsApi:                     NewCtvpcListFlowSessionsApi(client),
		CtvpcUpdateFlowSessionApi:                    NewCtvpcUpdateFlowSessionApi(client),
		CtvpcStopFlowSessionApi:                      NewCtvpcStopFlowSessionApi(client),
		CtvpcStartFlowSessionApi:                     NewCtvpcStartFlowSessionApi(client),
		CtvpcDeleteFlowSessionApi:                    NewCtvpcDeleteFlowSessionApi(client),
		CtvpcCreateFlowSessionApi:                    NewCtvpcCreateFlowSessionApi(client),
		CtvpcChangeFilteRulePriorityApi:              NewCtvpcChangeFilteRulePriorityApi(client),
		CtvpcListMirrorFlowFilterRuleApi:             NewCtvpcListMirrorFlowFilterRuleApi(client),
		CtvpcShowMirrorFlowFilterApi:                 NewCtvpcShowMirrorFlowFilterApi(client),
		CtvpcListMirrorFlowFilterApi:                 NewCtvpcListMirrorFlowFilterApi(client),
		CtvpcUpdateMirrorFlowFilterRuleApi:           NewCtvpcUpdateMirrorFlowFilterRuleApi(client),
		CtvpcUpdateMirrorFlowFilterApi:               NewCtvpcUpdateMirrorFlowFilterApi(client),
		CtvpcDeleteMirrorFlowFilterRuleApi:           NewCtvpcDeleteMirrorFlowFilterRuleApi(client),
		CtvpcDeleteMirrorFlowFilterApi:               NewCtvpcDeleteMirrorFlowFilterApi(client),
		CtvpcCreateMirrorFlowFilterApi:               NewCtvpcCreateMirrorFlowFilterApi(client),
		CtvpcCreateOutFilterRuleApi:                  NewCtvpcCreateOutFilterRuleApi(client),
		CtvpcCreateInFilterRuleApi:                   NewCtvpcCreateInFilterRuleApi(client),
		CtvpcAttachPortBmApi:                         NewCtvpcAttachPortBmApi(client),
		CtvpcNewPrivateZoneRecordListApi:             NewCtvpcNewPrivateZoneRecordListApi(client),
		CtvpcNewPrivateZoneListApi:                   NewCtvpcNewPrivateZoneListApi(client),
		CtvpcNewACLListApi:                           NewCtvpcNewACLListApi(client),
		CtvpcNewEndpointServiceWhiteListApi:          NewCtvpcNewEndpointServiceWhiteListApi(client),
		CtvpcNewEndpointServicesListApi:              NewCtvpcNewEndpointServicesListApi(client),
		CtvpcNewEndpointsListApi:                     NewCtvpcNewEndpointsListApi(client),
		CtvpcNewPortsListApi:                         NewCtvpcNewPortsListApi(client),
		CtvpcNewIPv6ListApi:                          NewCtvpcNewIPv6ListApi(client),
		CtvpcNewRouteRulesListApi:                    NewCtvpcNewRouteRulesListApi(client),
		CtvpcNewRouteTableListApi:                    NewCtvpcNewRouteTableListApi(client),
		CtvpcNewQuerySecurityGroupsApi:               NewCtvpcNewQuerySecurityGroupsApi(client),
		CtvpcNewSubnetListApi:                        NewCtvpcNewSubnetListApi(client),
		CtvpcNewVpcListApi:                           NewCtvpcNewVpcListApi(client),
		CtvpcNewIPv6BandwidthListApi:                 NewCtvpcNewIPv6BandwidthListApi(client),
		CtvpcNewBandwidthListApi:                     NewCtvpcNewBandwidthListApi(client),
		CtvpcNewEipListApi:                           NewCtvpcNewEipListApi(client),
		CtvpcNewQueryEIPRealtimeMonitorApi:           NewCtvpcNewQueryEIPRealtimeMonitorApi(client),
		CtvpcNewQueryEIPHistoryMonitorApi:            NewCtvpcNewQueryEIPHistoryMonitorApi(client),
		CtvpcCreateEipWithIpAddressApi:               NewCtvpcCreateEipWithIpAddressApi(client),
		CtvpcGetEipFilingStatusApi:                   NewCtvpcGetEipFilingStatusApi(client),
		CtvpcSubnetEnableIPv6Api:                     NewCtvpcSubnetEnableIPv6Api(client),
		CtvpcSgBatchDetachPortsApi:                   NewCtvpcSgBatchDetachPortsApi(client),
		CtvpcSgBatchAttachPortsApi:                   NewCtvpcSgBatchAttachPortsApi(client),
		CtvpcDeleteRouteRuleApi:                      NewCtvpcDeleteRouteRuleApi(client),
		CtvpcModifyRouteRuleApi:                      NewCtvpcModifyRouteRuleApi(client),
		CtvpcCreateRouteRuleApi:                      NewCtvpcCreateRouteRuleApi(client),
		CtvpcCreateSubnetACLApi:                      NewCtvpcCreateSubnetACLApi(client),
		CtvpcListVpcPeerRequestsApi:                  NewCtvpcListVpcPeerRequestsApi(client),
		CtvpcAgreeVpcPeerRequestApi:                  NewCtvpcAgreeVpcPeerRequestApi(client),
		CtvpcRejectVpcPeerRequestApi:                 NewCtvpcRejectVpcPeerRequestApi(client),
		CtvpcListIPv4GwApi:                           NewCtvpcListIPv4GwApi(client),
		CtvpcShowIPv4GwApi:                           NewCtvpcShowIPv4GwApi(client),
		CtvpcIpv4GwUnbindRouteTableApi:               NewCtvpcIpv4GwUnbindRouteTableApi(client),
		CtvpcIpv4GwBindRouteTableApi:                 NewCtvpcIpv4GwBindRouteTableApi(client),
		CtvpcListSubnetUsedIPsApi:                    NewCtvpcListSubnetUsedIPsApi(client),
		CtvpcCreateGatewayRouteTableApi:              NewCtvpcCreateGatewayRouteTableApi(client),
		CtvpcPortReplaceSubnetApi:                    NewCtvpcPortReplaceSubnetApi(client),
		CtvpcPortReplaceVPCApi:                       NewCtvpcPortReplaceVPCApi(client),
		CtvpcShowEndpointServiceConnectionsApi:       NewCtvpcShowEndpointServiceConnectionsApi(client),
		CtvpcUpdateEndpointServiceConnectionsApi:     NewCtvpcUpdateEndpointServiceConnectionsApi(client),
		CtvpcListEndpointServiceWhitelistApi:         NewCtvpcListEndpointServiceWhitelistApi(client),
		CtvpcDeleteEndpointServiceWhitelistApi:       NewCtvpcDeleteEndpointServiceWhitelistApi(client),
		CtvpcCreateEndpointServiceWhitelistApi:       NewCtvpcCreateEndpointServiceWhitelistApi(client),
		CtvpcListEndpointServiceApi:                  NewCtvpcListEndpointServiceApi(client),
		CtvpcDeleteEndpointServiceApi:                NewCtvpcDeleteEndpointServiceApi(client),
		CtvpcCreateEndpointServiceApi:                NewCtvpcCreateEndpointServiceApi(client),
		CtvpcDeleteEndpointWhitelistApi:              NewCtvpcDeleteEndpointWhitelistApi(client),
		CtvpcShowEndpointWhitelistApi:                NewCtvpcShowEndpointWhitelistApi(client),
		CtvpcAddEndpointWhitelistApi:                 NewCtvpcAddEndpointWhitelistApi(client),
		CtvpcDeleteEndpointApi:                       NewCtvpcDeleteEndpointApi(client),
		CtvpcShowEndpointApi:                         NewCtvpcShowEndpointApi(client),
		CtvpcListEndpointApi:                         NewCtvpcListEndpointApi(client),
		CtvpcUpdateEndpointApi:                       NewCtvpcUpdateEndpointApi(client),
		CtvpcCreateEndpointApi:                       NewCtvpcCreateEndpointApi(client),
		CtvpcListEndpointServiceTransitIPApi:         NewCtvpcListEndpointServiceTransitIPApi(client),
		CtvpcDeleteEndpointServiceTransitIPApi:       NewCtvpcDeleteEndpointServiceTransitIPApi(client),
		CtvpcCreateEndpointServiceTransitIPApi:       NewCtvpcCreateEndpointServiceTransitIPApi(client),
		CtvpcDeleteEndpointServiceReverseRuleApi:     NewCtvpcDeleteEndpointServiceReverseRuleApi(client),
		CtvpcListEndpointServiceReverseRuleApi:       NewCtvpcListEndpointServiceReverseRuleApi(client),
		CtvpcCreateEndpointServiceReverseRuleApi:     NewCtvpcCreateEndpointServiceReverseRuleApi(client),
		CtvpcDeleteEndpointServiceRuleApi:            NewCtvpcDeleteEndpointServiceRuleApi(client),
		CtvpcCreateEndpointServiceRuleApi:            NewCtvpcCreateEndpointServiceRuleApi(client),
		CtvpcBatchDeleteZoneRecordsApi:               NewCtvpcBatchDeleteZoneRecordsApi(client),
		CtvpcChangeEipNameApi:                        NewCtvpcChangeEipNameApi(client),
		CtvpcShowFlowPackageApi:                      NewCtvpcShowFlowPackageApi(client),
		CtvpcListFlowPackageApi:                      NewCtvpcListFlowPackageApi(client),
		CtvpcRefundFlowPackageApi:                    NewCtvpcRefundFlowPackageApi(client),
		CtvpcBuyFlowPackageApi:                       NewCtvpcBuyFlowPackageApi(client),
		CtvpcQueryFlowPackagePriceApi:                NewCtvpcQueryFlowPackagePriceApi(client),
		CtvpcModifyIPv6BandwidthSpecApi:              NewCtvpcModifyIPv6BandwidthSpecApi(client),
		CtvpcDeleteIPv6BandwidthApi:                  NewCtvpcDeleteIPv6BandwidthApi(client),
		CtvpcCreateIPv6BandwidthApi:                  NewCtvpcCreateIPv6BandwidthApi(client),
		CtvpcUpdateIPv6BandwidthAttributeApi:         NewCtvpcUpdateIPv6BandwidthAttributeApi(client),
		CtvpcListIPv6BandwidthApi:                    NewCtvpcListIPv6BandwidthApi(client),
		CtvpcShowIPv6BandwidthApi:                    NewCtvpcShowIPv6BandwidthApi(client),
		CtvpcRemoveIPv6FromIPv6BandwidthApi:          NewCtvpcRemoveIPv6FromIPv6BandwidthApi(client),
		CtvpcAddIPv6ToIPv6BandwidthApi:               NewCtvpcAddIPv6ToIPv6BandwidthApi(client),
		CtvpcQueryEipRealtimeMonitorApi:              NewCtvpcQueryEipRealtimeMonitorApi(client),
		CtvpcQueryEipHistoryMonitorApi:               NewCtvpcQueryEipHistoryMonitorApi(client),
		CtvpcBatchCheckEipAddressApi:                 NewCtvpcBatchCheckEipAddressApi(client),
		CtvpcCheckEipAddressApi:                      NewCtvpcCheckEipAddressApi(client),
		CtvpcBatchJoinSecurityGroupApi:               NewCtvpcBatchJoinSecurityGroupApi(client),
		CtvpcUpdateSecurityGroupAttributeApi:         NewCtvpcUpdateSecurityGroupAttributeApi(client),
		CtvpcShowEipApi:                              NewCtvpcShowEipApi(client),
		CtvpcAttachEipToPortApi:                      NewCtvpcAttachEipToPortApi(client),
		CtvpcUpdateIPv6StatusForVpcApi:               NewCtvpcUpdateIPv6StatusForVpcApi(client),
		CtvpcDeleteHavipApi:                          NewCtvpcDeleteHavipApi(client),
		CtvpcShowHavipApi:                            NewCtvpcShowHavipApi(client),
		CtvpcUnassignSecondaryPrivateIPsFromPortApi:  NewCtvpcUnassignSecondaryPrivateIPsFromPortApi(client),
		CtvpcDetachPortApi:                           NewCtvpcDetachPortApi(client),
		CtvpcAttachPortApi:                           NewCtvpcAttachPortApi(client),
		CtvpcAssignSecondaryPrivateIPsToPortApi:      NewCtvpcAssignSecondaryPrivateIPsToPortApi(client),
		CtvpcCheckPortStatusApi:                      NewCtvpcCheckPortStatusApi(client),
		CtvpcVpcListPortApi:                          NewCtvpcVpcListPortApi(client),
		CtvpcBatchCheckPortStatusApi:                 NewCtvpcBatchCheckPortStatusApi(client),
		CtvpcBatchUnassignIPv6FromPortApi:            NewCtvpcBatchUnassignIPv6FromPortApi(client),
		CtvpcBatchAssignIPv6ToPortApi:                NewCtvpcBatchAssignIPv6ToPortApi(client),
		CtvpcUnassignIPv6FromPortApi:                 NewCtvpcUnassignIPv6FromPortApi(client),
		CtvpcAssignIPv6ToPortApi:                     NewCtvpcAssignIPv6ToPortApi(client),
		CtvpcDeletePortApi:                           NewCtvpcDeletePortApi(client),
		CtvpcCreatePortApi:                           NewCtvpcCreatePortApi(client),
		CtvpcUpdatePortApi:                           NewCtvpcUpdatePortApi(client),
		CtvpcShowDnatEntryApi:                        NewCtvpcShowDnatEntryApi(client),
		CtvpcListDnatEntriesApi:                      NewCtvpcListDnatEntriesApi(client),
		CtvpcRenewNatGatewayApi:                      NewCtvpcRenewNatGatewayApi(client),
		CtvpcShowNatGatewayApi:                       NewCtvpcShowNatGatewayApi(client),
		CtvpcListNatGatewaysApi:                      NewCtvpcListNatGatewaysApi(client),
		CtvpcDeleteSnatEntryApi:                      NewCtvpcDeleteSnatEntryApi(client),
		CtvpcDeleteNatGatewayApi:                     NewCtvpcDeleteNatGatewayApi(client),
		CtvpcDeleteDnatEntryApi:                      NewCtvpcDeleteDnatEntryApi(client),
		CtvpcCreateSnatEntryApi:                      NewCtvpcCreateSnatEntryApi(client),
		CtvpcCreateNatGatewayApi:                     NewCtvpcCreateNatGatewayApi(client),
		CtvpcCreateDnatEntryApi:                      NewCtvpcCreateDnatEntryApi(client),
		CtvpcUpdateSnatEntryAttributeApi:             NewCtvpcUpdateSnatEntryAttributeApi(client),
		CtvpcUpdateNatGatewayAttributeApi:            NewCtvpcUpdateNatGatewayAttributeApi(client),
		CtvpcUpdateDnatEntryAttributeApi:             NewCtvpcUpdateDnatEntryAttributeApi(client),
		CtvpcDisassociateEipsFromSnatApi:             NewCtvpcDisassociateEipsFromSnatApi(client),
		CtvpcAssociateEipsToSnatApi:                  NewCtvpcAssociateEipsToSnatApi(client),
		CtvpcDeleteAclRuleApi:                        NewCtvpcDeleteAclRuleApi(client),
		CtvpcDeleteAclApi:                            NewCtvpcDeleteAclApi(client),
		CtvpcCreateAclRuleApi:                        NewCtvpcCreateAclRuleApi(client),
		CtvpcCreateAclApi:                            NewCtvpcCreateAclApi(client),
		CtvpcUpdateAclRuleAttributeApi:               NewCtvpcUpdateAclRuleAttributeApi(client),
		CtvpcUpdateAclAttributeApi:                   NewCtvpcUpdateAclAttributeApi(client),
		CtvpcShowAclApi:                              NewCtvpcShowAclApi(client),
		CtvpcListAclApi:                              NewCtvpcListAclApi(client),
		CtvpcListAclRuleApi:                          NewCtvpcListAclRuleApi(client),
		CtvpcShowIPv6GatewayApi:                      NewCtvpcShowIPv6GatewayApi(client),
		CtvpcListIPv6GatewayApi:                      NewCtvpcListIPv6GatewayApi(client),
		CtvpcDeleteIPv6GatewayApi:                    NewCtvpcDeleteIPv6GatewayApi(client),
		CtvpcCreateIPv6GatewayApi:                    NewCtvpcCreateIPv6GatewayApi(client),
		CtvpcShowPrivateZoneRecordApi:                NewCtvpcShowPrivateZoneRecordApi(client),
		CtvpcListPrivateZoneRecordApi:                NewCtvpcListPrivateZoneRecordApi(client),
		CtvpcDeletePrivateZoneRecordApi:              NewCtvpcDeletePrivateZoneRecordApi(client),
		CtvpcUpdatePrivateZoneRecordAttributeApi:     NewCtvpcUpdatePrivateZoneRecordAttributeApi(client),
		CtvpcCreatePrivateZoneRecordApi:              NewCtvpcCreatePrivateZoneRecordApi(client),
		CtvpcShowPrivateZoneApi:                      NewCtvpcShowPrivateZoneApi(client),
		CtvpcListPrivateZoneApi:                      NewCtvpcListPrivateZoneApi(client),
		CtvpcDisassociatePrivateZoneFromVpcApi:       NewCtvpcDisassociatePrivateZoneFromVpcApi(client),
		CtvpcAssociatePrivateZoneToVpcApi:            NewCtvpcAssociatePrivateZoneToVpcApi(client),
		CtvpcUpdatePrivateZoneAttributeApi:           NewCtvpcUpdatePrivateZoneAttributeApi(client),
		CtvpcDeletePrivateZoneApi:                    NewCtvpcDeletePrivateZoneApi(client),
		CtvpcCreatePrivateZoneApi:                    NewCtvpcCreatePrivateZoneApi(client),
		CtvpcShowRouteTableApi:                       NewCtvpcShowRouteTableApi(client),
		CtvpcListRouteTableRulesApi:                  NewCtvpcListRouteTableRulesApi(client),
		CtvpcListRouteTableApi:                       NewCtvpcListRouteTableApi(client),
		CtvpcDeleteRouteTableRulesApi:                NewCtvpcDeleteRouteTableRulesApi(client),
		CtvpcDeleteRouteTableApi:                     NewCtvpcDeleteRouteTableApi(client),
		CtvpcCreateRouteTableRulesApi:                NewCtvpcCreateRouteTableRulesApi(client),
		CtvpcDisassociateEipApi:                      NewCtvpcDisassociateEipApi(client),
		CtvpcCreateRouteTableApi:                     NewCtvpcCreateRouteTableApi(client),
		CtvpcUpdateRouteTableRulesAttributeApi:       NewCtvpcUpdateRouteTableRulesAttributeApi(client),
		CtvpcUpdateRouteTableAttributeApi:            NewCtvpcUpdateRouteTableAttributeApi(client),
		CtvpcShowVpcPeerConnectionApi:                NewCtvpcShowVpcPeerConnectionApi(client),
		CtvpcModifyEipSpecApi:                        NewCtvpcModifyEipSpecApi(client),
		CtvpcListVpcPeerConnectionApi:                NewCtvpcListVpcPeerConnectionApi(client),
		CtvpcUpdateVpcPeerConnectionAttributeApi:     NewCtvpcUpdateVpcPeerConnectionAttributeApi(client),
		CtvpcShowIPv6Api:                             NewCtvpcShowIPv6Api(client),
		CtvpcListIPv6Api:                             NewCtvpcListIPv6Api(client),
		CtvpcDeleteVpcPeerConnectionApi:              NewCtvpcDeleteVpcPeerConnectionApi(client),
		CtvpcAssociateEipApi:                         NewCtvpcAssociateEipApi(client),
		CtvpcCreateVpcPeerConnectionApi:              NewCtvpcCreateVpcPeerConnectionApi(client),
		CtvpcRenewEipApi:                             NewCtvpcRenewEipApi(client),
		CtvpcDisassociateSubnetAclApi:                NewCtvpcDisassociateSubnetAclApi(client),
		CtvpcReplaceSubnetRouteTableApi:              NewCtvpcReplaceSubnetRouteTableApi(client),
		CtvpcReplaceSubnetAclApi:                     NewCtvpcReplaceSubnetAclApi(client),
		CtvpcCreateEipApi:                            NewCtvpcCreateEipApi(client),
		CtvpcDeleteEipApi:                            NewCtvpcDeleteEipApi(client),
		CtvpcListEipApi:                              NewCtvpcListEipApi(client),
		CtvpcVpcDeleteSubnetApi:                      NewCtvpcVpcDeleteSubnetApi(client),
		CtvpcUpDateSubnetApi:                         NewCtvpcUpDateSubnetApi(client),
		CtvpcDeleteVpcApi:                            NewCtvpcDeleteVpcApi(client),
		CtvpcUpdateSubnetIPv6StatusApi:               NewCtvpcUpdateSubnetIPv6StatusApi(client),
		CtvpcUpdateVpcAttributeApi:                   NewCtvpcUpdateVpcAttributeApi(client),
		CtvpcDisassociateSecondaryCidrsFromVpcApi:    NewCtvpcDisassociateSecondaryCidrsFromVpcApi(client),
		CtvpcAssociateSecondaryCidrsToVpcApi:         NewCtvpcAssociateSecondaryCidrsToVpcApi(client),
		CtvpcDisassociateIPv6FromBandwidthApi:        NewCtvpcDisassociateIPv6FromBandwidthApi(client),
		CtvpcAssociateIPv6ToBandwidthApi:             NewCtvpcAssociateIPv6ToBandwidthApi(client),
		CtvpcDisassociateEipFromBandwidthApi:         NewCtvpcDisassociateEipFromBandwidthApi(client),
		CtvpcAssociateEipToBandwidthApi:              NewCtvpcAssociateEipToBandwidthApi(client),
		CtvpcListBandwidthApi:                        NewCtvpcListBandwidthApi(client),
		CtvpcShowBandwidthApi:                        NewCtvpcShowBandwidthApi(client),
		CtvpcUpdateBandwidthAttributeApi:             NewCtvpcUpdateBandwidthAttributeApi(client),
		CtvpcModifyBandwidthSpecApi:                  NewCtvpcModifyBandwidthSpecApi(client),
		CtvpcDeleteBandwidthApi:                      NewCtvpcDeleteBandwidthApi(client),
		CtvpcCreateBandwidthApi:                      NewCtvpcCreateBandwidthApi(client),
		CtvpcShowPortApi:                             NewCtvpcShowPortApi(client),
		CtvpcUnbindHavipApi:                          NewCtvpcUnbindHavipApi(client),
		CtvpcListHavipApi:                            NewCtvpcListHavipApi(client),
		CtvpcBindHavipApi:                            NewCtvpcBindHavipApi(client),
		CtvpcCreateHavipApi:                          NewCtvpcCreateHavipApi(client),
		CtvpcRevokeSgEngressRuleApi:                  NewCtvpcRevokeSgEngressRuleApi(client),
		CtvpcRevokeSgIngressRuleApi:                  NewCtvpcRevokeSgIngressRuleApi(client),
		CtvpcModifySgEngressRuleApi:                  NewCtvpcModifySgEngressRuleApi(client),
		CtvpcModifySgIngressRuleApi:                  NewCtvpcModifySgIngressRuleApi(client),
		CtvpcCreateSgEgressRuleApi:                   NewCtvpcCreateSgEgressRuleApi(client),
		CtvpcCreateSgIngressRuleApi:                  NewCtvpcCreateSgIngressRuleApi(client),
		CtvpcVpcDeleteSecurityGroupApi:               NewCtvpcVpcDeleteSecurityGroupApi(client),
		CtvpcVpcCreateSecurityGroupApi:               NewCtvpcVpcCreateSecurityGroupApi(client),
		CtvpcLeaveSecurityGroupApi:                   NewCtvpcLeaveSecurityGroupApi(client),
		CtvpcJoinSecurityGroupApi:                    NewCtvpcJoinSecurityGroupApi(client),
		CtvpcShowSecurityGroupApi:                    NewCtvpcShowSecurityGroupApi(client),
		CtvpcListSecurityGroupsApi:                   NewCtvpcListSecurityGroupsApi(client),
		CtvpcListSubnetApi:                           NewCtvpcListSubnetApi(client),
		CtvpcShowSubnetApi:                           NewCtvpcShowSubnetApi(client),
		CtvpcListVpcApi:                              NewCtvpcListVpcApi(client),
		CtvpcShowVpcApi:                              NewCtvpcShowVpcApi(client),
		CtvpcVpcCreateSubnetApi:                      NewCtvpcVpcCreateSubnetApi(client),
		CtvpcCreateVpc1Api:                           NewCtvpcCreateVpc1Api(client),
	}
}
