package ctiam

import (
	"github.com/ctyun-it/terraform-provider-ctyun/internal/core/core"
)

const EndpointName = "ctiam"

type Apis struct {
	CtiamCreateUserApi                   *CtiamCreateUserApi
	CtiamUpdateUserApi                   *CtiamUpdateUserApi
	CtiamGetEpPageListApi                *CtiamGetEpPageListApi
	CtiamCreateGroupApi                  *CtiamCreateGroupApi
	CtiamUserToGroupApi                  *CtiamUserToGroupApi
	CtiamGetGroupByGroupIdApi            *CtiamGetGroupByGroupIdApi
	CtiamInvalidGroupApi                 *CtiamInvalidGroupApi
	CtiamGetIdentityProviderInfoApi      *CtiamGetIdentityProviderInfoApi
	CtiamGetGroupsApi                    *CtiamGetGroupsApi
	CtiamUpdateGroupApi                  *CtiamUpdateGroupApi
	CtiamUserOutGroupApi                 *CtiamUserOutGroupApi
	CtiamGetGroupUserApi                 *CtiamGetGroupUserApi
	CtiamAttachGroupPolicyApi            *CtiamAttachGroupPolicyApi
	CtiamInvalidGroupPolicyApi           *CtiamInvalidGroupPolicyApi
	CtiamListGroupPolicyApi              *CtiamListGroupPolicyApi
	CtiamListUserPolicyApi               *CtiamListUserPolicyApi
	CtiamQueryApi                        *CtiamQueryApi
	CtiamAttachDelegateRolePolicyApi     *CtiamAttachDelegateRolePolicyApi
	CtiamInvalidDelegateRolePolicyApi    *CtiamInvalidDelegateRolePolicyApi
	CtiamCreatePolicyApi                 *CtiamCreatePolicyApi
	CtiamUpdatePolicyApi                 *CtiamUpdatePolicyApi
	CtiamDeletePolicyApi                 *CtiamDeletePolicyApi
	CtiamQueryPolicyApi                  *CtiamQueryPolicyApi
	CtiamGetPolicyByIdApi                *CtiamGetPolicyByIdApi
	CtiamCreateAkApi                     *CtiamCreateAkApi
	CtiamQueryAkApi                      *CtiamQueryAkApi
	CtiamQueryQuotaByTypeApi             *CtiamQueryQuotaByTypeApi
	CtiamQueryRegionByAccountIdApi       *CtiamQueryRegionByAccountIdApi
	CtiamCreateDelegateRoleApi           *CtiamCreateDelegateRoleApi
	CtiamQueryDelegateRolesApi           *CtiamQueryDelegateRolesApi
	CtiamGetDelegateRoleApi              *CtiamGetDelegateRoleApi
	CtiamUpdateIdPApi                    *CtiamUpdateIdPApi
	CtiamCreateIdPApi                    *CtiamCreateIdPApi
	CtiamDeleteIdPApi                    *CtiamDeleteIdPApi
	CtiamQueryIdPsApi                    *CtiamQueryIdPsApi
	CtiamGetIdPDetailsApi                *CtiamGetIdPDetailsApi
	CtiamDeleteDelegateRoleApi           *CtiamDeleteDelegateRoleApi
	CtiamCreateEnterpriseProjectApi      *CtiamCreateEnterpriseProjectApi
	CtiamUpdateEnterpriseProjectApi      *CtiamUpdateEnterpriseProjectApi
	CtiamGetEnterpriseProjectByIdApi     *CtiamGetEnterpriseProjectByIdApi
	CtiamSasEnterpriseProjectApi         *CtiamSasEnterpriseProjectApi
	CtiamGetEpGroupPageListApi           *CtiamGetEpGroupPageListApi
	CtiamAssignmentEpToGroupApi          *CtiamAssignmentEpToGroupApi
	CtiamGetEpPloyApi                    *CtiamGetEpPloyApi
	CtiamRemoveEpFromGroupApi            *CtiamRemoveEpFromGroupApi
	CtiamSetEpGroupPloyApi               *CtiamSetEpGroupPloyApi
	CtiamGetResourcePageListApi          *CtiamGetResourcePageListApi
	CtiamChangeResourceEpApi             *CtiamChangeResourceEpApi
	CtiamDeleteAkApi                     *CtiamDeleteAkApi
	CtiamPauseAkApi                      *CtiamPauseAkApi
	CtiamOnlineAkApi                     *CtiamOnlineAkApi
	CtiamAkToRecycleBinApi               *CtiamAkToRecycleBinApi
	CtiamRecoverAkApi                    *CtiamRecoverAkApi
	CtiamQueryRecycleBinAkApi            *CtiamQueryRecycleBinAkApi
	CtiamSendVerifyCodeToRootApi         *CtiamSendVerifyCodeToRootApi
	CtiamResetPwdByRootCodeApi           *CtiamResetPwdByRootCodeApi
	CtiamTotpEffectiveChangeApi          *CtiamTotpEffectiveChangeApi
	CtiamTotpUriApi                      *CtiamTotpUriApi
	CtiamTotpEffectiveApi                *CtiamTotpEffectiveApi
	CtiamMfaValidationApi                *CtiamMfaValidationApi
	CtiamCancelOrgAttachPolicyApi        *CtiamCancelOrgAttachPolicyApi
	CtiamAttachEpPermissionApi           *CtiamAttachEpPermissionApi
	CtiamQueryUsersApi                   *CtiamQueryUsersApi
	CtiamGetTokenApi                     *CtiamGetTokenApi
	CtiamQueryDelegateListApi            *CtiamQueryDelegateListApi
	CtiamQueryCtapiServiceByConditionApi *CtiamQueryCtapiServiceByConditionApi
	CtiamQueryAllAuthorityByServiceIdApi *CtiamQueryAllAuthorityByServiceIdApi
	CtiamAttachGroupToUserApi            *CtiamAttachGroupToUserApi
	CtiamRemoveGroupFromUserApi          *CtiamRemoveGroupFromUserApi
	CtiamAttachPolicyToUserApi           *CtiamAttachPolicyToUserApi
	CtiamQueryPrivilegeByIdApi           *CtiamQueryPrivilegeByIdApi
	CtiamQueryCloudCtapiServiceApi       *CtiamQueryCloudCtapiServiceApi
	CtiamListUserInheritGroupPolicyApi   *CtiamListUserInheritGroupPolicyApi
	CtiamListUserOneselfPolicyApi        *CtiamListUserOneselfPolicyApi
	CtiamQuerySensitiveEventApi          *CtiamQuerySensitiveEventApi
	CtiamUpdatePhoneAndEmailApi          *CtiamUpdatePhoneAndEmailApi
	CtiamSwitchDelegateApi               *CtiamSwitchDelegateApi
	CtiamInvalidUserApi                  *CtiamInvalidUserApi
	CtiamGetUserApi                      *CtiamGetUserApi
	CtiamRestPasswordApi                 *CtiamRestPasswordApi
	CtiamCheckCreateUserInfoApi          *CtiamCheckCreateUserInfoApi
	CtiamCheckUpdateUserInfoApi          *CtiamCheckUpdateUserInfoApi
	CtiamSetAccessControlApi             *CtiamSetAccessControlApi
	CtiamQueryAccessControlApi           *CtiamQueryAccessControlApi
	CtiamSettingPasswordApi              *CtiamSettingPasswordApi
	CtiamSetLoginAuthenApi               *CtiamSetLoginAuthenApi
	CtiamQueryLoginAuthenApi             *CtiamQueryLoginAuthenApi
	CtiamSecurityOpVerifyApi             *CtiamSecurityOpVerifyApi
	CtiamQueryOpVerifyApi                *CtiamQueryOpVerifyApi
	CtiamSetEpGroupPloyIncreaseApi       *CtiamSetEpGroupPloyIncreaseApi
	CtiamInvalidEpGroupPloyDecreaseApi   *CtiamInvalidEpGroupPloyDecreaseApi
}

func NewApis(endpointUrl string, client *core.CtyunClient) *Apis {
	client.RegisterEndpoint(core.Endpoint{
		Name: EndpointName,
		Url:  endpointUrl,
	})
	return &Apis{
		CtiamCreateUserApi:                   NewCtiamCreateUserApi(client),
		CtiamUpdateUserApi:                   NewCtiamUpdateUserApi(client),
		CtiamGetEpPageListApi:                NewCtiamGetEpPageListApi(client),
		CtiamCreateGroupApi:                  NewCtiamCreateGroupApi(client),
		CtiamUserToGroupApi:                  NewCtiamUserToGroupApi(client),
		CtiamGetGroupByGroupIdApi:            NewCtiamGetGroupByGroupIdApi(client),
		CtiamInvalidGroupApi:                 NewCtiamInvalidGroupApi(client),
		CtiamGetIdentityProviderInfoApi:      NewCtiamGetIdentityProviderInfoApi(client),
		CtiamGetGroupsApi:                    NewCtiamGetGroupsApi(client),
		CtiamUpdateGroupApi:                  NewCtiamUpdateGroupApi(client),
		CtiamUserOutGroupApi:                 NewCtiamUserOutGroupApi(client),
		CtiamGetGroupUserApi:                 NewCtiamGetGroupUserApi(client),
		CtiamAttachGroupPolicyApi:            NewCtiamAttachGroupPolicyApi(client),
		CtiamInvalidGroupPolicyApi:           NewCtiamInvalidGroupPolicyApi(client),
		CtiamListGroupPolicyApi:              NewCtiamListGroupPolicyApi(client),
		CtiamListUserPolicyApi:               NewCtiamListUserPolicyApi(client),
		CtiamQueryApi:                        NewCtiamQueryApi(client),
		CtiamAttachDelegateRolePolicyApi:     NewCtiamAttachDelegateRolePolicyApi(client),
		CtiamInvalidDelegateRolePolicyApi:    NewCtiamInvalidDelegateRolePolicyApi(client),
		CtiamCreatePolicyApi:                 NewCtiamCreatePolicyApi(client),
		CtiamUpdatePolicyApi:                 NewCtiamUpdatePolicyApi(client),
		CtiamDeletePolicyApi:                 NewCtiamDeletePolicyApi(client),
		CtiamQueryPolicyApi:                  NewCtiamQueryPolicyApi(client),
		CtiamGetPolicyByIdApi:                NewCtiamGetPolicyByIdApi(client),
		CtiamCreateAkApi:                     NewCtiamCreateAkApi(client),
		CtiamQueryAkApi:                      NewCtiamQueryAkApi(client),
		CtiamQueryQuotaByTypeApi:             NewCtiamQueryQuotaByTypeApi(client),
		CtiamQueryRegionByAccountIdApi:       NewCtiamQueryRegionByAccountIdApi(client),
		CtiamCreateDelegateRoleApi:           NewCtiamCreateDelegateRoleApi(client),
		CtiamQueryDelegateRolesApi:           NewCtiamQueryDelegateRolesApi(client),
		CtiamGetDelegateRoleApi:              NewCtiamGetDelegateRoleApi(client),
		CtiamUpdateIdPApi:                    NewCtiamUpdateIdPApi(client),
		CtiamCreateIdPApi:                    NewCtiamCreateIdPApi(client),
		CtiamDeleteIdPApi:                    NewCtiamDeleteIdPApi(client),
		CtiamQueryIdPsApi:                    NewCtiamQueryIdPsApi(client),
		CtiamGetIdPDetailsApi:                NewCtiamGetIdPDetailsApi(client),
		CtiamDeleteDelegateRoleApi:           NewCtiamDeleteDelegateRoleApi(client),
		CtiamCreateEnterpriseProjectApi:      NewCtiamCreateEnterpriseProjectApi(client),
		CtiamUpdateEnterpriseProjectApi:      NewCtiamUpdateEnterpriseProjectApi(client),
		CtiamGetEnterpriseProjectByIdApi:     NewCtiamGetEnterpriseProjectByIdApi(client),
		CtiamSasEnterpriseProjectApi:         NewCtiamSasEnterpriseProjectApi(client),
		CtiamGetEpGroupPageListApi:           NewCtiamGetEpGroupPageListApi(client),
		CtiamAssignmentEpToGroupApi:          NewCtiamAssignmentEpToGroupApi(client),
		CtiamGetEpPloyApi:                    NewCtiamGetEpPloyApi(client),
		CtiamRemoveEpFromGroupApi:            NewCtiamRemoveEpFromGroupApi(client),
		CtiamSetEpGroupPloyApi:               NewCtiamSetEpGroupPloyApi(client),
		CtiamGetResourcePageListApi:          NewCtiamGetResourcePageListApi(client),
		CtiamChangeResourceEpApi:             NewCtiamChangeResourceEpApi(client),
		CtiamDeleteAkApi:                     NewCtiamDeleteAkApi(client),
		CtiamPauseAkApi:                      NewCtiamPauseAkApi(client),
		CtiamOnlineAkApi:                     NewCtiamOnlineAkApi(client),
		CtiamAkToRecycleBinApi:               NewCtiamAkToRecycleBinApi(client),
		CtiamRecoverAkApi:                    NewCtiamRecoverAkApi(client),
		CtiamQueryRecycleBinAkApi:            NewCtiamQueryRecycleBinAkApi(client),
		CtiamSendVerifyCodeToRootApi:         NewCtiamSendVerifyCodeToRootApi(client),
		CtiamResetPwdByRootCodeApi:           NewCtiamResetPwdByRootCodeApi(client),
		CtiamTotpEffectiveChangeApi:          NewCtiamTotpEffectiveChangeApi(client),
		CtiamTotpUriApi:                      NewCtiamTotpUriApi(client),
		CtiamTotpEffectiveApi:                NewCtiamTotpEffectiveApi(client),
		CtiamMfaValidationApi:                NewCtiamMfaValidationApi(client),
		CtiamCancelOrgAttachPolicyApi:        NewCtiamCancelOrgAttachPolicyApi(client),
		CtiamAttachEpPermissionApi:           NewCtiamAttachEpPermissionApi(client),
		CtiamQueryUsersApi:                   NewCtiamQueryUsersApi(client),
		CtiamGetTokenApi:                     NewCtiamGetTokenApi(client),
		CtiamQueryDelegateListApi:            NewCtiamQueryDelegateListApi(client),
		CtiamQueryCtapiServiceByConditionApi: NewCtiamQueryCtapiServiceByConditionApi(client),
		CtiamQueryAllAuthorityByServiceIdApi: NewCtiamQueryAllAuthorityByServiceIdApi(client),
		CtiamAttachGroupToUserApi:            NewCtiamAttachGroupToUserApi(client),
		CtiamRemoveGroupFromUserApi:          NewCtiamRemoveGroupFromUserApi(client),
		CtiamAttachPolicyToUserApi:           NewCtiamAttachPolicyToUserApi(client),
		CtiamQueryPrivilegeByIdApi:           NewCtiamQueryPrivilegeByIdApi(client),
		CtiamQueryCloudCtapiServiceApi:       NewCtiamQueryCloudCtapiServiceApi(client),
		CtiamListUserInheritGroupPolicyApi:   NewCtiamListUserInheritGroupPolicyApi(client),
		CtiamListUserOneselfPolicyApi:        NewCtiamListUserOneselfPolicyApi(client),
		CtiamQuerySensitiveEventApi:          NewCtiamQuerySensitiveEventApi(client),
		CtiamUpdatePhoneAndEmailApi:          NewCtiamUpdatePhoneAndEmailApi(client),
		CtiamSwitchDelegateApi:               NewCtiamSwitchDelegateApi(client),
		CtiamInvalidUserApi:                  NewCtiamInvalidUserApi(client),
		CtiamGetUserApi:                      NewCtiamGetUserApi(client),
		CtiamRestPasswordApi:                 NewCtiamRestPasswordApi(client),
		CtiamCheckCreateUserInfoApi:          NewCtiamCheckCreateUserInfoApi(client),
		CtiamCheckUpdateUserInfoApi:          NewCtiamCheckUpdateUserInfoApi(client),
		CtiamSetAccessControlApi:             NewCtiamSetAccessControlApi(client),
		CtiamQueryAccessControlApi:           NewCtiamQueryAccessControlApi(client),
		CtiamSettingPasswordApi:              NewCtiamSettingPasswordApi(client),
		CtiamSetLoginAuthenApi:               NewCtiamSetLoginAuthenApi(client),
		CtiamQueryLoginAuthenApi:             NewCtiamQueryLoginAuthenApi(client),
		CtiamSecurityOpVerifyApi:             NewCtiamSecurityOpVerifyApi(client),
		CtiamQueryOpVerifyApi:                NewCtiamQueryOpVerifyApi(client),
		CtiamSetEpGroupPloyIncreaseApi:       NewCtiamSetEpGroupPloyIncreaseApi(client),
		CtiamInvalidEpGroupPloyDecreaseApi:   NewCtiamInvalidEpGroupPloyDecreaseApi(client),
	}
}
