package sfs

import (
	"github.com/ctyun-it/terraform-provider-ctyun/internal/core/core"
)

const EndpointName = "sfs"

type Apis struct {
	SfsSfsNewApi                     *SfsSfsNewApi
	SfsListRegionSfsApi              *SfsListRegionSfsApi
	SfsListSfsByOndemandApi          *SfsListSfsByOndemandApi
	SfsListSfsBySfstypeApi           *SfsListSfsBySfstypeApi
	SfsStorageQuotaSfsApi            *SfsStorageQuotaSfsApi
	SfsCountQuotaSfsApi              *SfsCountQuotaSfsApi
	SfsRenameSFSApi                  *SfsRenameSFSApi
	SfsSfsRegionDetailsSfsApi        *SfsSfsRegionDetailsSfsApi
	SfsListSfsBySfsprotocolApi       *SfsListSfsBySfsprotocolApi
	SfsSfsOpenListSfsApi             *SfsSfsOpenListSfsApi
	SfsSfsListRwApi                  *SfsSfsListRwApi
	SfsSfsListReadWriteSfs1Api       *SfsSfsListReadWriteSfs1Api
	SfsDeleteMountpointSfsApi        *SfsDeleteMountpointSfsApi
	SfsSfsSetReadWriteSfsApi         *SfsSfsSetReadWriteSfsApi
	SfsSfsSetReadSfsApi              *SfsSfsSetReadSfsApi
	SfsSfsListVpcSfsApi              *SfsSfsListVpcSfsApi
	SfsSfsUsedRateSfsApi             *SfsSfsUsedRateSfsApi
	SfsSfsFreeSizeSfsApi             *SfsSfsFreeSizeSfsApi
	SfsSfsUsedSizeSfsApi             *SfsSfsUsedSizeSfsApi
	SfsSfsTotalSizeSfsApi            *SfsSfsTotalSizeSfsApi
	SfsSfsInfoApi                    *SfsSfsInfoApi
	SfsSfsInfoByNameApi              *SfsSfsInfoByNameApi
	SfsSfsListApi                    *SfsSfsListApi
	SfsSfsZoneListsfsApi             *SfsSfsZoneListsfsApi
	SfsSfsRegionlistApi              *SfsSfsRegionlistApi
	SfsTotalStorageApi               *SfsTotalStorageApi
	SfsUsedStorageApi                *SfsUsedStorageApi
	SfsFreeStorageApi                *SfsFreeStorageApi
	SfsRateStorageApi                *SfsRateStorageApi
	SfsOpendListApi                  *SfsOpendListApi
	SfsSfsRoApi                      *SfsSfsRoApi
	SfsSfsRwApi                      *SfsSfsRwApi
	SfsSfsInfoByNameSfsApi           *SfsSfsInfoByNameSfsApi
	SfsSfsCreateSfsApi               *SfsSfsCreateSfsApi
	SfsSfsListMountpointApi          *SfsSfsListMountpointApi
	SfsSfsListLabelBySfsApi          *SfsSfsListLabelBySfsApi
	SfsSfsBatchBindLabelApi          *SfsSfsBatchBindLabelApi
	SfsSfsUpdateLabelApi             *SfsSfsUpdateLabelApi
	SfsCreateSubdirSfsApi            *SfsCreateSubdirSfsApi
	SfsSfsNewPermissionSfsApi        *SfsSfsNewPermissionSfsApi
	SfsSfsDeletePermissionSfsApi     *SfsSfsDeletePermissionSfsApi
	SfsSfsModifyPermissionSfsApi     *SfsSfsModifyPermissionSfsApi
	SfsSfsCreateQueryPricesApi       *SfsSfsCreateQueryPricesApi
	SfsSfsQueryPricesApi             *SfsSfsQueryPricesApi
	SfsQueryPricesApi                *SfsQueryPricesApi
	SfsAddMountpointSfsApi           *SfsAddMountpointSfsApi
	SfsSfsChangeVpcSfsApi            *SfsSfsChangeVpcSfsApi
	SfsSfsUnbindVpcSfsApi            *SfsSfsUnbindVpcSfsApi
	SfsSfsBindVpcSfsApi              *SfsSfsBindVpcSfsApi
	SfsSfsModifyPermissionRuleSfsApi *SfsSfsModifyPermissionRuleSfsApi
	SfsSfsListPermissionRuleSfsApi   *SfsSfsListPermissionRuleSfsApi
	SfsSfsDeletePermissionRuleSfsApi *SfsSfsDeletePermissionRuleSfsApi
	SfsSfsNewPermissionRuleSfsApi    *SfsSfsNewPermissionRuleSfsApi
	SfsSfsListPermissionSfsApi       *SfsSfsListPermissionSfsApi
	SfsSfsNewSfsApi                  *SfsSfsNewSfsApi
	SfsSfsRenewSfsApi                *SfsSfsRenewSfsApi
	SfsSfsResizeSfsApi               *SfsSfsResizeSfsApi
	SfsSfsRefundSfsApi               *SfsSfsRefundSfsApi
	SfsPermissionRuleModifyApi       *SfsPermissionRuleModifyApi
	SfsPermissionRuleListApi         *SfsPermissionRuleListApi
	SfsPermissionRuleDeleteApi       *SfsPermissionRuleDeleteApi
	SfsPermissionRuleNewApi          *SfsPermissionRuleNewApi
	SfsModifyPermissionGroupApi      *SfsModifyPermissionGroupApi
	SfsPermissionGroupListApi        *SfsPermissionGroupListApi
	SfsPermissionGroupDeleteApi      *SfsPermissionGroupDeleteApi
	SfsPermissionGroupNewApi         *SfsPermissionGroupNewApi
	SfsListPermissionApi             *SfsListPermissionApi
	SfsChangePermissionApi           *SfsChangePermissionApi
	SfsSfsUnbindPermissionApi        *SfsSfsUnbindPermissionApi
	SfsSfsBindPermissionApi          *SfsSfsBindPermissionApi
	SfsDeleteMountpointApi           *SfsDeleteMountpointApi
	SfsListMountpointApi             *SfsListMountpointApi
	SfsSfsRefundApi                  *SfsSfsRefundApi
	SfsSfsResizeApi                  *SfsSfsResizeApi
	SfsSfsRenewApi                   *SfsSfsRenewApi
	SfsSfsListSfsByVpcidApi          *SfsSfsListSfsByVpcidApi
	SfsVpcQuotaSfsApi                *SfsVpcQuotaSfsApi
	SfsSfsCheckKtbApi                *SfsSfsCheckKtbApi
	SfsSfsListADApi                  *SfsSfsListADApi
	SfsSfsJoinADApi                  *SfsSfsJoinADApi
	SfsSfsModifyADApi                *SfsSfsModifyADApi
	SfsSfsDeleteADApi                *SfsSfsDeleteADApi
	SfsSfsCreateDuplicateApi         *SfsSfsCreateDuplicateApi
	SfsSfsSetProtectSwitchApi        *SfsSfsSetProtectSwitchApi
	SfsSfsListDuplicateApi           *SfsSfsListDuplicateApi
	SfsSfsDeleteDuplicateApi         *SfsSfsDeleteDuplicateApi
	SfsSfsInfoSfsApi                 *SfsSfsInfoSfsApi
}

func NewApis(endpointUrl string, client *core.CtyunClient) *Apis {
	client.RegisterEndpoint(core.Endpoint{
		Name: EndpointName,
		Url:  endpointUrl,
	})
	return &Apis{
		SfsSfsNewApi:                     NewSfsSfsNewApi(client),
		SfsListRegionSfsApi:              NewSfsListRegionSfsApi(client),
		SfsListSfsByOndemandApi:          NewSfsListSfsByOndemandApi(client),
		SfsListSfsBySfstypeApi:           NewSfsListSfsBySfstypeApi(client),
		SfsStorageQuotaSfsApi:            NewSfsStorageQuotaSfsApi(client),
		SfsCountQuotaSfsApi:              NewSfsCountQuotaSfsApi(client),
		SfsRenameSFSApi:                  NewSfsRenameSFSApi(client),
		SfsSfsRegionDetailsSfsApi:        NewSfsSfsRegionDetailsSfsApi(client),
		SfsListSfsBySfsprotocolApi:       NewSfsListSfsBySfsprotocolApi(client),
		SfsSfsOpenListSfsApi:             NewSfsSfsOpenListSfsApi(client),
		SfsSfsListRwApi:                  NewSfsSfsListRwApi(client),
		SfsSfsListReadWriteSfs1Api:       NewSfsSfsListReadWriteSfs1Api(client),
		SfsDeleteMountpointSfsApi:        NewSfsDeleteMountpointSfsApi(client),
		SfsSfsSetReadWriteSfsApi:         NewSfsSfsSetReadWriteSfsApi(client),
		SfsSfsSetReadSfsApi:              NewSfsSfsSetReadSfsApi(client),
		SfsSfsListVpcSfsApi:              NewSfsSfsListVpcSfsApi(client),
		SfsSfsUsedRateSfsApi:             NewSfsSfsUsedRateSfsApi(client),
		SfsSfsFreeSizeSfsApi:             NewSfsSfsFreeSizeSfsApi(client),
		SfsSfsUsedSizeSfsApi:             NewSfsSfsUsedSizeSfsApi(client),
		SfsSfsTotalSizeSfsApi:            NewSfsSfsTotalSizeSfsApi(client),
		SfsSfsInfoApi:                    NewSfsSfsInfoApi(client),
		SfsSfsInfoByNameApi:              NewSfsSfsInfoByNameApi(client),
		SfsSfsListApi:                    NewSfsSfsListApi(client),
		SfsSfsZoneListsfsApi:             NewSfsSfsZoneListsfsApi(client),
		SfsSfsRegionlistApi:              NewSfsSfsRegionlistApi(client),
		SfsTotalStorageApi:               NewSfsTotalStorageApi(client),
		SfsUsedStorageApi:                NewSfsUsedStorageApi(client),
		SfsFreeStorageApi:                NewSfsFreeStorageApi(client),
		SfsRateStorageApi:                NewSfsRateStorageApi(client),
		SfsOpendListApi:                  NewSfsOpendListApi(client),
		SfsSfsRoApi:                      NewSfsSfsRoApi(client),
		SfsSfsRwApi:                      NewSfsSfsRwApi(client),
		SfsSfsInfoByNameSfsApi:           NewSfsSfsInfoByNameSfsApi(client),
		SfsSfsCreateSfsApi:               NewSfsSfsCreateSfsApi(client),
		SfsSfsListMountpointApi:          NewSfsSfsListMountpointApi(client),
		SfsSfsListLabelBySfsApi:          NewSfsSfsListLabelBySfsApi(client),
		SfsSfsBatchBindLabelApi:          NewSfsSfsBatchBindLabelApi(client),
		SfsSfsUpdateLabelApi:             NewSfsSfsUpdateLabelApi(client),
		SfsCreateSubdirSfsApi:            NewSfsCreateSubdirSfsApi(client),
		SfsSfsNewPermissionSfsApi:        NewSfsSfsNewPermissionSfsApi(client),
		SfsSfsDeletePermissionSfsApi:     NewSfsSfsDeletePermissionSfsApi(client),
		SfsSfsModifyPermissionSfsApi:     NewSfsSfsModifyPermissionSfsApi(client),
		SfsSfsCreateQueryPricesApi:       NewSfsSfsCreateQueryPricesApi(client),
		SfsSfsQueryPricesApi:             NewSfsSfsQueryPricesApi(client),
		SfsQueryPricesApi:                NewSfsQueryPricesApi(client),
		SfsAddMountpointSfsApi:           NewSfsAddMountpointSfsApi(client),
		SfsSfsChangeVpcSfsApi:            NewSfsSfsChangeVpcSfsApi(client),
		SfsSfsUnbindVpcSfsApi:            NewSfsSfsUnbindVpcSfsApi(client),
		SfsSfsBindVpcSfsApi:              NewSfsSfsBindVpcSfsApi(client),
		SfsSfsModifyPermissionRuleSfsApi: NewSfsSfsModifyPermissionRuleSfsApi(client),
		SfsSfsListPermissionRuleSfsApi:   NewSfsSfsListPermissionRuleSfsApi(client),
		SfsSfsDeletePermissionRuleSfsApi: NewSfsSfsDeletePermissionRuleSfsApi(client),
		SfsSfsNewPermissionRuleSfsApi:    NewSfsSfsNewPermissionRuleSfsApi(client),
		SfsSfsListPermissionSfsApi:       NewSfsSfsListPermissionSfsApi(client),
		SfsSfsNewSfsApi:                  NewSfsSfsNewSfsApi(client),
		SfsSfsRenewSfsApi:                NewSfsSfsRenewSfsApi(client),
		SfsSfsResizeSfsApi:               NewSfsSfsResizeSfsApi(client),
		SfsSfsRefundSfsApi:               NewSfsSfsRefundSfsApi(client),
		SfsPermissionRuleModifyApi:       NewSfsPermissionRuleModifyApi(client),
		SfsPermissionRuleListApi:         NewSfsPermissionRuleListApi(client),
		SfsPermissionRuleDeleteApi:       NewSfsPermissionRuleDeleteApi(client),
		SfsPermissionRuleNewApi:          NewSfsPermissionRuleNewApi(client),
		SfsModifyPermissionGroupApi:      NewSfsModifyPermissionGroupApi(client),
		SfsPermissionGroupListApi:        NewSfsPermissionGroupListApi(client),
		SfsPermissionGroupDeleteApi:      NewSfsPermissionGroupDeleteApi(client),
		SfsPermissionGroupNewApi:         NewSfsPermissionGroupNewApi(client),
		SfsListPermissionApi:             NewSfsListPermissionApi(client),
		SfsChangePermissionApi:           NewSfsChangePermissionApi(client),
		SfsSfsUnbindPermissionApi:        NewSfsSfsUnbindPermissionApi(client),
		SfsSfsBindPermissionApi:          NewSfsSfsBindPermissionApi(client),
		SfsDeleteMountpointApi:           NewSfsDeleteMountpointApi(client),
		SfsListMountpointApi:             NewSfsListMountpointApi(client),
		SfsSfsRefundApi:                  NewSfsSfsRefundApi(client),
		SfsSfsResizeApi:                  NewSfsSfsResizeApi(client),
		SfsSfsRenewApi:                   NewSfsSfsRenewApi(client),
		SfsSfsListSfsByVpcidApi:          NewSfsSfsListSfsByVpcidApi(client),
		SfsVpcQuotaSfsApi:                NewSfsVpcQuotaSfsApi(client),
		SfsSfsCheckKtbApi:                NewSfsSfsCheckKtbApi(client),
		SfsSfsListADApi:                  NewSfsSfsListADApi(client),
		SfsSfsJoinADApi:                  NewSfsSfsJoinADApi(client),
		SfsSfsModifyADApi:                NewSfsSfsModifyADApi(client),
		SfsSfsDeleteADApi:                NewSfsSfsDeleteADApi(client),
		SfsSfsCreateDuplicateApi:         NewSfsSfsCreateDuplicateApi(client),
		SfsSfsSetProtectSwitchApi:        NewSfsSfsSetProtectSwitchApi(client),
		SfsSfsListDuplicateApi:           NewSfsSfsListDuplicateApi(client),
		SfsSfsDeleteDuplicateApi:         NewSfsSfsDeleteDuplicateApi(client),
		SfsSfsInfoSfsApi:                 NewSfsSfsInfoSfsApi(client),
	}
}
