package ctgkafka

import (
	"github.com/ctyun-it/terraform-provider-ctyun/internal/core/core"
)

const EndpointName = "ctgkafka"

type Apis struct {
	CtgkafkaTopicQueryV3Api                *CtgkafkaTopicQueryV3Api
	CtgkafkaCreatePostPayOrderApi          *CtgkafkaCreatePostPayOrderApi
	CtgkafkaCreateOrderApi                 *CtgkafkaCreateOrderApi
	CtgkafkaSpecExtendApi                  *CtgkafkaSpecExtendApi
	CtgkafkaTransChargeTypeV3Api           *CtgkafkaTransChargeTypeV3Api
	CtgkafkaUnsubscribeInstV3Api           *CtgkafkaUnsubscribeInstV3Api
	CtgkafkaInstQueryApi                   *CtgkafkaInstQueryApi
	CtgkafkaNodeStatusV3Api                *CtgkafkaNodeStatusV3Api
	CtgkafkaInstancesModifyNameV3Api       *CtgkafkaInstancesModifyNameV3Api
	CtgkafkaModifyInstanceConfigApi        *CtgkafkaModifyInstanceConfigApi
	CtgkafkaTopicStatusV3Api               *CtgkafkaTopicStatusV3Api
	CtgkafkaTopicModifyremarkV3Api         *CtgkafkaTopicModifyremarkV3Api
	CtgkafkaModifypartitionNumV3Api        *CtgkafkaModifypartitionNumV3Api
	CtgkafkaTopicDeleteV3Api               *CtgkafkaTopicDeleteV3Api
	CtgkafkaConsumerGroupCreateV3Api       *CtgkafkaConsumerGroupCreateV3Api
	CtgkafkaConsumerGroupQueryV3Api        *CtgkafkaConsumerGroupQueryV3Api
	CtgkafkaConsumerGroupStatusV3Api       *CtgkafkaConsumerGroupStatusV3Api
	CtgkafkaConsumerGroupInstancesV3Api    *CtgkafkaConsumerGroupInstancesV3Api
	CtgkafkaSelectedTopicsV3Api            *CtgkafkaSelectedTopicsV3Api
	CtgkafkaConsumerGroupUpdatetopicsV3Api *CtgkafkaConsumerGroupUpdatetopicsV3Api
	CtgkafkaConsumerGroupResetV3Api        *CtgkafkaConsumerGroupResetV3Api
	CtgkafkaConsumerGroupDeleteV3Api       *CtgkafkaConsumerGroupDeleteV3Api
	CtgkafkaAclAddV3Api                    *CtgkafkaAclAddV3Api
	CtgkafkaAclQueryV3Api                  *CtgkafkaAclQueryV3Api
	CtgkafkaAclDeleteV3Api                 *CtgkafkaAclDeleteV3Api
	CtgkafkaSaslUserCreateV3Api            *CtgkafkaSaslUserCreateV3Api
	CtgkafkaSaslUserQueryV3Api             *CtgkafkaSaslUserQueryV3Api
	CtgkafkaSaslUserDeleteV3Api            *CtgkafkaSaslUserDeleteV3Api
	CtgkafkaQueryMessageByOffsetV3Api      *CtgkafkaQueryMessageByOffsetV3Api
	CtgkafkaQueryMessageByTimestampV3Api   *CtgkafkaQueryMessageByTimestampV3Api
	CtgkafkaResourceTagAddtagV3Api         *CtgkafkaResourceTagAddtagV3Api
	CtgkafkaListTagV3Api                   *CtgkafkaListTagV3Api
	CtgkafkaTagResourceV3Api               *CtgkafkaTagResourceV3Api
	CtgkafkaListResourceV3Api              *CtgkafkaListResourceV3Api
	CtgkafkaUnTagResourceV3Api             *CtgkafkaUnTagResourceV3Api
	CtgkafkaTopicCreateV3Api               *CtgkafkaTopicCreateV3Api
	CtgkafkaDiskExtendApi                  *CtgkafkaDiskExtendApi
	CtgkafkaDiskShrinkApi                  *CtgkafkaDiskShrinkApi
	CtgkafkaNodeExtendApi                  *CtgkafkaNodeExtendApi
	CtgkafkaNodeShrinkApi                  *CtgkafkaNodeShrinkApi
	CtgkafkaSpecShrinkApi                  *CtgkafkaSpecShrinkApi
	CtgkafkaUpgradeInstanceVersionV3Api    *CtgkafkaUpgradeInstanceVersionV3Api
	CtgkafkaInstancesRestartV3Api          *CtgkafkaInstancesRestartV3Api
	CtgkafkaMirrorTaskApi                  *CtgkafkaMirrorTaskApi
	CtgkafkaChangeAzApi                    *CtgkafkaChangeAzApi
	CtgkafkaProdDetailApi                  *CtgkafkaProdDetailApi
	CtgkafkaCanExpandProdApi               *CtgkafkaCanExpandProdApi
	CtgkafkaQueryCanUpdateVersionV3Api     *CtgkafkaQueryCanUpdateVersionV3Api
	CtgkafkaPageQueryFloatingipsApi        *CtgkafkaPageQueryFloatingipsApi
	CtgkafkaGetInstanceConfigApi           *CtgkafkaGetInstanceConfigApi
	CtgkafkaUpdateInstanceConfigApi        *CtgkafkaUpdateInstanceConfigApi
	CtgkafkaSetAcrossVpcInfoApi            *CtgkafkaSetAcrossVpcInfoApi
	CtgkafkaBindElasticIpApi               *CtgkafkaBindElasticIpApi
	CtgkafkaUnbindElasticIpApi             *CtgkafkaUnbindElasticIpApi
	CtgkafkaEnableAutoReassignApi          *CtgkafkaEnableAutoReassignApi
	CtgkafkaElasticBandwidthApi            *CtgkafkaElasticBandwidthApi
	CtgkafkaGetTopicDetailsApi             *CtgkafkaGetTopicDetailsApi
	CtgkafkaEndMessageApi                  *CtgkafkaEndMessageApi
	CtgkafkaBeginningMessageApi            *CtgkafkaBeginningMessageApi
	CtgkafkaQueryProducersApi              *CtgkafkaQueryProducersApi
	CtgkafkaTopicDiskusageApi              *CtgkafkaTopicDiskusageApi
	CtgkafkaUpdateTopicApi                 *CtgkafkaUpdateTopicApi
	CtgkafkaReassignmentsApi               *CtgkafkaReassignmentsApi
	CtgkafkaProduceApi                     *CtgkafkaProduceApi
	CtgkafkaTopicBatchDeleteApi            *CtgkafkaTopicBatchDeleteApi
	CtgkafkaConsumerGroupUpdateApi         *CtgkafkaConsumerGroupUpdateApi
	CtgkafkaConsumerGroupBatchDeleteApi    *CtgkafkaConsumerGroupBatchDeleteApi
	CtgkafkaGetAuthorityApi                *CtgkafkaGetAuthorityApi
	CtgkafkaUserUpdateApi                  *CtgkafkaUserUpdateApi
	CtgkafkaAddAuthorityApi                *CtgkafkaAddAuthorityApi
	CtgkafkaQueryMessageApi                *CtgkafkaQueryMessageApi
	CtgkafkaMonitorMetricsV3Api            *CtgkafkaMonitorMetricsV3Api
	CtgkafkaQuotaBrokerQueryApi            *CtgkafkaQuotaBrokerQueryApi
	CtgkafkaQuotaBrokerDeleteApi           *CtgkafkaQuotaBrokerDeleteApi
	CtgkafkaQuotaBrokerUpdateApi           *CtgkafkaQuotaBrokerUpdateApi
	CtgkafkaQuotaBrokerCreateApi           *CtgkafkaQuotaBrokerCreateApi
	CtgkafkaQuotaTopicListApi              *CtgkafkaQuotaTopicListApi
	CtgkafkaQuotaTopicDeleteApi            *CtgkafkaQuotaTopicDeleteApi
	CtgkafkaQuotaTopicUpdateApi            *CtgkafkaQuotaTopicUpdateApi
	CtgkafkaQuotaTopicCreateApi            *CtgkafkaQuotaTopicCreateApi
	CtgkafkaQuotaClientListApi             *CtgkafkaQuotaClientListApi
	CtgkafkaQuotaClientDeleteApi           *CtgkafkaQuotaClientDeleteApi
	CtgkafkaQuotaClientUpdateApi           *CtgkafkaQuotaClientUpdateApi
	CtgkafkaQuotaClientCreateApi           *CtgkafkaQuotaClientCreateApi
	CtgkafkaChaosQueryReqMsgApi            *CtgkafkaChaosQueryReqMsgApi
	CtgkafkaChaosCancelApi                 *CtgkafkaChaosCancelApi
	CtgkafkaChaosInjectApi                 *CtgkafkaChaosInjectApi
	CtgkafkaChaosListApi                   *CtgkafkaChaosListApi
	CtgkafkaDeleteAuthorityApi             *CtgkafkaDeleteAuthorityApi
	CtgkafkaInstanceDeleteV3Api            *CtgkafkaInstanceDeleteV3Api
}

func NewApis(endpointUrl string, client *core.CtyunClient) *Apis {
	client.RegisterEndpoint(core.Endpoint{
		Name: EndpointName,
		Url:  endpointUrl,
	})
	return &Apis{
		CtgkafkaTopicQueryV3Api:                NewCtgkafkaTopicQueryV3Api(client),
		CtgkafkaCreatePostPayOrderApi:          NewCtgkafkaCreatePostPayOrderApi(client),
		CtgkafkaCreateOrderApi:                 NewCtgkafkaCreateOrderApi(client),
		CtgkafkaSpecExtendApi:                  NewCtgkafkaSpecExtendApi(client),
		CtgkafkaTransChargeTypeV3Api:           NewCtgkafkaTransChargeTypeV3Api(client),
		CtgkafkaUnsubscribeInstV3Api:           NewCtgkafkaUnsubscribeInstV3Api(client),
		CtgkafkaInstQueryApi:                   NewCtgkafkaInstQueryApi(client),
		CtgkafkaNodeStatusV3Api:                NewCtgkafkaNodeStatusV3Api(client),
		CtgkafkaInstancesModifyNameV3Api:       NewCtgkafkaInstancesModifyNameV3Api(client),
		CtgkafkaModifyInstanceConfigApi:        NewCtgkafkaModifyInstanceConfigApi(client),
		CtgkafkaTopicStatusV3Api:               NewCtgkafkaTopicStatusV3Api(client),
		CtgkafkaTopicModifyremarkV3Api:         NewCtgkafkaTopicModifyremarkV3Api(client),
		CtgkafkaModifypartitionNumV3Api:        NewCtgkafkaModifypartitionNumV3Api(client),
		CtgkafkaTopicDeleteV3Api:               NewCtgkafkaTopicDeleteV3Api(client),
		CtgkafkaConsumerGroupCreateV3Api:       NewCtgkafkaConsumerGroupCreateV3Api(client),
		CtgkafkaConsumerGroupQueryV3Api:        NewCtgkafkaConsumerGroupQueryV3Api(client),
		CtgkafkaConsumerGroupStatusV3Api:       NewCtgkafkaConsumerGroupStatusV3Api(client),
		CtgkafkaConsumerGroupInstancesV3Api:    NewCtgkafkaConsumerGroupInstancesV3Api(client),
		CtgkafkaSelectedTopicsV3Api:            NewCtgkafkaSelectedTopicsV3Api(client),
		CtgkafkaConsumerGroupUpdatetopicsV3Api: NewCtgkafkaConsumerGroupUpdatetopicsV3Api(client),
		CtgkafkaConsumerGroupResetV3Api:        NewCtgkafkaConsumerGroupResetV3Api(client),
		CtgkafkaConsumerGroupDeleteV3Api:       NewCtgkafkaConsumerGroupDeleteV3Api(client),
		CtgkafkaAclAddV3Api:                    NewCtgkafkaAclAddV3Api(client),
		CtgkafkaAclQueryV3Api:                  NewCtgkafkaAclQueryV3Api(client),
		CtgkafkaAclDeleteV3Api:                 NewCtgkafkaAclDeleteV3Api(client),
		CtgkafkaSaslUserCreateV3Api:            NewCtgkafkaSaslUserCreateV3Api(client),
		CtgkafkaSaslUserQueryV3Api:             NewCtgkafkaSaslUserQueryV3Api(client),
		CtgkafkaSaslUserDeleteV3Api:            NewCtgkafkaSaslUserDeleteV3Api(client),
		CtgkafkaQueryMessageByOffsetV3Api:      NewCtgkafkaQueryMessageByOffsetV3Api(client),
		CtgkafkaQueryMessageByTimestampV3Api:   NewCtgkafkaQueryMessageByTimestampV3Api(client),
		CtgkafkaResourceTagAddtagV3Api:         NewCtgkafkaResourceTagAddtagV3Api(client),
		CtgkafkaListTagV3Api:                   NewCtgkafkaListTagV3Api(client),
		CtgkafkaTagResourceV3Api:               NewCtgkafkaTagResourceV3Api(client),
		CtgkafkaListResourceV3Api:              NewCtgkafkaListResourceV3Api(client),
		CtgkafkaUnTagResourceV3Api:             NewCtgkafkaUnTagResourceV3Api(client),
		CtgkafkaTopicCreateV3Api:               NewCtgkafkaTopicCreateV3Api(client),
		CtgkafkaDiskExtendApi:                  NewCtgkafkaDiskExtendApi(client),
		CtgkafkaDiskShrinkApi:                  NewCtgkafkaDiskShrinkApi(client),
		CtgkafkaNodeExtendApi:                  NewCtgkafkaNodeExtendApi(client),
		CtgkafkaNodeShrinkApi:                  NewCtgkafkaNodeShrinkApi(client),
		CtgkafkaSpecShrinkApi:                  NewCtgkafkaSpecShrinkApi(client),
		CtgkafkaUpgradeInstanceVersionV3Api:    NewCtgkafkaUpgradeInstanceVersionV3Api(client),
		CtgkafkaInstancesRestartV3Api:          NewCtgkafkaInstancesRestartV3Api(client),
		CtgkafkaMirrorTaskApi:                  NewCtgkafkaMirrorTaskApi(client),
		CtgkafkaChangeAzApi:                    NewCtgkafkaChangeAzApi(client),
		CtgkafkaProdDetailApi:                  NewCtgkafkaProdDetailApi(client),
		CtgkafkaCanExpandProdApi:               NewCtgkafkaCanExpandProdApi(client),
		CtgkafkaQueryCanUpdateVersionV3Api:     NewCtgkafkaQueryCanUpdateVersionV3Api(client),
		CtgkafkaPageQueryFloatingipsApi:        NewCtgkafkaPageQueryFloatingipsApi(client),
		CtgkafkaGetInstanceConfigApi:           NewCtgkafkaGetInstanceConfigApi(client),
		CtgkafkaUpdateInstanceConfigApi:        NewCtgkafkaUpdateInstanceConfigApi(client),
		CtgkafkaSetAcrossVpcInfoApi:            NewCtgkafkaSetAcrossVpcInfoApi(client),
		CtgkafkaBindElasticIpApi:               NewCtgkafkaBindElasticIpApi(client),
		CtgkafkaUnbindElasticIpApi:             NewCtgkafkaUnbindElasticIpApi(client),
		CtgkafkaEnableAutoReassignApi:          NewCtgkafkaEnableAutoReassignApi(client),
		CtgkafkaElasticBandwidthApi:            NewCtgkafkaElasticBandwidthApi(client),
		CtgkafkaGetTopicDetailsApi:             NewCtgkafkaGetTopicDetailsApi(client),
		CtgkafkaEndMessageApi:                  NewCtgkafkaEndMessageApi(client),
		CtgkafkaBeginningMessageApi:            NewCtgkafkaBeginningMessageApi(client),
		CtgkafkaQueryProducersApi:              NewCtgkafkaQueryProducersApi(client),
		CtgkafkaTopicDiskusageApi:              NewCtgkafkaTopicDiskusageApi(client),
		CtgkafkaUpdateTopicApi:                 NewCtgkafkaUpdateTopicApi(client),
		CtgkafkaReassignmentsApi:               NewCtgkafkaReassignmentsApi(client),
		CtgkafkaProduceApi:                     NewCtgkafkaProduceApi(client),
		CtgkafkaTopicBatchDeleteApi:            NewCtgkafkaTopicBatchDeleteApi(client),
		CtgkafkaConsumerGroupUpdateApi:         NewCtgkafkaConsumerGroupUpdateApi(client),
		CtgkafkaConsumerGroupBatchDeleteApi:    NewCtgkafkaConsumerGroupBatchDeleteApi(client),
		CtgkafkaGetAuthorityApi:                NewCtgkafkaGetAuthorityApi(client),
		CtgkafkaUserUpdateApi:                  NewCtgkafkaUserUpdateApi(client),
		CtgkafkaAddAuthorityApi:                NewCtgkafkaAddAuthorityApi(client),
		CtgkafkaQueryMessageApi:                NewCtgkafkaQueryMessageApi(client),
		CtgkafkaMonitorMetricsV3Api:            NewCtgkafkaMonitorMetricsV3Api(client),
		CtgkafkaQuotaBrokerQueryApi:            NewCtgkafkaQuotaBrokerQueryApi(client),
		CtgkafkaQuotaBrokerDeleteApi:           NewCtgkafkaQuotaBrokerDeleteApi(client),
		CtgkafkaQuotaBrokerUpdateApi:           NewCtgkafkaQuotaBrokerUpdateApi(client),
		CtgkafkaQuotaBrokerCreateApi:           NewCtgkafkaQuotaBrokerCreateApi(client),
		CtgkafkaQuotaTopicListApi:              NewCtgkafkaQuotaTopicListApi(client),
		CtgkafkaQuotaTopicDeleteApi:            NewCtgkafkaQuotaTopicDeleteApi(client),
		CtgkafkaQuotaTopicUpdateApi:            NewCtgkafkaQuotaTopicUpdateApi(client),
		CtgkafkaQuotaTopicCreateApi:            NewCtgkafkaQuotaTopicCreateApi(client),
		CtgkafkaQuotaClientListApi:             NewCtgkafkaQuotaClientListApi(client),
		CtgkafkaQuotaClientDeleteApi:           NewCtgkafkaQuotaClientDeleteApi(client),
		CtgkafkaQuotaClientUpdateApi:           NewCtgkafkaQuotaClientUpdateApi(client),
		CtgkafkaQuotaClientCreateApi:           NewCtgkafkaQuotaClientCreateApi(client),
		CtgkafkaChaosQueryReqMsgApi:            NewCtgkafkaChaosQueryReqMsgApi(client),
		CtgkafkaChaosCancelApi:                 NewCtgkafkaChaosCancelApi(client),
		CtgkafkaChaosInjectApi:                 NewCtgkafkaChaosInjectApi(client),
		CtgkafkaChaosListApi:                   NewCtgkafkaChaosListApi(client),
		CtgkafkaDeleteAuthorityApi:             NewCtgkafkaDeleteAuthorityApi(client),
		CtgkafkaInstanceDeleteV3Api:            NewCtgkafkaInstanceDeleteV3Api(client),
	}
}
