package sdwan

import (
	"github.com/ctyun-it/terraform-provider-ctyun/internal/core/core"
)

const EndpointName = "sdwan"

type Apis struct {
	SdwanGetSdwanGplotApi                           *SdwanGetSdwanGplotApi
	SdwanGetSdwanGplotLinkApi                       *SdwanGetSdwanGplotLinkApi
	SdwanGetSdwanGplotDetailApi                     *SdwanGetSdwanGplotDetailApi
	SdwanEdgeInActiveApi                            *SdwanEdgeInActiveApi
	SdwanUpdateGplotApi                             *SdwanUpdateGplotApi
	SdwanCreateEdgeStaticRouteApi                   *SdwanCreateEdgeStaticRouteApi
	SdwanDeleteEdgeStaticRouteApi                   *SdwanDeleteEdgeStaticRouteApi
	SdwanGetEdgeStaticRouteApi                      *SdwanGetEdgeStaticRouteApi
	SdwanCreateEdgeBindSdwanApi                     *SdwanCreateEdgeBindSdwanApi
	SdwanDeleteEdgeBindSdwanApi                     *SdwanDeleteEdgeBindSdwanApi
	SdwanEdgeNetConfigApi                           *SdwanEdgeNetConfigApi
	SdwanEdgeActiveApi                              *SdwanEdgeActiveApi
	SdwanCreateSdwanQosApi                          *SdwanCreateSdwanQosApi
	SdwanUpdateSdwanQosApi                          *SdwanUpdateSdwanQosApi
	SdwanDeleteSdwanQosApi                          *SdwanDeleteSdwanQosApi
	SdwanGetSdwanQosApi                             *SdwanGetSdwanQosApi
	SdwanCreateSdwanQosRuleApi                      *SdwanCreateSdwanQosRuleApi
	SdwanUpdateSdwanQosRuleAppApi                   *SdwanUpdateSdwanQosRuleAppApi
	SdwanGetSdwanQosRuleApi                         *SdwanGetSdwanQosRuleApi
	SdwanCreateEdgeBindQosApi                       *SdwanCreateEdgeBindQosApi
	SdwanDeleteEdgeBindQosApi                       *SdwanDeleteEdgeBindQosApi
	SdwanGetEdgeBindQosApi                          *SdwanGetEdgeBindQosApi
	SdwanGetEdgeUnbindQosApi                        *SdwanGetEdgeUnbindQosApi
	SdwanGetEdgeDeviceInfoApi                       *SdwanGetEdgeDeviceInfoApi
	SdwanGetEdgeLanControlInfoApi                   *SdwanGetEdgeLanControlInfoApi
	SdwanGetEdgeLanInfoApi                          *SdwanGetEdgeLanInfoApi
	SdwanGetEdgeInfoApi                             *SdwanGetEdgeInfoApi
	SdwanGetEdgeLinkApi                             *SdwanGetEdgeLinkApi
	SdwanUpdateEdgeApi                              *SdwanUpdateEdgeApi
	SdwanGetEdgeUpdateVersionApi                    *SdwanGetEdgeUpdateVersionApi
	SdwanGetEdgeVersionApi                          *SdwanGetEdgeVersionApi
	SdwanEdgeDpiSwitchApi                           *SdwanEdgeDpiSwitchApi
	SdwanEdgeDNSSwitchApi                           *SdwanEdgeDNSSwitchApi
	SdwanUpdateEdgeDNSApi                           *SdwanUpdateEdgeDNSApi
	SdwanGetEdgeDNSApi                              *SdwanGetEdgeDNSApi
	SdwanUpdateEdgeSNApi                            *SdwanUpdateEdgeSNApi
	SdwanUpdateEdgeDualArmConfigApi                 *SdwanUpdateEdgeDualArmConfigApi
	SdwanGetEdgeRuleInfoApi                         *SdwanGetEdgeRuleInfoApi
	SdwanGetQosRuleCanConfigCountApi                *SdwanGetQosRuleCanConfigCountApi
	SdwanGetEdgeStaticRouteCanConfigCountApi        *SdwanGetEdgeStaticRouteCanConfigCountApi
	SdwanGetEdgeCanConfigCountApi                   *SdwanGetEdgeCanConfigCountApi
	SdwanGetEdgeLinkCountApi                        *SdwanGetEdgeLinkCountApi
	SdwanCreateEdgeOspfBackupApi                    *SdwanCreateEdgeOspfBackupApi
	SdwanDeleteEdgeOspfBackupApi                    *SdwanDeleteEdgeOspfBackupApi
	SdwanGetEdgeOspfBackupApi                       *SdwanGetEdgeOspfBackupApi
	SdwanGetBackipEdgeOspfApi                       *SdwanGetBackipEdgeOspfApi
	SdwanEdgeOspfSwitchApi                          *SdwanEdgeOspfSwitchApi
	SdwanUpdateEdgeOspfApi                          *SdwanUpdateEdgeOspfApi
	SdwanDeleteEdgeOspfApi                          *SdwanDeleteEdgeOspfApi
	SdwanGetEdgeOspfApi                             *SdwanGetEdgeOspfApi
	SdwanCreateSdwanApi                             *SdwanCreateSdwanApi
	SdwanUpdateSdwanApi                             *SdwanUpdateSdwanApi
	SdwanDeleteSdwanApi                             *SdwanDeleteSdwanApi
	SdwanListSdwanApi                               *SdwanListSdwanApi
	SdwanCreateSdwanEdgeBranchApi                   *SdwanCreateSdwanEdgeBranchApi
	SdwanDeleteSdwanEdgeBranchApi                   *SdwanDeleteSdwanEdgeBranchApi
	SdwanGetSdwanEdgeBranchApi                      *SdwanGetSdwanEdgeBranchApi
	SdwanEdgeLinkConfigApi                          *SdwanEdgeLinkConfigApi
	SdwanGetEdgeBranchEdgeApi                       *SdwanGetEdgeBranchEdgeApi
	SdwanGetHqBranchMonitorApi                      *SdwanGetHqBranchMonitorApi
	SdwanCreateSdwanAclApi                          *SdwanCreateSdwanAclApi
	SdwanDeleteSdwanAclApi                          *SdwanDeleteSdwanAclApi
	SdwanUpdateSdwanAclApi                          *SdwanUpdateSdwanAclApi
	SdwanGetSdwanAclApi                             *SdwanGetSdwanAclApi
	SdwanCreateSdwanAclRuleApi                      *SdwanCreateSdwanAclRuleApi
	SdwanDeleteSdwanAclRuleApi                      *SdwanDeleteSdwanAclRuleApi
	SdwanUpdateSdwanAclRuleApi                      *SdwanUpdateSdwanAclRuleApi
	SdwanGetSdwanAclRuleApi                         *SdwanGetSdwanAclRuleApi
	SdwanBindSdwanAclEdgeApi                        *SdwanBindSdwanAclEdgeApi
	SdwanUnbindSdwanAclEdgeApi                      *SdwanUnbindSdwanAclEdgeApi
	SdwanGetSdwanApp1Api                            *SdwanGetSdwanApp1Api
	SdwanCreateSdwanAppApi                          *SdwanCreateSdwanAppApi
	SdwanUpdateSdwanAppApi                          *SdwanUpdateSdwanAppApi
	SdwanDeleteSdwanAppApi                          *SdwanDeleteSdwanAppApi
	SdwanGetSdwanAppGroupApi                        *SdwanGetSdwanAppGroupApi
	SdwanCreateSdwanAppGroupApi                     *SdwanCreateSdwanAppGroupApi
	SdwanUpdateSdwanAppGroupApi                     *SdwanUpdateSdwanAppGroupApi
	SdwanDeleteSdwanAppGroupApi                     *SdwanDeleteSdwanAppGroupApi
	SdwanGetSdwanAppTrafficApi                      *SdwanGetSdwanAppTrafficApi
	SdwanGetSdwanAppGroupTrafficApi                 *SdwanGetSdwanAppGroupTrafficApi
	SdwanGetSdwanOperationLogApi                    *SdwanGetSdwanOperationLogApi
	SdwanGetSdwanEdgePolicyApi                      *SdwanGetSdwanEdgePolicyApi
	SdwanQuerySdwanEdgePolicyApi                    *SdwanQuerySdwanEdgePolicyApi
	SdwanCreateSdwanEdgePolicyApi                   *SdwanCreateSdwanEdgePolicyApi
	SdwanUpdateSdwanEdgePolicyApi                   *SdwanUpdateSdwanEdgePolicyApi
	SdwanDeleteSdwanEdgePolicyApi                   *SdwanDeleteSdwanEdgePolicyApi
	SdwanConfigSdwanOverloadApi                     *SdwanConfigSdwanOverloadApi
	SdwanGetSdwanOverloadApi                        *SdwanGetSdwanOverloadApi
	SdwanGetSdwanEdgeSaftyFlowApi                   *SdwanGetSdwanEdgeSaftyFlowApi
	SdwanCreateSdwanEdgeSaftyFlowApi                *SdwanCreateSdwanEdgeSaftyFlowApi
	SdwanDeleteSdwanEdgeSaftyFlowApi                *SdwanDeleteSdwanEdgeSaftyFlowApi
	SdwanGetSdwanUserSaftyFlowApi                   *SdwanGetSdwanUserSaftyFlowApi
	SdwanCreateSdwanEdgeSaftyFlowBandwidthApi       *SdwanCreateSdwanEdgeSaftyFlowBandwidthApi
	SdwanUpdateSdwanEdgeSaftyFlowBandwidthApi       *SdwanUpdateSdwanEdgeSaftyFlowBandwidthApi
	SdwanDeleteSdwanEdgeSaftyFlowBandwidthApi       *SdwanDeleteSdwanEdgeSaftyFlowBandwidthApi
	SdwanGetSdwanEdgeSaftyFlowBandwidthApi          *SdwanGetSdwanEdgeSaftyFlowBandwidthApi
	SdwanSdwanEdgeSaftyFlowSwitchApi                *SdwanSdwanEdgeSaftyFlowSwitchApi
	SdwanDeleteSdwanQosRuleAceApi                   *SdwanDeleteSdwanQosRuleAceApi
	SdwanDeleteSdwanQosRuleAppApi                   *SdwanDeleteSdwanQosRuleAppApi
	SdwanSdwanOrderEdgeNewApi                       *SdwanSdwanOrderEdgeNewApi
	SdwanSdwanOrderEdgeRenewApi                     *SdwanSdwanOrderEdgeRenewApi
	SdwanSdwanOrderEdgeRefundApi                    *SdwanSdwanOrderEdgeRefundApi
	SdwanSdwanOrderEdgeUpgradeApi                   *SdwanSdwanOrderEdgeUpgradeApi
	SdwanSdwanQueryAlarmItemApi                     *SdwanSdwanQueryAlarmItemApi
	SdwanSdwanOrderElasticBandwidthPackageNewApi    *SdwanSdwanOrderElasticBandwidthPackageNewApi
	SdwanSdwanOrderElasticBandwidthPackageRefundApi *SdwanSdwanOrderElasticBandwidthPackageRefundApi
	SdwanSdwanListElasticBandwidthPackageApi        *SdwanSdwanListElasticBandwidthPackageApi
	SdwanSdwanEffectElasticBandwidthPackage1Api     *SdwanSdwanEffectElasticBandwidthPackage1Api
	SdwanSdwanEffectElasticBandwidthPackageApi      *SdwanSdwanEffectElasticBandwidthPackageApi
	SdwanSdwanListDetectIPApi                       *SdwanSdwanListDetectIPApi
	SdwanSdwanCreateLinkDetectApi                   *SdwanSdwanCreateLinkDetectApi
	SdwanSdwanDeleteLinkDetectApi                   *SdwanSdwanDeleteLinkDetectApi
	SdwanSdwanQueryLinkQualityWeightApi             *SdwanSdwanQueryLinkQualityWeightApi
	SdwanSdwanSetLinkQualityWeightApi               *SdwanSdwanSetLinkQualityWeightApi
	SdwanSdwanListAclEdgeApi                        *SdwanSdwanListAclEdgeApi
	SdwanSdwanChangeEdgeSNApi                       *SdwanSdwanChangeEdgeSNApi
	SdwanSdwanEdgeLanNicInfoListApi                 *SdwanSdwanEdgeLanNicInfoListApi
	SdwanSdwanConfigEdgePortlinkageApi              *SdwanSdwanConfigEdgePortlinkageApi
	SdwanSdwanQueryEdgePortlinkageApi               *SdwanSdwanQueryEdgePortlinkageApi
	SdwanSdwanDeleteEdgePortlinkageApi              *SdwanSdwanDeleteEdgePortlinkageApi
	SdwanSdwanConfigEdgeSpecialLineApi              *SdwanSdwanConfigEdgeSpecialLineApi
	SdwanSdwanA8CEdgeActiveApi                      *SdwanSdwanA8CEdgeActiveApi
	SdwanSdwanAddSNATApi                            *SdwanSdwanAddSNATApi
	SdwanSdwanUpdateSNATApi                         *SdwanSdwanUpdateSNATApi
	SdwanSdwanDeleteSNATApi                         *SdwanSdwanDeleteSNATApi
	SdwanSdwanListSNATApi                           *SdwanSdwanListSNATApi
	SdwanSdwanAddDNATApi                            *SdwanSdwanAddDNATApi
	SdwanSdwanDeleteDNATApi                         *SdwanSdwanDeleteDNATApi
	SdwanSdwanListDNATApi                           *SdwanSdwanListDNATApi
	SdwanSdwanOfflineEdgeLockApi                    *SdwanSdwanOfflineEdgeLockApi
	SdwanSdwanOfflineEdgeUnlockApi                  *SdwanSdwanOfflineEdgeUnlockApi
	SdwanSdwanListEdgeDatacentersApi                *SdwanSdwanListEdgeDatacentersApi
	SdwanGetSdwanAreaApi                            *SdwanGetSdwanAreaApi
	SdwanSdwanQueryPriceNewApi                      *SdwanSdwanQueryPriceNewApi
	SdwanSdwanQueryPriceRenewApi                    *SdwanSdwanQueryPriceRenewApi
	SdwanSdwanQueryPriceUpgradeApi                  *SdwanSdwanQueryPriceUpgradeApi
	SdwanAddAuthCrossEdgeApi                        *SdwanAddAuthCrossEdgeApi
	SdwanDeleteAuthCrossEdgeApi                     *SdwanDeleteAuthCrossEdgeApi
	SdwanLIstAuthCrossEdgeApi                       *SdwanLIstAuthCrossEdgeApi
	SdwanListAuthCrossGrantEdgeApi                  *SdwanListAuthCrossGrantEdgeApi
	SdwanListAuthCrossAcceptEdgeApi                 *SdwanListAuthCrossAcceptEdgeApi
	SdwanListEdgeBindSdwanListApi                   *SdwanListEdgeBindSdwanListApi
	SdwanListAclEdgeRelationApi                     *SdwanListAclEdgeRelationApi
	SdwanCheckSDWANCidrApi                          *SdwanCheckSDWANCidrApi
	SdwanListEdgeSpecialLineApi                     *SdwanListEdgeSpecialLineApi
	SdwanSyncEdgeDpiApi                             *SdwanSyncEdgeDpiApi
	SdwanGreateQosRuleAceApi                        *SdwanGreateQosRuleAceApi
}

func NewApis(endpointUrl string, client *core.CtyunClient) *Apis {
	client.RegisterEndpoint(core.Endpoint{
		Name: EndpointName,
		Url:  endpointUrl,
	})
	return &Apis{
		SdwanGetSdwanGplotApi:                           NewSdwanGetSdwanGplotApi(client),
		SdwanGetSdwanGplotLinkApi:                       NewSdwanGetSdwanGplotLinkApi(client),
		SdwanGetSdwanGplotDetailApi:                     NewSdwanGetSdwanGplotDetailApi(client),
		SdwanEdgeInActiveApi:                            NewSdwanEdgeInActiveApi(client),
		SdwanUpdateGplotApi:                             NewSdwanUpdateGplotApi(client),
		SdwanCreateEdgeStaticRouteApi:                   NewSdwanCreateEdgeStaticRouteApi(client),
		SdwanDeleteEdgeStaticRouteApi:                   NewSdwanDeleteEdgeStaticRouteApi(client),
		SdwanGetEdgeStaticRouteApi:                      NewSdwanGetEdgeStaticRouteApi(client),
		SdwanCreateEdgeBindSdwanApi:                     NewSdwanCreateEdgeBindSdwanApi(client),
		SdwanDeleteEdgeBindSdwanApi:                     NewSdwanDeleteEdgeBindSdwanApi(client),
		SdwanEdgeNetConfigApi:                           NewSdwanEdgeNetConfigApi(client),
		SdwanEdgeActiveApi:                              NewSdwanEdgeActiveApi(client),
		SdwanCreateSdwanQosApi:                          NewSdwanCreateSdwanQosApi(client),
		SdwanUpdateSdwanQosApi:                          NewSdwanUpdateSdwanQosApi(client),
		SdwanDeleteSdwanQosApi:                          NewSdwanDeleteSdwanQosApi(client),
		SdwanGetSdwanQosApi:                             NewSdwanGetSdwanQosApi(client),
		SdwanCreateSdwanQosRuleApi:                      NewSdwanCreateSdwanQosRuleApi(client),
		SdwanUpdateSdwanQosRuleAppApi:                   NewSdwanUpdateSdwanQosRuleAppApi(client),
		SdwanGetSdwanQosRuleApi:                         NewSdwanGetSdwanQosRuleApi(client),
		SdwanCreateEdgeBindQosApi:                       NewSdwanCreateEdgeBindQosApi(client),
		SdwanDeleteEdgeBindQosApi:                       NewSdwanDeleteEdgeBindQosApi(client),
		SdwanGetEdgeBindQosApi:                          NewSdwanGetEdgeBindQosApi(client),
		SdwanGetEdgeUnbindQosApi:                        NewSdwanGetEdgeUnbindQosApi(client),
		SdwanGetEdgeDeviceInfoApi:                       NewSdwanGetEdgeDeviceInfoApi(client),
		SdwanGetEdgeLanControlInfoApi:                   NewSdwanGetEdgeLanControlInfoApi(client),
		SdwanGetEdgeLanInfoApi:                          NewSdwanGetEdgeLanInfoApi(client),
		SdwanGetEdgeInfoApi:                             NewSdwanGetEdgeInfoApi(client),
		SdwanGetEdgeLinkApi:                             NewSdwanGetEdgeLinkApi(client),
		SdwanUpdateEdgeApi:                              NewSdwanUpdateEdgeApi(client),
		SdwanGetEdgeUpdateVersionApi:                    NewSdwanGetEdgeUpdateVersionApi(client),
		SdwanGetEdgeVersionApi:                          NewSdwanGetEdgeVersionApi(client),
		SdwanEdgeDpiSwitchApi:                           NewSdwanEdgeDpiSwitchApi(client),
		SdwanEdgeDNSSwitchApi:                           NewSdwanEdgeDNSSwitchApi(client),
		SdwanUpdateEdgeDNSApi:                           NewSdwanUpdateEdgeDNSApi(client),
		SdwanGetEdgeDNSApi:                              NewSdwanGetEdgeDNSApi(client),
		SdwanUpdateEdgeSNApi:                            NewSdwanUpdateEdgeSNApi(client),
		SdwanUpdateEdgeDualArmConfigApi:                 NewSdwanUpdateEdgeDualArmConfigApi(client),
		SdwanGetEdgeRuleInfoApi:                         NewSdwanGetEdgeRuleInfoApi(client),
		SdwanGetQosRuleCanConfigCountApi:                NewSdwanGetQosRuleCanConfigCountApi(client),
		SdwanGetEdgeStaticRouteCanConfigCountApi:        NewSdwanGetEdgeStaticRouteCanConfigCountApi(client),
		SdwanGetEdgeCanConfigCountApi:                   NewSdwanGetEdgeCanConfigCountApi(client),
		SdwanGetEdgeLinkCountApi:                        NewSdwanGetEdgeLinkCountApi(client),
		SdwanCreateEdgeOspfBackupApi:                    NewSdwanCreateEdgeOspfBackupApi(client),
		SdwanDeleteEdgeOspfBackupApi:                    NewSdwanDeleteEdgeOspfBackupApi(client),
		SdwanGetEdgeOspfBackupApi:                       NewSdwanGetEdgeOspfBackupApi(client),
		SdwanGetBackipEdgeOspfApi:                       NewSdwanGetBackipEdgeOspfApi(client),
		SdwanEdgeOspfSwitchApi:                          NewSdwanEdgeOspfSwitchApi(client),
		SdwanUpdateEdgeOspfApi:                          NewSdwanUpdateEdgeOspfApi(client),
		SdwanDeleteEdgeOspfApi:                          NewSdwanDeleteEdgeOspfApi(client),
		SdwanGetEdgeOspfApi:                             NewSdwanGetEdgeOspfApi(client),
		SdwanCreateSdwanApi:                             NewSdwanCreateSdwanApi(client),
		SdwanUpdateSdwanApi:                             NewSdwanUpdateSdwanApi(client),
		SdwanDeleteSdwanApi:                             NewSdwanDeleteSdwanApi(client),
		SdwanListSdwanApi:                               NewSdwanListSdwanApi(client),
		SdwanCreateSdwanEdgeBranchApi:                   NewSdwanCreateSdwanEdgeBranchApi(client),
		SdwanDeleteSdwanEdgeBranchApi:                   NewSdwanDeleteSdwanEdgeBranchApi(client),
		SdwanGetSdwanEdgeBranchApi:                      NewSdwanGetSdwanEdgeBranchApi(client),
		SdwanEdgeLinkConfigApi:                          NewSdwanEdgeLinkConfigApi(client),
		SdwanGetEdgeBranchEdgeApi:                       NewSdwanGetEdgeBranchEdgeApi(client),
		SdwanGetHqBranchMonitorApi:                      NewSdwanGetHqBranchMonitorApi(client),
		SdwanCreateSdwanAclApi:                          NewSdwanCreateSdwanAclApi(client),
		SdwanDeleteSdwanAclApi:                          NewSdwanDeleteSdwanAclApi(client),
		SdwanUpdateSdwanAclApi:                          NewSdwanUpdateSdwanAclApi(client),
		SdwanGetSdwanAclApi:                             NewSdwanGetSdwanAclApi(client),
		SdwanCreateSdwanAclRuleApi:                      NewSdwanCreateSdwanAclRuleApi(client),
		SdwanDeleteSdwanAclRuleApi:                      NewSdwanDeleteSdwanAclRuleApi(client),
		SdwanUpdateSdwanAclRuleApi:                      NewSdwanUpdateSdwanAclRuleApi(client),
		SdwanGetSdwanAclRuleApi:                         NewSdwanGetSdwanAclRuleApi(client),
		SdwanBindSdwanAclEdgeApi:                        NewSdwanBindSdwanAclEdgeApi(client),
		SdwanUnbindSdwanAclEdgeApi:                      NewSdwanUnbindSdwanAclEdgeApi(client),
		SdwanGetSdwanApp1Api:                            NewSdwanGetSdwanApp1Api(client),
		SdwanCreateSdwanAppApi:                          NewSdwanCreateSdwanAppApi(client),
		SdwanUpdateSdwanAppApi:                          NewSdwanUpdateSdwanAppApi(client),
		SdwanDeleteSdwanAppApi:                          NewSdwanDeleteSdwanAppApi(client),
		SdwanGetSdwanAppGroupApi:                        NewSdwanGetSdwanAppGroupApi(client),
		SdwanCreateSdwanAppGroupApi:                     NewSdwanCreateSdwanAppGroupApi(client),
		SdwanUpdateSdwanAppGroupApi:                     NewSdwanUpdateSdwanAppGroupApi(client),
		SdwanDeleteSdwanAppGroupApi:                     NewSdwanDeleteSdwanAppGroupApi(client),
		SdwanGetSdwanAppTrafficApi:                      NewSdwanGetSdwanAppTrafficApi(client),
		SdwanGetSdwanAppGroupTrafficApi:                 NewSdwanGetSdwanAppGroupTrafficApi(client),
		SdwanGetSdwanOperationLogApi:                    NewSdwanGetSdwanOperationLogApi(client),
		SdwanGetSdwanEdgePolicyApi:                      NewSdwanGetSdwanEdgePolicyApi(client),
		SdwanQuerySdwanEdgePolicyApi:                    NewSdwanQuerySdwanEdgePolicyApi(client),
		SdwanCreateSdwanEdgePolicyApi:                   NewSdwanCreateSdwanEdgePolicyApi(client),
		SdwanUpdateSdwanEdgePolicyApi:                   NewSdwanUpdateSdwanEdgePolicyApi(client),
		SdwanDeleteSdwanEdgePolicyApi:                   NewSdwanDeleteSdwanEdgePolicyApi(client),
		SdwanConfigSdwanOverloadApi:                     NewSdwanConfigSdwanOverloadApi(client),
		SdwanGetSdwanOverloadApi:                        NewSdwanGetSdwanOverloadApi(client),
		SdwanGetSdwanEdgeSaftyFlowApi:                   NewSdwanGetSdwanEdgeSaftyFlowApi(client),
		SdwanCreateSdwanEdgeSaftyFlowApi:                NewSdwanCreateSdwanEdgeSaftyFlowApi(client),
		SdwanDeleteSdwanEdgeSaftyFlowApi:                NewSdwanDeleteSdwanEdgeSaftyFlowApi(client),
		SdwanGetSdwanUserSaftyFlowApi:                   NewSdwanGetSdwanUserSaftyFlowApi(client),
		SdwanCreateSdwanEdgeSaftyFlowBandwidthApi:       NewSdwanCreateSdwanEdgeSaftyFlowBandwidthApi(client),
		SdwanUpdateSdwanEdgeSaftyFlowBandwidthApi:       NewSdwanUpdateSdwanEdgeSaftyFlowBandwidthApi(client),
		SdwanDeleteSdwanEdgeSaftyFlowBandwidthApi:       NewSdwanDeleteSdwanEdgeSaftyFlowBandwidthApi(client),
		SdwanGetSdwanEdgeSaftyFlowBandwidthApi:          NewSdwanGetSdwanEdgeSaftyFlowBandwidthApi(client),
		SdwanSdwanEdgeSaftyFlowSwitchApi:                NewSdwanSdwanEdgeSaftyFlowSwitchApi(client),
		SdwanDeleteSdwanQosRuleAceApi:                   NewSdwanDeleteSdwanQosRuleAceApi(client),
		SdwanDeleteSdwanQosRuleAppApi:                   NewSdwanDeleteSdwanQosRuleAppApi(client),
		SdwanSdwanOrderEdgeNewApi:                       NewSdwanSdwanOrderEdgeNewApi(client),
		SdwanSdwanOrderEdgeRenewApi:                     NewSdwanSdwanOrderEdgeRenewApi(client),
		SdwanSdwanOrderEdgeRefundApi:                    NewSdwanSdwanOrderEdgeRefundApi(client),
		SdwanSdwanOrderEdgeUpgradeApi:                   NewSdwanSdwanOrderEdgeUpgradeApi(client),
		SdwanSdwanQueryAlarmItemApi:                     NewSdwanSdwanQueryAlarmItemApi(client),
		SdwanSdwanOrderElasticBandwidthPackageNewApi:    NewSdwanSdwanOrderElasticBandwidthPackageNewApi(client),
		SdwanSdwanOrderElasticBandwidthPackageRefundApi: NewSdwanSdwanOrderElasticBandwidthPackageRefundApi(client),
		SdwanSdwanListElasticBandwidthPackageApi:        NewSdwanSdwanListElasticBandwidthPackageApi(client),
		SdwanSdwanEffectElasticBandwidthPackage1Api:     NewSdwanSdwanEffectElasticBandwidthPackage1Api(client),
		SdwanSdwanEffectElasticBandwidthPackageApi:      NewSdwanSdwanEffectElasticBandwidthPackageApi(client),
		SdwanSdwanListDetectIPApi:                       NewSdwanSdwanListDetectIPApi(client),
		SdwanSdwanCreateLinkDetectApi:                   NewSdwanSdwanCreateLinkDetectApi(client),
		SdwanSdwanDeleteLinkDetectApi:                   NewSdwanSdwanDeleteLinkDetectApi(client),
		SdwanSdwanQueryLinkQualityWeightApi:             NewSdwanSdwanQueryLinkQualityWeightApi(client),
		SdwanSdwanSetLinkQualityWeightApi:               NewSdwanSdwanSetLinkQualityWeightApi(client),
		SdwanSdwanListAclEdgeApi:                        NewSdwanSdwanListAclEdgeApi(client),
		SdwanSdwanChangeEdgeSNApi:                       NewSdwanSdwanChangeEdgeSNApi(client),
		SdwanSdwanEdgeLanNicInfoListApi:                 NewSdwanSdwanEdgeLanNicInfoListApi(client),
		SdwanSdwanConfigEdgePortlinkageApi:              NewSdwanSdwanConfigEdgePortlinkageApi(client),
		SdwanSdwanQueryEdgePortlinkageApi:               NewSdwanSdwanQueryEdgePortlinkageApi(client),
		SdwanSdwanDeleteEdgePortlinkageApi:              NewSdwanSdwanDeleteEdgePortlinkageApi(client),
		SdwanSdwanConfigEdgeSpecialLineApi:              NewSdwanSdwanConfigEdgeSpecialLineApi(client),
		SdwanSdwanA8CEdgeActiveApi:                      NewSdwanSdwanA8CEdgeActiveApi(client),
		SdwanSdwanAddSNATApi:                            NewSdwanSdwanAddSNATApi(client),
		SdwanSdwanUpdateSNATApi:                         NewSdwanSdwanUpdateSNATApi(client),
		SdwanSdwanDeleteSNATApi:                         NewSdwanSdwanDeleteSNATApi(client),
		SdwanSdwanListSNATApi:                           NewSdwanSdwanListSNATApi(client),
		SdwanSdwanAddDNATApi:                            NewSdwanSdwanAddDNATApi(client),
		SdwanSdwanDeleteDNATApi:                         NewSdwanSdwanDeleteDNATApi(client),
		SdwanSdwanListDNATApi:                           NewSdwanSdwanListDNATApi(client),
		SdwanSdwanOfflineEdgeLockApi:                    NewSdwanSdwanOfflineEdgeLockApi(client),
		SdwanSdwanOfflineEdgeUnlockApi:                  NewSdwanSdwanOfflineEdgeUnlockApi(client),
		SdwanSdwanListEdgeDatacentersApi:                NewSdwanSdwanListEdgeDatacentersApi(client),
		SdwanGetSdwanAreaApi:                            NewSdwanGetSdwanAreaApi(client),
		SdwanSdwanQueryPriceNewApi:                      NewSdwanSdwanQueryPriceNewApi(client),
		SdwanSdwanQueryPriceRenewApi:                    NewSdwanSdwanQueryPriceRenewApi(client),
		SdwanSdwanQueryPriceUpgradeApi:                  NewSdwanSdwanQueryPriceUpgradeApi(client),
		SdwanAddAuthCrossEdgeApi:                        NewSdwanAddAuthCrossEdgeApi(client),
		SdwanDeleteAuthCrossEdgeApi:                     NewSdwanDeleteAuthCrossEdgeApi(client),
		SdwanLIstAuthCrossEdgeApi:                       NewSdwanLIstAuthCrossEdgeApi(client),
		SdwanListAuthCrossGrantEdgeApi:                  NewSdwanListAuthCrossGrantEdgeApi(client),
		SdwanListAuthCrossAcceptEdgeApi:                 NewSdwanListAuthCrossAcceptEdgeApi(client),
		SdwanListEdgeBindSdwanListApi:                   NewSdwanListEdgeBindSdwanListApi(client),
		SdwanListAclEdgeRelationApi:                     NewSdwanListAclEdgeRelationApi(client),
		SdwanCheckSDWANCidrApi:                          NewSdwanCheckSDWANCidrApi(client),
		SdwanListEdgeSpecialLineApi:                     NewSdwanListEdgeSpecialLineApi(client),
		SdwanSyncEdgeDpiApi:                             NewSdwanSyncEdgeDpiApi(client),
		SdwanGreateQosRuleAceApi:                        NewSdwanGreateQosRuleAceApi(client),
	}
}
