package ctecs

import (
	"github.com/ctyun-it/terraform-provider-ctyun/internal/core/core"
)

const EndpointName = "ctecs"

type Apis struct {
	CtecsDeleteInstanceAndRelatedResourceApi        *CtecsDeleteInstanceAndRelatedResourceApi
	CtecsRecoverUnsubscribeInstanceV41Api           *CtecsRecoverUnsubscribeInstanceV41Api
	CtecsGetCaAgentApi                              *CtecsGetCaAgentApi
	CtecsDescribeSendFileResultsApi                 *CtecsDescribeSendFileResultsApi
	CtecsSendFileApi                                *CtecsSendFileApi
	CtecsGetCommandApi                              *CtecsGetCommandApi
	CtecsGetCommandsApi                             *CtecsGetCommandsApi
	CtecsInvokeCommandApi                           *CtecsInvokeCommandApi
	CtecsDeleteCommandApi                           *CtecsDeleteCommandApi
	CtecsModifyCommandApi                           *CtecsModifyCommandApi
	CtecsCreateCommandApi                           *CtecsCreateCommandApi
	CtecsCreateSameConfigInstancesApi               *CtecsCreateSameConfigInstancesApi
	CtecsBatchOperateEcsLabelV41Api                 *CtecsBatchOperateEcsLabelV41Api
	CtecsUpdateEcsLabelV41Api                       *CtecsUpdateEcsLabelV41Api
	CtecsOperateAllInstancesV41Api                  *CtecsOperateAllInstancesV41Api
	CtecsLiteEcsCreateVolumeApi                     *CtecsLiteEcsCreateVolumeApi
	CtecsListBackupTaskApi                          *CtecsListBackupTaskApi
	CtecsListUpdateSpecFlavorV41Api                 *CtecsListUpdateSpecFlavorV41Api
	CtecsRebuildLiteInstanceApi                     *CtecsRebuildLiteInstanceApi
	CtecsEcsSnapshotTaskListApi                     *CtecsEcsSnapshotTaskListApi
	CtecsLiteEcsUnsubscribeVolumeApi                *CtecsLiteEcsUnsubscribeVolumeApi
	CtecsEcsSnapshotBatchDeleteApi                  *CtecsEcsSnapshotBatchDeleteApi
	CtecsDestroyInstanceApi                         *CtecsDestroyInstanceApi
	CtecsEcsDeleteDelegateApi                       *CtecsEcsDeleteDelegateApi
	CtecsEcsAttachDelegateApi                       *CtecsEcsAttachDelegateApi
	CtecsCloudAssistantDescribeInvocationResultsApi *CtecsCloudAssistantDescribeInvocationResultsApi
	CtecsCloudAssistantRunCommandApi                *CtecsCloudAssistantRunCommandApi
	CtecsListGpuDriverV41Api                        *CtecsListGpuDriverV41Api
	CtecsBatchShelveInstancesApi                    *CtecsBatchShelveInstancesApi
	CtecsShelveInstanceApi                          *CtecsShelveInstanceApi
	CtecsAffinityGroupUnbindInstancesApi            *CtecsAffinityGroupUnbindInstancesApi
	CtecsInstanceDetachSfsV41Api                    *CtecsInstanceDetachSfsV41Api
	CtecsInstanceAttachSfsV41Api                    *CtecsInstanceAttachSfsV41Api
	CtecsListSfsInstanceV41Api                      *CtecsListSfsInstanceV41Api
	CtecsListInstanceSfsV41Api                      *CtecsListInstanceSfsV41Api
	CtecsUpdateDeletionProtectionV41Api             *CtecsUpdateDeletionProtectionV41Api
	CtecsLiveResizeInstanceV41Api                   *CtecsLiveResizeInstanceV41Api
	CtecsListLiveResizeFlavorV41Api                 *CtecsListLiveResizeFlavorV41Api
	CtecsQuerySnapshotStatisticsV41Api              *CtecsQuerySnapshotStatisticsV41Api
	CtecsShowVolumeV41Api                           *CtecsShowVolumeV41Api
	CtecsListFlavorLiteInstanceV41Api               *CtecsListFlavorLiteInstanceV41Api
	CtecsDeleteVolumeV41Api                         *CtecsDeleteVolumeV41Api
	CtecsAttachVolumeV41Api                         *CtecsAttachVolumeV41Api
	CtecsExtendVolumeV41Api                         *CtecsExtendVolumeV41Api
	CtecsDetachVolumeV41Api                         *CtecsDetachVolumeV41Api
	CtecsUpdateSpecLiteInstanceV41Api               *CtecsUpdateSpecLiteInstanceV41Api
	CtecsResetLiteInstancePasswordV41Api            *CtecsResetLiteInstancePasswordV41Api
	CtecsRebootLiteInstanceV41Api                   *CtecsRebootLiteInstanceV41Api
	CtecsStopLiteInstanceV41Api                     *CtecsStopLiteInstanceV41Api
	CtecsStartLiteInstanceV41Api                    *CtecsStartLiteInstanceV41Api
	CtecsDetailsVncLiteInstanceV41Api               *CtecsDetailsVncLiteInstanceV41Api
	CtecsUnsubscribeLiteInstanceV41Api              *CtecsUnsubscribeLiteInstanceV41Api
	CtecsResubscribeLiteInstanceV41Api              *CtecsResubscribeLiteInstanceV41Api
	CtecsDetailsLiteInstanceV41Api                  *CtecsDetailsLiteInstanceV41Api
	CtecsListLiteInstanceV41Api                     *CtecsListLiteInstanceV41Api
	CtecsCreateLiteInstanceV41Api                   *CtecsCreateLiteInstanceV41Api
	CtecsUpdateVolumeV41Api                         *CtecsUpdateVolumeV41Api
	CtecsCreateVolumeV41Api                         *CtecsCreateVolumeV41Api
	CtecsQueryOrderUuidV41Api                       *CtecsQueryOrderUuidV41Api
	CtecsQueryCustomerQuotasInRegionV41Api          *CtecsQueryCustomerQuotasInRegionV41Api
	CtecsQueryCustomerResourcesInRegionV41Api       *CtecsQueryCustomerResourcesInRegionV41Api
	CtecsDeleteSnapshotpolicyV41Api                 *CtecsDeleteSnapshotpolicyV41Api
	CtecsQueryInstancIDV41Api                       *CtecsQueryInstancIDV41Api
	CtecsExecuteSnapshotPolicyV41Api                *CtecsExecuteSnapshotPolicyV41Api
	CtecsListInstanceSnapshotPolicyV41Api           *CtecsListInstanceSnapshotPolicyV41Api
	CtecsDetailsSnapshotpolicyV41Api                *CtecsDetailsSnapshotpolicyV41Api
	CtecsListSnapshotPolicyV41Api                   *CtecsListSnapshotPolicyV41Api
	CtecsListSnapshotPolicyTaskV41Api               *CtecsListSnapshotPolicyTaskV41Api
	CtecsSnapshotPolicyUnbindInstancesV41Api        *CtecsSnapshotPolicyUnbindInstancesV41Api
	CtecsSnapshotpolicyBindInstanceV41Api           *CtecsSnapshotpolicyBindInstanceV41Api
	CtecsEnableSnapshotPolicyV41Api                 *CtecsEnableSnapshotPolicyV41Api
	CtecsCreateSnapshotpolicyV41Api                 *CtecsCreateSnapshotpolicyV41Api
	CtecsDisableSnapshotPolicyV41Api                *CtecsDisableSnapshotPolicyV41Api
	CtecsUpdateSnapshotPolicyV41Api                 *CtecsUpdateSnapshotPolicyV41Api
	CtecsQueryJobV41Api                             *CtecsQueryJobV41Api
	CtecsDescribeInstancesApi                       *CtecsDescribeInstancesApi
	CtecsCreateMetadataV41Api                       *CtecsCreateMetadataV41Api
	CtecsListInstanceBackupV41Api                   *CtecsListInstanceBackupV41Api
	CtecsDetailsInstanceBackupV41Api                *CtecsDetailsInstanceBackupV41Api
	CtecsCreateSnapshotV41Api                       *CtecsCreateSnapshotV41Api
	CtecsUpdateSnapshotV41Api                       *CtecsUpdateSnapshotV41Api
	CtecsBatchUpdateSnapshotV41Api                  *CtecsBatchUpdateSnapshotV41Api
	CtecsQuerySnapshotListV41Api                    *CtecsQuerySnapshotListV41Api
	CtecsQuerySnapshotStatusV41Api                  *CtecsQuerySnapshotStatusV41Api
	CtecsQuerySnapshotDetailsV41Api                 *CtecsQuerySnapshotDetailsV41Api
	CtecsImportKeypairV41Api                        *CtecsImportKeypairV41Api
	CtecsCreateKeypairV41Api                        *CtecsCreateKeypairV41Api
	CtecsStatusInstanceBackupV41Api                 *CtecsStatusInstanceBackupV41Api
	CtecsDetailsKeypairV41Api                       *CtecsDetailsKeypairV41Api
	CtecsKeypairAttachInstanceV41Api                *CtecsKeypairAttachInstanceV41Api
	CtecsInstanceDetachKeypairV41Api                *CtecsInstanceDetachKeypairV41Api
	CtecsUpdateInstanceBackupV41Api                 *CtecsUpdateInstanceBackupV41Api
	CtecsBackupBatchUpdateApi                       *CtecsBackupBatchUpdateApi
	CtecsCreateInstanceBackupV41Api                 *CtecsCreateInstanceBackupV41Api
	CtecsDetailsBackupInstanceV41Api                *CtecsDetailsBackupInstanceV41Api
	CtecsTotalInstanceBackupVolumeSizeV41Api        *CtecsTotalInstanceBackupVolumeSizeV41Api
	CtecsListFlavorV41Api                           *CtecsListFlavorV41Api
	CtecsListFlavorFamiliesV41Api                   *CtecsListFlavorFamiliesV41Api
	CtecsListInstanceFlavorFamiliesV41Api           *CtecsListInstanceFlavorFamiliesV41Api
	CtecsListAffinityGroupV41Api                    *CtecsListAffinityGroupV41Api
	CtecsDeleteMetadataV41Api                       *CtecsDeleteMetadataV41Api
	CtecsUpdateMetadataV41Api                       *CtecsUpdateMetadataV41Api
	CtecsGetAffinityGroupV41Api                     *CtecsGetAffinityGroupV41Api
	CtecsListAffinityGroupInstanceV41Api            *CtecsListAffinityGroupInstanceV41Api
	CtecsDetailsMetadataV41Api                      *CtecsDetailsMetadataV41Api
	CtecsCreateAffinityGroupV41Api                  *CtecsCreateAffinityGroupV41Api
	CtecsAffinityGroupbindInstanceV41Api            *CtecsAffinityGroupbindInstanceV41Api
	CtecsDescribeAvailabilityZonesV41Api            *CtecsDescribeAvailabilityZonesV41Api
	CtecsAffinityGroupUnbindInstanceV41Api          *CtecsAffinityGroupUnbindInstanceV41Api
	CtecsAffinityGroupbindInstanceCheckV41Api       *CtecsAffinityGroupbindInstanceCheckV41Api
	CtecsQueryUserdataDetailsV41Api                 *CtecsQueryUserdataDetailsV41Api
	CtecsDetailsInstanceV41Api                      *CtecsDetailsInstanceV41Api
	CtecsListInstanceV41Api                         *CtecsListInstanceV41Api
	CtecsListInstanceStatusV41Api                   *CtecsListInstanceStatusV41Api
	CtecsListFixedIpV41Api                          *CtecsListFixedIpV41Api
	CtecsBatchRebuildInstancesV41Api                *CtecsBatchRebuildInstancesV41Api
	CtecsBatchRebootInstancesV41Api                 *CtecsBatchRebootInstancesV41Api
	CtecsBatchStopInstancesV41Api                   *CtecsBatchStopInstancesV41Api
	CtecsBatchStartInstancesV41Api                  *CtecsBatchStartInstancesV41Api
	CtecsRebuildInstanceV41Api                      *CtecsRebuildInstanceV41Api
	CtecsRebootInstanceV41Api                       *CtecsRebootInstanceV41Api
	CtecsStopInstanceV41Api                         *CtecsStopInstanceV41Api
	CtecsStartInstanceV41Api                        *CtecsStartInstanceV41Api
	CtecsUpdateNetworkSpecV41Api                    *CtecsUpdateNetworkSpecV41Api
	CtecsInstanceAttachShareInterfaceV41Api         *CtecsInstanceAttachShareInterfaceV41Api
	CtecsUpdateFlavorSpecV41Api                     *CtecsUpdateFlavorSpecV41Api
	CtecsUpdateInstanceSpecV41Api                   *CtecsUpdateInstanceSpecV41Api
	CtecsGetVolumeStatisticsV41Api                  *CtecsGetVolumeStatisticsV41Api
	CtecsQueryVolumeListV41Api                      *CtecsQueryVolumeListV41Api
	CtecsQueryVncDetailsV41Api                      *CtecsQueryVncDetailsV41Api
	CtecsBatchUpdateInstancesPasswordV41Api         *CtecsBatchUpdateInstancesPasswordV41Api
	CtecsResetInstancePasswordV41Api                *CtecsResetInstancePasswordV41Api
	CtecsBatchUpdateInstancesV41Api                 *CtecsBatchUpdateInstancesV41Api
	CtecsUpdateInstanceV41Api                       *CtecsUpdateInstanceV41Api
	CtecsUnsubscribeInstanceV41Api                  *CtecsUnsubscribeInstanceV41Api
	CtecsResubscribeInstanceV41Api                  *CtecsResubscribeInstanceV41Api
	CtecsBatchCreateInstancesV41Api                 *CtecsBatchCreateInstancesV41Api
	CtecsCreateInstanceV41Api                       *CtecsCreateInstanceV41Api
	CtecsCloneInstanceApi                           *CtecsCloneInstanceApi
	CtecsCreateInstanceByInstanceBackupApi          *CtecsCreateInstanceByInstanceBackupApi
	CtecsSnapshotCreateInstanceV41Api               *CtecsSnapshotCreateInstanceV41Api
	CtecsListInstanceBackupPolicyBindInstancesApi   *CtecsListInstanceBackupPolicyBindInstancesApi
	CtecsQueryUpgradeOrderPriceV41Api               *CtecsQueryUpgradeOrderPriceV41Api
	CtecsQueryRenewOrderPriceV41Api                 *CtecsQueryRenewOrderPriceV41Api
	CtecsQueryNewOrderPriceV42Api                   *CtecsQueryNewOrderPriceV42Api
	CtecsListInstanceBackupPolicyApi                *CtecsListInstanceBackupPolicyApi
	CtecsInstanceBackupPolicyUnbindRepoApi          *CtecsInstanceBackupPolicyUnbindRepoApi
	CtecsInstanceBackupPolicyBindRepoApi            *CtecsInstanceBackupPolicyBindRepoApi
	CtecsInstanceBackupPolicyUnbindInstancesApi     *CtecsInstanceBackupPolicyUnbindInstancesApi
	CtecsInstanceBackupPolicyBindInstancesApi       *CtecsInstanceBackupPolicyBindInstancesApi
	CtecsExecuteInstanceBackupPolicyApi             *CtecsExecuteInstanceBackupPolicyApi
	CtecsUpdateInstanceBackupPolicyApi              *CtecsUpdateInstanceBackupPolicyApi
	CtecsDeleteInstanceBackupPolicyApi              *CtecsDeleteInstanceBackupPolicyApi
	CtecsCreateInstanceBackupPolicyApi              *CtecsCreateInstanceBackupPolicyApi
	CtecsUpgradeInstanceBackupRepoApi               *CtecsUpgradeInstanceBackupRepoApi
	CtecsCreateInstanceBackupRepoApi                *CtecsCreateInstanceBackupRepoApi
	CtecsListInstanceBackupRepoApi                  *CtecsListInstanceBackupRepoApi
	CtecsRenewInstanceBackupRepoApi                 *CtecsRenewInstanceBackupRepoApi
	CtecsDeleteInstanceBackupRepoApi                *CtecsDeleteInstanceBackupRepoApi
	CtecsCreateEipV41Api                            *CtecsCreateEipV41Api
	CtecsStatisticsInstanceBackupApi                *CtecsStatisticsInstanceBackupApi
	CtecsDeleteEipV41Api                            *CtecsDeleteEipV41Api
	CtecsQueryVmNetworkHistoryMetricDataV41Api      *CtecsQueryVmNetworkHistoryMetricDataV41Api
	CtecsQueryVmDiskHistoryMetricDataV41Api         *CtecsQueryVmDiskHistoryMetricDataV41Api
	CtecsQueryVmMemoryHistoryMetricDataV41Api       *CtecsQueryVmMemoryHistoryMetricDataV41Api
	CtecsQueryVmCpuHistoryMetricDataV41Api          *CtecsQueryVmCpuHistoryMetricDataV41Api
	CtecsQueryVmNetworkLatestMetricDataV41Api       *CtecsQueryVmNetworkLatestMetricDataV41Api
	CtecsQueryVmDiskLatestMetricDataV41Api          *CtecsQueryVmDiskLatestMetricDataV41Api
	CtecsQueryVmMemoryLatestMetricDataV41Api        *CtecsQueryVmMemoryLatestMetricDataV41Api
	CtecsQueryVmCpuLatestMetricDataV41Api           *CtecsQueryVmCpuLatestMetricDataV41Api
	CtecsBatchDeleteMetadataV41Api                  *CtecsBatchDeleteMetadataV41Api
	CtecsQueryInstanceStatisticsV41Api              *CtecsQueryInstanceStatisticsV41Api
	CtecsQueryUpgradeOrderPriceV42Api               *CtecsQueryUpgradeOrderPriceV42Api
	CtecsQueryRenewOrderPriceV42Api                 *CtecsQueryRenewOrderPriceV42Api
	CtecsQueryNewOrderPriceV41Api                   *CtecsQueryNewOrderPriceV41Api
	CtecsQueryJobInfoV41Api                         *CtecsQueryJobInfoV41Api
	CtecsGetEcsFlavorsApi                           *CtecsGetEcsFlavorsApi
	CtecsQuerySummaryInRegionV41Api                 *CtecsQuerySummaryInRegionV41Api
	CtecsQueryZonesInRegionV41Api                   *CtecsQueryZonesInRegionV41Api
	CtecsQueryProductsInRegionV41Api                *CtecsQueryProductsInRegionV41Api
	CtecsListRegionsV41Api                          *CtecsListRegionsV41Api
	CtecsUsageInstanceBackupApi                     *CtecsUsageInstanceBackupApi
	CtecsRestoreInstanceBackupApi                   *CtecsRestoreInstanceBackupApi
	CtecsDeleteInstanceBackupApi                    *CtecsDeleteInstanceBackupApi
	CtecsRestoreSnapshotV41Api                      *CtecsRestoreSnapshotV41Api
	CtecsDeleteSnapshotV41Api                       *CtecsDeleteSnapshotV41Api
	CtecsDeleteKeypairV41Api                        *CtecsDeleteKeypairV41Api
	CtecsDescribeSecurityGroupAttributeV41Api       *CtecsDescribeSecurityGroupAttributeV41Api
	CtecsEcsleaveSecurityGroupV41Api                *CtecsEcsleaveSecurityGroupV41Api
	CtecsEcsJoinSecurityGroupV41Api                 *CtecsEcsJoinSecurityGroupV41Api
	CtecsRevokeSecurityGroupEgressV41Api            *CtecsRevokeSecurityGroupEgressV41Api
	CtecsRevokeSecurityGroupIngressV41Api           *CtecsRevokeSecurityGroupIngressV41Api
	CtecsModifySecurityGroupEgressV41Api            *CtecsModifySecurityGroupEgressV41Api
	CtecsModifySecurityGroupIngressV41Api           *CtecsModifySecurityGroupIngressV41Api
	CtecsCreateSecurityGroupEgressV41Api            *CtecsCreateSecurityGroupEgressV41Api
	CtecsCreateSecurityGroupIngressV41Api           *CtecsCreateSecurityGroupIngressV41Api
	CtecsDeleteSecurityGroupV41Api                  *CtecsDeleteSecurityGroupV41Api
	CtecsQuerySecurityGroupsV41Api                  *CtecsQuerySecurityGroupsV41Api
	CtecsCreateSecurityGroupV41Api                  *CtecsCreateSecurityGroupV41Api
	CtecsBatchDeleteInstancesApi                    *CtecsBatchDeleteInstancesApi
	CtecsQueryAsyncResultV41Api                     *CtecsQueryAsyncResultV41Api
	CtecsPortsDetachInstanceV41Api                  *CtecsPortsDetachInstanceV41Api
	CtecsPortsAttachInstanceV41Api                  *CtecsPortsAttachInstanceV41Api
	CtecsPortsUnassignIpv6V41Api                    *CtecsPortsUnassignIpv6V41Api
	CtecsPortsAssignIpv6V41Api                      *CtecsPortsAssignIpv6V41Api
	CtecsPortsUnassignSecondaryprivateipsV41Api     *CtecsPortsUnassignSecondaryprivateipsV41Api
	CtecsPortsAssignSecondaryprivateipsV41Api       *CtecsPortsAssignSecondaryprivateipsV41Api
	CtecsUpdatePortsV41Api                          *CtecsUpdatePortsV41Api
	CtecsDeletePortsV41Api                          *CtecsDeletePortsV41Api
	CtecsCreatePortsV41Api                          *CtecsCreatePortsV41Api
	CtecsShowPortsV41Api                            *CtecsShowPortsV41Api
	CtecsListPortsV41Api                            *CtecsListPortsV41Api
	CtecsUpdateAffinityGroupApi                     *CtecsUpdateAffinityGroupApi
	CtecsDeleteAffinityGroupApi                     *CtecsDeleteAffinityGroupApi
}

func NewApis(endpointUrl string, client *core.CtyunClient) *Apis {
	client.RegisterEndpoint(core.Endpoint{
		Name: EndpointName,
		Url:  endpointUrl,
	})
	return &Apis{
		CtecsDeleteInstanceAndRelatedResourceApi:        NewCtecsDeleteInstanceAndRelatedResourceApi(client),
		CtecsRecoverUnsubscribeInstanceV41Api:           NewCtecsRecoverUnsubscribeInstanceV41Api(client),
		CtecsGetCaAgentApi:                              NewCtecsGetCaAgentApi(client),
		CtecsDescribeSendFileResultsApi:                 NewCtecsDescribeSendFileResultsApi(client),
		CtecsSendFileApi:                                NewCtecsSendFileApi(client),
		CtecsGetCommandApi:                              NewCtecsGetCommandApi(client),
		CtecsGetCommandsApi:                             NewCtecsGetCommandsApi(client),
		CtecsInvokeCommandApi:                           NewCtecsInvokeCommandApi(client),
		CtecsDeleteCommandApi:                           NewCtecsDeleteCommandApi(client),
		CtecsModifyCommandApi:                           NewCtecsModifyCommandApi(client),
		CtecsCreateCommandApi:                           NewCtecsCreateCommandApi(client),
		CtecsCreateSameConfigInstancesApi:               NewCtecsCreateSameConfigInstancesApi(client),
		CtecsBatchOperateEcsLabelV41Api:                 NewCtecsBatchOperateEcsLabelV41Api(client),
		CtecsUpdateEcsLabelV41Api:                       NewCtecsUpdateEcsLabelV41Api(client),
		CtecsOperateAllInstancesV41Api:                  NewCtecsOperateAllInstancesV41Api(client),
		CtecsLiteEcsCreateVolumeApi:                     NewCtecsLiteEcsCreateVolumeApi(client),
		CtecsListBackupTaskApi:                          NewCtecsListBackupTaskApi(client),
		CtecsListUpdateSpecFlavorV41Api:                 NewCtecsListUpdateSpecFlavorV41Api(client),
		CtecsRebuildLiteInstanceApi:                     NewCtecsRebuildLiteInstanceApi(client),
		CtecsEcsSnapshotTaskListApi:                     NewCtecsEcsSnapshotTaskListApi(client),
		CtecsLiteEcsUnsubscribeVolumeApi:                NewCtecsLiteEcsUnsubscribeVolumeApi(client),
		CtecsEcsSnapshotBatchDeleteApi:                  NewCtecsEcsSnapshotBatchDeleteApi(client),
		CtecsDestroyInstanceApi:                         NewCtecsDestroyInstanceApi(client),
		CtecsEcsDeleteDelegateApi:                       NewCtecsEcsDeleteDelegateApi(client),
		CtecsEcsAttachDelegateApi:                       NewCtecsEcsAttachDelegateApi(client),
		CtecsCloudAssistantDescribeInvocationResultsApi: NewCtecsCloudAssistantDescribeInvocationResultsApi(client),
		CtecsCloudAssistantRunCommandApi:                NewCtecsCloudAssistantRunCommandApi(client),
		CtecsListGpuDriverV41Api:                        NewCtecsListGpuDriverV41Api(client),
		CtecsBatchShelveInstancesApi:                    NewCtecsBatchShelveInstancesApi(client),
		CtecsShelveInstanceApi:                          NewCtecsShelveInstanceApi(client),
		CtecsAffinityGroupUnbindInstancesApi:            NewCtecsAffinityGroupUnbindInstancesApi(client),
		CtecsInstanceDetachSfsV41Api:                    NewCtecsInstanceDetachSfsV41Api(client),
		CtecsInstanceAttachSfsV41Api:                    NewCtecsInstanceAttachSfsV41Api(client),
		CtecsListSfsInstanceV41Api:                      NewCtecsListSfsInstanceV41Api(client),
		CtecsListInstanceSfsV41Api:                      NewCtecsListInstanceSfsV41Api(client),
		CtecsUpdateDeletionProtectionV41Api:             NewCtecsUpdateDeletionProtectionV41Api(client),
		CtecsLiveResizeInstanceV41Api:                   NewCtecsLiveResizeInstanceV41Api(client),
		CtecsListLiveResizeFlavorV41Api:                 NewCtecsListLiveResizeFlavorV41Api(client),
		CtecsQuerySnapshotStatisticsV41Api:              NewCtecsQuerySnapshotStatisticsV41Api(client),
		CtecsShowVolumeV41Api:                           NewCtecsShowVolumeV41Api(client),
		CtecsListFlavorLiteInstanceV41Api:               NewCtecsListFlavorLiteInstanceV41Api(client),
		CtecsDeleteVolumeV41Api:                         NewCtecsDeleteVolumeV41Api(client),
		CtecsAttachVolumeV41Api:                         NewCtecsAttachVolumeV41Api(client),
		CtecsExtendVolumeV41Api:                         NewCtecsExtendVolumeV41Api(client),
		CtecsDetachVolumeV41Api:                         NewCtecsDetachVolumeV41Api(client),
		CtecsUpdateSpecLiteInstanceV41Api:               NewCtecsUpdateSpecLiteInstanceV41Api(client),
		CtecsResetLiteInstancePasswordV41Api:            NewCtecsResetLiteInstancePasswordV41Api(client),
		CtecsRebootLiteInstanceV41Api:                   NewCtecsRebootLiteInstanceV41Api(client),
		CtecsStopLiteInstanceV41Api:                     NewCtecsStopLiteInstanceV41Api(client),
		CtecsStartLiteInstanceV41Api:                    NewCtecsStartLiteInstanceV41Api(client),
		CtecsDetailsVncLiteInstanceV41Api:               NewCtecsDetailsVncLiteInstanceV41Api(client),
		CtecsUnsubscribeLiteInstanceV41Api:              NewCtecsUnsubscribeLiteInstanceV41Api(client),
		CtecsResubscribeLiteInstanceV41Api:              NewCtecsResubscribeLiteInstanceV41Api(client),
		CtecsDetailsLiteInstanceV41Api:                  NewCtecsDetailsLiteInstanceV41Api(client),
		CtecsListLiteInstanceV41Api:                     NewCtecsListLiteInstanceV41Api(client),
		CtecsCreateLiteInstanceV41Api:                   NewCtecsCreateLiteInstanceV41Api(client),
		CtecsUpdateVolumeV41Api:                         NewCtecsUpdateVolumeV41Api(client),
		CtecsCreateVolumeV41Api:                         NewCtecsCreateVolumeV41Api(client),
		CtecsQueryOrderUuidV41Api:                       NewCtecsQueryOrderUuidV41Api(client),
		CtecsQueryCustomerQuotasInRegionV41Api:          NewCtecsQueryCustomerQuotasInRegionV41Api(client),
		CtecsQueryCustomerResourcesInRegionV41Api:       NewCtecsQueryCustomerResourcesInRegionV41Api(client),
		CtecsDeleteSnapshotpolicyV41Api:                 NewCtecsDeleteSnapshotpolicyV41Api(client),
		CtecsQueryInstancIDV41Api:                       NewCtecsQueryInstancIDV41Api(client),
		CtecsExecuteSnapshotPolicyV41Api:                NewCtecsExecuteSnapshotPolicyV41Api(client),
		CtecsListInstanceSnapshotPolicyV41Api:           NewCtecsListInstanceSnapshotPolicyV41Api(client),
		CtecsDetailsSnapshotpolicyV41Api:                NewCtecsDetailsSnapshotpolicyV41Api(client),
		CtecsListSnapshotPolicyV41Api:                   NewCtecsListSnapshotPolicyV41Api(client),
		CtecsListSnapshotPolicyTaskV41Api:               NewCtecsListSnapshotPolicyTaskV41Api(client),
		CtecsSnapshotPolicyUnbindInstancesV41Api:        NewCtecsSnapshotPolicyUnbindInstancesV41Api(client),
		CtecsSnapshotpolicyBindInstanceV41Api:           NewCtecsSnapshotpolicyBindInstanceV41Api(client),
		CtecsEnableSnapshotPolicyV41Api:                 NewCtecsEnableSnapshotPolicyV41Api(client),
		CtecsCreateSnapshotpolicyV41Api:                 NewCtecsCreateSnapshotpolicyV41Api(client),
		CtecsDisableSnapshotPolicyV41Api:                NewCtecsDisableSnapshotPolicyV41Api(client),
		CtecsUpdateSnapshotPolicyV41Api:                 NewCtecsUpdateSnapshotPolicyV41Api(client),
		CtecsQueryJobV41Api:                             NewCtecsQueryJobV41Api(client),
		CtecsDescribeInstancesApi:                       NewCtecsDescribeInstancesApi(client),
		CtecsCreateMetadataV41Api:                       NewCtecsCreateMetadataV41Api(client),
		CtecsListInstanceBackupV41Api:                   NewCtecsListInstanceBackupV41Api(client),
		CtecsDetailsInstanceBackupV41Api:                NewCtecsDetailsInstanceBackupV41Api(client),
		CtecsCreateSnapshotV41Api:                       NewCtecsCreateSnapshotV41Api(client),
		CtecsUpdateSnapshotV41Api:                       NewCtecsUpdateSnapshotV41Api(client),
		CtecsBatchUpdateSnapshotV41Api:                  NewCtecsBatchUpdateSnapshotV41Api(client),
		CtecsQuerySnapshotListV41Api:                    NewCtecsQuerySnapshotListV41Api(client),
		CtecsQuerySnapshotStatusV41Api:                  NewCtecsQuerySnapshotStatusV41Api(client),
		CtecsQuerySnapshotDetailsV41Api:                 NewCtecsQuerySnapshotDetailsV41Api(client),
		CtecsImportKeypairV41Api:                        NewCtecsImportKeypairV41Api(client),
		CtecsCreateKeypairV41Api:                        NewCtecsCreateKeypairV41Api(client),
		CtecsStatusInstanceBackupV41Api:                 NewCtecsStatusInstanceBackupV41Api(client),
		CtecsDetailsKeypairV41Api:                       NewCtecsDetailsKeypairV41Api(client),
		CtecsKeypairAttachInstanceV41Api:                NewCtecsKeypairAttachInstanceV41Api(client),
		CtecsInstanceDetachKeypairV41Api:                NewCtecsInstanceDetachKeypairV41Api(client),
		CtecsUpdateInstanceBackupV41Api:                 NewCtecsUpdateInstanceBackupV41Api(client),
		CtecsBackupBatchUpdateApi:                       NewCtecsBackupBatchUpdateApi(client),
		CtecsCreateInstanceBackupV41Api:                 NewCtecsCreateInstanceBackupV41Api(client),
		CtecsDetailsBackupInstanceV41Api:                NewCtecsDetailsBackupInstanceV41Api(client),
		CtecsTotalInstanceBackupVolumeSizeV41Api:        NewCtecsTotalInstanceBackupVolumeSizeV41Api(client),
		CtecsListFlavorV41Api:                           NewCtecsListFlavorV41Api(client),
		CtecsListFlavorFamiliesV41Api:                   NewCtecsListFlavorFamiliesV41Api(client),
		CtecsListInstanceFlavorFamiliesV41Api:           NewCtecsListInstanceFlavorFamiliesV41Api(client),
		CtecsListAffinityGroupV41Api:                    NewCtecsListAffinityGroupV41Api(client),
		CtecsDeleteMetadataV41Api:                       NewCtecsDeleteMetadataV41Api(client),
		CtecsUpdateMetadataV41Api:                       NewCtecsUpdateMetadataV41Api(client),
		CtecsGetAffinityGroupV41Api:                     NewCtecsGetAffinityGroupV41Api(client),
		CtecsListAffinityGroupInstanceV41Api:            NewCtecsListAffinityGroupInstanceV41Api(client),
		CtecsDetailsMetadataV41Api:                      NewCtecsDetailsMetadataV41Api(client),
		CtecsCreateAffinityGroupV41Api:                  NewCtecsCreateAffinityGroupV41Api(client),
		CtecsAffinityGroupbindInstanceV41Api:            NewCtecsAffinityGroupbindInstanceV41Api(client),
		CtecsDescribeAvailabilityZonesV41Api:            NewCtecsDescribeAvailabilityZonesV41Api(client),
		CtecsAffinityGroupUnbindInstanceV41Api:          NewCtecsAffinityGroupUnbindInstanceV41Api(client),
		CtecsAffinityGroupbindInstanceCheckV41Api:       NewCtecsAffinityGroupbindInstanceCheckV41Api(client),
		CtecsQueryUserdataDetailsV41Api:                 NewCtecsQueryUserdataDetailsV41Api(client),
		CtecsDetailsInstanceV41Api:                      NewCtecsDetailsInstanceV41Api(client),
		CtecsListInstanceV41Api:                         NewCtecsListInstanceV41Api(client),
		CtecsListInstanceStatusV41Api:                   NewCtecsListInstanceStatusV41Api(client),
		CtecsListFixedIpV41Api:                          NewCtecsListFixedIpV41Api(client),
		CtecsBatchRebuildInstancesV41Api:                NewCtecsBatchRebuildInstancesV41Api(client),
		CtecsBatchRebootInstancesV41Api:                 NewCtecsBatchRebootInstancesV41Api(client),
		CtecsBatchStopInstancesV41Api:                   NewCtecsBatchStopInstancesV41Api(client),
		CtecsBatchStartInstancesV41Api:                  NewCtecsBatchStartInstancesV41Api(client),
		CtecsRebuildInstanceV41Api:                      NewCtecsRebuildInstanceV41Api(client),
		CtecsRebootInstanceV41Api:                       NewCtecsRebootInstanceV41Api(client),
		CtecsStopInstanceV41Api:                         NewCtecsStopInstanceV41Api(client),
		CtecsStartInstanceV41Api:                        NewCtecsStartInstanceV41Api(client),
		CtecsUpdateNetworkSpecV41Api:                    NewCtecsUpdateNetworkSpecV41Api(client),
		CtecsInstanceAttachShareInterfaceV41Api:         NewCtecsInstanceAttachShareInterfaceV41Api(client),
		CtecsUpdateFlavorSpecV41Api:                     NewCtecsUpdateFlavorSpecV41Api(client),
		CtecsUpdateInstanceSpecV41Api:                   NewCtecsUpdateInstanceSpecV41Api(client),
		CtecsGetVolumeStatisticsV41Api:                  NewCtecsGetVolumeStatisticsV41Api(client),
		CtecsQueryVolumeListV41Api:                      NewCtecsQueryVolumeListV41Api(client),
		CtecsQueryVncDetailsV41Api:                      NewCtecsQueryVncDetailsV41Api(client),
		CtecsBatchUpdateInstancesPasswordV41Api:         NewCtecsBatchUpdateInstancesPasswordV41Api(client),
		CtecsResetInstancePasswordV41Api:                NewCtecsResetInstancePasswordV41Api(client),
		CtecsBatchUpdateInstancesV41Api:                 NewCtecsBatchUpdateInstancesV41Api(client),
		CtecsUpdateInstanceV41Api:                       NewCtecsUpdateInstanceV41Api(client),
		CtecsUnsubscribeInstanceV41Api:                  NewCtecsUnsubscribeInstanceV41Api(client),
		CtecsResubscribeInstanceV41Api:                  NewCtecsResubscribeInstanceV41Api(client),
		CtecsBatchCreateInstancesV41Api:                 NewCtecsBatchCreateInstancesV41Api(client),
		CtecsCreateInstanceV41Api:                       NewCtecsCreateInstanceV41Api(client),
		CtecsCloneInstanceApi:                           NewCtecsCloneInstanceApi(client),
		CtecsCreateInstanceByInstanceBackupApi:          NewCtecsCreateInstanceByInstanceBackupApi(client),
		CtecsSnapshotCreateInstanceV41Api:               NewCtecsSnapshotCreateInstanceV41Api(client),
		CtecsListInstanceBackupPolicyBindInstancesApi:   NewCtecsListInstanceBackupPolicyBindInstancesApi(client),
		CtecsQueryUpgradeOrderPriceV41Api:               NewCtecsQueryUpgradeOrderPriceV41Api(client),
		CtecsQueryRenewOrderPriceV41Api:                 NewCtecsQueryRenewOrderPriceV41Api(client),
		CtecsQueryNewOrderPriceV42Api:                   NewCtecsQueryNewOrderPriceV42Api(client),
		CtecsListInstanceBackupPolicyApi:                NewCtecsListInstanceBackupPolicyApi(client),
		CtecsInstanceBackupPolicyUnbindRepoApi:          NewCtecsInstanceBackupPolicyUnbindRepoApi(client),
		CtecsInstanceBackupPolicyBindRepoApi:            NewCtecsInstanceBackupPolicyBindRepoApi(client),
		CtecsInstanceBackupPolicyUnbindInstancesApi:     NewCtecsInstanceBackupPolicyUnbindInstancesApi(client),
		CtecsInstanceBackupPolicyBindInstancesApi:       NewCtecsInstanceBackupPolicyBindInstancesApi(client),
		CtecsExecuteInstanceBackupPolicyApi:             NewCtecsExecuteInstanceBackupPolicyApi(client),
		CtecsUpdateInstanceBackupPolicyApi:              NewCtecsUpdateInstanceBackupPolicyApi(client),
		CtecsDeleteInstanceBackupPolicyApi:              NewCtecsDeleteInstanceBackupPolicyApi(client),
		CtecsCreateInstanceBackupPolicyApi:              NewCtecsCreateInstanceBackupPolicyApi(client),
		CtecsUpgradeInstanceBackupRepoApi:               NewCtecsUpgradeInstanceBackupRepoApi(client),
		CtecsCreateInstanceBackupRepoApi:                NewCtecsCreateInstanceBackupRepoApi(client),
		CtecsListInstanceBackupRepoApi:                  NewCtecsListInstanceBackupRepoApi(client),
		CtecsRenewInstanceBackupRepoApi:                 NewCtecsRenewInstanceBackupRepoApi(client),
		CtecsDeleteInstanceBackupRepoApi:                NewCtecsDeleteInstanceBackupRepoApi(client),
		CtecsCreateEipV41Api:                            NewCtecsCreateEipV41Api(client),
		CtecsStatisticsInstanceBackupApi:                NewCtecsStatisticsInstanceBackupApi(client),
		CtecsDeleteEipV41Api:                            NewCtecsDeleteEipV41Api(client),
		CtecsQueryVmNetworkHistoryMetricDataV41Api:      NewCtecsQueryVmNetworkHistoryMetricDataV41Api(client),
		CtecsQueryVmDiskHistoryMetricDataV41Api:         NewCtecsQueryVmDiskHistoryMetricDataV41Api(client),
		CtecsQueryVmMemoryHistoryMetricDataV41Api:       NewCtecsQueryVmMemoryHistoryMetricDataV41Api(client),
		CtecsQueryVmCpuHistoryMetricDataV41Api:          NewCtecsQueryVmCpuHistoryMetricDataV41Api(client),
		CtecsQueryVmNetworkLatestMetricDataV41Api:       NewCtecsQueryVmNetworkLatestMetricDataV41Api(client),
		CtecsQueryVmDiskLatestMetricDataV41Api:          NewCtecsQueryVmDiskLatestMetricDataV41Api(client),
		CtecsQueryVmMemoryLatestMetricDataV41Api:        NewCtecsQueryVmMemoryLatestMetricDataV41Api(client),
		CtecsQueryVmCpuLatestMetricDataV41Api:           NewCtecsQueryVmCpuLatestMetricDataV41Api(client),
		CtecsBatchDeleteMetadataV41Api:                  NewCtecsBatchDeleteMetadataV41Api(client),
		CtecsQueryInstanceStatisticsV41Api:              NewCtecsQueryInstanceStatisticsV41Api(client),
		CtecsQueryUpgradeOrderPriceV42Api:               NewCtecsQueryUpgradeOrderPriceV42Api(client),
		CtecsQueryRenewOrderPriceV42Api:                 NewCtecsQueryRenewOrderPriceV42Api(client),
		CtecsQueryNewOrderPriceV41Api:                   NewCtecsQueryNewOrderPriceV41Api(client),
		CtecsQueryJobInfoV41Api:                         NewCtecsQueryJobInfoV41Api(client),
		CtecsGetEcsFlavorsApi:                           NewCtecsGetEcsFlavorsApi(client),
		CtecsQuerySummaryInRegionV41Api:                 NewCtecsQuerySummaryInRegionV41Api(client),
		CtecsQueryZonesInRegionV41Api:                   NewCtecsQueryZonesInRegionV41Api(client),
		CtecsQueryProductsInRegionV41Api:                NewCtecsQueryProductsInRegionV41Api(client),
		CtecsListRegionsV41Api:                          NewCtecsListRegionsV41Api(client),
		CtecsUsageInstanceBackupApi:                     NewCtecsUsageInstanceBackupApi(client),
		CtecsRestoreInstanceBackupApi:                   NewCtecsRestoreInstanceBackupApi(client),
		CtecsDeleteInstanceBackupApi:                    NewCtecsDeleteInstanceBackupApi(client),
		CtecsRestoreSnapshotV41Api:                      NewCtecsRestoreSnapshotV41Api(client),
		CtecsDeleteSnapshotV41Api:                       NewCtecsDeleteSnapshotV41Api(client),
		CtecsDeleteKeypairV41Api:                        NewCtecsDeleteKeypairV41Api(client),
		CtecsDescribeSecurityGroupAttributeV41Api:       NewCtecsDescribeSecurityGroupAttributeV41Api(client),
		CtecsEcsleaveSecurityGroupV41Api:                NewCtecsEcsleaveSecurityGroupV41Api(client),
		CtecsEcsJoinSecurityGroupV41Api:                 NewCtecsEcsJoinSecurityGroupV41Api(client),
		CtecsRevokeSecurityGroupEgressV41Api:            NewCtecsRevokeSecurityGroupEgressV41Api(client),
		CtecsRevokeSecurityGroupIngressV41Api:           NewCtecsRevokeSecurityGroupIngressV41Api(client),
		CtecsModifySecurityGroupEgressV41Api:            NewCtecsModifySecurityGroupEgressV41Api(client),
		CtecsModifySecurityGroupIngressV41Api:           NewCtecsModifySecurityGroupIngressV41Api(client),
		CtecsCreateSecurityGroupEgressV41Api:            NewCtecsCreateSecurityGroupEgressV41Api(client),
		CtecsCreateSecurityGroupIngressV41Api:           NewCtecsCreateSecurityGroupIngressV41Api(client),
		CtecsDeleteSecurityGroupV41Api:                  NewCtecsDeleteSecurityGroupV41Api(client),
		CtecsQuerySecurityGroupsV41Api:                  NewCtecsQuerySecurityGroupsV41Api(client),
		CtecsCreateSecurityGroupV41Api:                  NewCtecsCreateSecurityGroupV41Api(client),
		CtecsBatchDeleteInstancesApi:                    NewCtecsBatchDeleteInstancesApi(client),
		CtecsQueryAsyncResultV41Api:                     NewCtecsQueryAsyncResultV41Api(client),
		CtecsPortsDetachInstanceV41Api:                  NewCtecsPortsDetachInstanceV41Api(client),
		CtecsPortsAttachInstanceV41Api:                  NewCtecsPortsAttachInstanceV41Api(client),
		CtecsPortsUnassignIpv6V41Api:                    NewCtecsPortsUnassignIpv6V41Api(client),
		CtecsPortsAssignIpv6V41Api:                      NewCtecsPortsAssignIpv6V41Api(client),
		CtecsPortsUnassignSecondaryprivateipsV41Api:     NewCtecsPortsUnassignSecondaryprivateipsV41Api(client),
		CtecsPortsAssignSecondaryprivateipsV41Api:       NewCtecsPortsAssignSecondaryprivateipsV41Api(client),
		CtecsUpdatePortsV41Api:                          NewCtecsUpdatePortsV41Api(client),
		CtecsDeletePortsV41Api:                          NewCtecsDeletePortsV41Api(client),
		CtecsCreatePortsV41Api:                          NewCtecsCreatePortsV41Api(client),
		CtecsShowPortsV41Api:                            NewCtecsShowPortsV41Api(client),
		CtecsListPortsV41Api:                            NewCtecsListPortsV41Api(client),
		CtecsUpdateAffinityGroupApi:                     NewCtecsUpdateAffinityGroupApi(client),
		CtecsDeleteAffinityGroupApi:                     NewCtecsDeleteAffinityGroupApi(client),
	}
}
