package ctzos

import (
	"github.com/ctyun-it/terraform-provider-ctyun/internal/core/core"
)

const EndpointName = "zos"

type Apis struct {
	ZosPutUserEventBridgeApi                     *ZosPutUserEventBridgeApi
	ZosGetUserEventBridgeApi                     *ZosGetUserEventBridgeApi
	ZosDeleteZMSMigrationTaskApi                 *ZosDeleteZMSMigrationTaskApi
	ZosResumeZMSMigrationTaskApi                 *ZosResumeZMSMigrationTaskApi
	ZosPauseZMSMigrationTaskApi                  *ZosPauseZMSMigrationTaskApi
	ZosRetryZMSMigrationTaskApi                  *ZosRetryZMSMigrationTaskApi
	ZosGetFailedObjectsListofZMSMigrationTaskApi *ZosGetFailedObjectsListofZMSMigrationTaskApi
	ZosGetZMSMigrationTaskDetailApi              *ZosGetZMSMigrationTaskDetailApi
	ZosGetZMSMigrationTaskListApi                *ZosGetZMSMigrationTaskListApi
	ZosCreateZMSMigrationTaskApi                 *ZosCreateZMSMigrationTaskApi
	ZosDeleteZMSAssessmentTaskApi                *ZosDeleteZMSAssessmentTaskApi
	ZosResumeZMSAssessmentTaskApi                *ZosResumeZMSAssessmentTaskApi
	ZosPauseZMSAssessmentTaskApi                 *ZosPauseZMSAssessmentTaskApi
	ZosStartZMSAssessmentTaskApi                 *ZosStartZMSAssessmentTaskApi
	ZosGetZMSAssessmentTaskDetailApi             *ZosGetZMSAssessmentTaskDetailApi
	ZosGetZMSAssessmentTaskListApi               *ZosGetZMSAssessmentTaskListApi
	ZosCreateZMSAssessmentTaskApi                *ZosCreateZMSAssessmentTaskApi
	ZosPutBucketEventBridgeApi                   *ZosPutBucketEventBridgeApi
	ZosListRegionsApi                            *ZosListRegionsApi
	ZosQueryNewOrderPriceApi                     *ZosQueryNewOrderPriceApi
	ZosGetOssServiceStatusApi                    *ZosGetOssServiceStatusApi
	ZosDeletePolicyApi                           *ZosDeletePolicyApi
	ZosPolicyDetailApi                           *ZosPolicyDetailApi
	ZosDeletePolicy1Api                          *ZosDeletePolicy1Api
	ZosPutPolicyApi                              *ZosPutPolicyApi
	ZosListPoliciesApi                           *ZosListPoliciesApi
	ZosRoleDetailApi                             *ZosRoleDetailApi
	ZosDeleteRoleApi                             *ZosDeleteRoleApi
	ZosListRolesApi                              *ZosListRolesApi
	ZosBindRolePolicyApi                         *ZosBindRolePolicyApi
	ZosCreatePolicyApi                           *ZosCreatePolicyApi
	ZosCreateRoleApi                             *ZosCreateRoleApi
	ZosGetBucketStatisticsApi                    *ZosGetBucketStatisticsApi
	ZosPutBucketQuotaApi                         *ZosPutBucketQuotaApi
	ZosGetEndpointApi                            *ZosGetEndpointApi
	ZosGetFragmentNumApi                         *ZosGetFragmentNumApi
	ZosPutObjectNumApi                           *ZosPutObjectNumApi
	ZosPutObjectStorageTypeApi                   *ZosPutObjectStorageTypeApi
	ZosUnfreezeObjectApi                         *ZosUnfreezeObjectApi
	ZosListAllPartsApi                           *ZosListAllPartsApi
	ZosDeleteDirectoryApi                        *ZosDeleteDirectoryApi
	ZosCreateDirectoryApi                        *ZosCreateDirectoryApi
	ZosListObjectVersionsApi                     *ZosListObjectVersionsApi
	ZosCompleteMultipartUploadApi                *ZosCompleteMultipartUploadApi
	ZosListPartsApi                              *ZosListPartsApi
	ZosGenerateObjectUploadLinkApi               *ZosGenerateObjectUploadLinkApi
	ZosGetKeysApi                                *ZosGetKeysApi
	ZosPutObjectHeaderApi                        *ZosPutObjectHeaderApi
	ZosDeleteObjectTaggingApi                    *ZosDeleteObjectTaggingApi
	ZosGetObjectTaggingApi                       *ZosGetObjectTaggingApi
	ZosPutObjectTaggingApi                       *ZosPutObjectTaggingApi
	ZosGetObjectAclApi                           *ZosGetObjectAclApi
	ZosPutObjectAclApi                           *ZosPutObjectAclApi
	ZosAbortMultipartUploadApi                   *ZosAbortMultipartUploadApi
	ZosListMultipartUploadsApi                   *ZosListMultipartUploadsApi
	ZosCreateMultipartUploadApi                  *ZosCreateMultipartUploadApi
	ZosHeadObjectApi                             *ZosHeadObjectApi
	ZosGenerateObjectDownloadLinkApi             *ZosGenerateObjectDownloadLinkApi
	ZosDeleteObjectsApi                          *ZosDeleteObjectsApi
	ZosCopyObjectApi                             *ZosCopyObjectApi
	ZosDeleteObjectApi                           *ZosDeleteObjectApi
	ZosListObjectsApi                            *ZosListObjectsApi
	ZosGetBucketInfoApi                          *ZosGetBucketInfoApi
	ZosPutBucketVersioningApi                    *ZosPutBucketVersioningApi
	ZosDeleteBucketLifecycleConfApi              *ZosDeleteBucketLifecycleConfApi
	ZosPutBucketLifecycleConfApi                 *ZosPutBucketLifecycleConfApi
	ZosPutBucketAclApi                           *ZosPutBucketAclApi
	ZosDeleteBucketReplicationApi                *ZosDeleteBucketReplicationApi
	ZosPutBucketLoggingApi                       *ZosPutBucketLoggingApi
	ZosDeleteBucketLoggingApi                    *ZosDeleteBucketLoggingApi
	ZosGetBucketLocationApi                      *ZosGetBucketLocationApi
	ZosDeleteBucketCorsApi                       *ZosDeleteBucketCorsApi
	ZosPutBucketCorsApi                          *ZosPutBucketCorsApi
	ZosGetBucketCorsApi                          *ZosGetBucketCorsApi
	ZosHeadBucketApi                             *ZosHeadBucketApi
	ZosDeleteBucketApi                           *ZosDeleteBucketApi
	ZosListBucketsApi                            *ZosListBucketsApi
	ZosCreateBucketApi                           *ZosCreateBucketApi
	ZosGetBucketEncryptionApi                    *ZosGetBucketEncryptionApi
	ZosPutBucketEncryptionApi                    *ZosPutBucketEncryptionApi
	ZosDeleteBucketEncryptionApi                 *ZosDeleteBucketEncryptionApi
	ZosDeleteBucketTaggingApi                    *ZosDeleteBucketTaggingApi
	ZosPutBucketTaggingApi                       *ZosPutBucketTaggingApi
	ZosDeleteBucketPolicyApi                     *ZosDeleteBucketPolicyApi
	ZosPutBucketPolicyApi                        *ZosPutBucketPolicyApi
	ZosGetBucketTaggingApi                       *ZosGetBucketTaggingApi
	ZosGetBucketLoggingApi                       *ZosGetBucketLoggingApi
	ZosGetBucketPolicyApi                        *ZosGetBucketPolicyApi
	ZosGetBucketVersioningApi                    *ZosGetBucketVersioningApi
	ZosGetBucketLifecycleConfApi                 *ZosGetBucketLifecycleConfApi
	ZosGetBucketAclApi                           *ZosGetBucketAclApi
	ZosGetObjectRetentionApi                     *ZosGetObjectRetentionApi
	ZosPutObjectRetentionApi                     *ZosPutObjectRetentionApi
	ZosGetObjectLockConfApi                      *ZosGetObjectLockConfApi
	ZosPutObjectLockConfApi                      *ZosPutObjectLockConfApi
	ZosGetBucketReplicationCompleteApi           *ZosGetBucketReplicationCompleteApi
	ZosGetBucketReplicationRegionApi             *ZosGetBucketReplicationRegionApi
	ZosGetBucketReplicationApi                   *ZosGetBucketReplicationApi
	ZosPutBucketReplicationApi                   *ZosPutBucketReplicationApi
	ZosNewOssApi                                 *ZosNewOssApi
}

func NewApis(endpointUrl string, client *core.CtyunClient) *Apis {
	client.RegisterEndpoint(core.Endpoint{
		Name: EndpointName,
		Url:  endpointUrl,
	})
	return &Apis{
		ZosPutUserEventBridgeApi:                     NewZosPutUserEventBridgeApi(client),
		ZosGetUserEventBridgeApi:                     NewZosGetUserEventBridgeApi(client),
		ZosDeleteZMSMigrationTaskApi:                 NewZosDeleteZMSMigrationTaskApi(client),
		ZosResumeZMSMigrationTaskApi:                 NewZosResumeZMSMigrationTaskApi(client),
		ZosPauseZMSMigrationTaskApi:                  NewZosPauseZMSMigrationTaskApi(client),
		ZosRetryZMSMigrationTaskApi:                  NewZosRetryZMSMigrationTaskApi(client),
		ZosGetFailedObjectsListofZMSMigrationTaskApi: NewZosGetFailedObjectsListofZMSMigrationTaskApi(client),
		ZosGetZMSMigrationTaskDetailApi:              NewZosGetZMSMigrationTaskDetailApi(client),
		ZosGetZMSMigrationTaskListApi:                NewZosGetZMSMigrationTaskListApi(client),
		ZosCreateZMSMigrationTaskApi:                 NewZosCreateZMSMigrationTaskApi(client),
		ZosDeleteZMSAssessmentTaskApi:                NewZosDeleteZMSAssessmentTaskApi(client),
		ZosResumeZMSAssessmentTaskApi:                NewZosResumeZMSAssessmentTaskApi(client),
		ZosPauseZMSAssessmentTaskApi:                 NewZosPauseZMSAssessmentTaskApi(client),
		ZosStartZMSAssessmentTaskApi:                 NewZosStartZMSAssessmentTaskApi(client),
		ZosGetZMSAssessmentTaskDetailApi:             NewZosGetZMSAssessmentTaskDetailApi(client),
		ZosGetZMSAssessmentTaskListApi:               NewZosGetZMSAssessmentTaskListApi(client),
		ZosCreateZMSAssessmentTaskApi:                NewZosCreateZMSAssessmentTaskApi(client),
		ZosPutBucketEventBridgeApi:                   NewZosPutBucketEventBridgeApi(client),
		ZosListRegionsApi:                            NewZosListRegionsApi(client),
		ZosQueryNewOrderPriceApi:                     NewZosQueryNewOrderPriceApi(client),
		ZosGetOssServiceStatusApi:                    NewZosGetOssServiceStatusApi(client),
		ZosDeletePolicyApi:                           NewZosDeletePolicyApi(client),
		ZosPolicyDetailApi:                           NewZosPolicyDetailApi(client),
		ZosDeletePolicy1Api:                          NewZosDeletePolicy1Api(client),
		ZosPutPolicyApi:                              NewZosPutPolicyApi(client),
		ZosListPoliciesApi:                           NewZosListPoliciesApi(client),
		ZosRoleDetailApi:                             NewZosRoleDetailApi(client),
		ZosDeleteRoleApi:                             NewZosDeleteRoleApi(client),
		ZosListRolesApi:                              NewZosListRolesApi(client),
		ZosBindRolePolicyApi:                         NewZosBindRolePolicyApi(client),
		ZosCreatePolicyApi:                           NewZosCreatePolicyApi(client),
		ZosCreateRoleApi:                             NewZosCreateRoleApi(client),
		ZosGetBucketStatisticsApi:                    NewZosGetBucketStatisticsApi(client),
		ZosPutBucketQuotaApi:                         NewZosPutBucketQuotaApi(client),
		ZosGetEndpointApi:                            NewZosGetEndpointApi(client),
		ZosGetFragmentNumApi:                         NewZosGetFragmentNumApi(client),
		ZosPutObjectNumApi:                           NewZosPutObjectNumApi(client),
		ZosPutObjectStorageTypeApi:                   NewZosPutObjectStorageTypeApi(client),
		ZosUnfreezeObjectApi:                         NewZosUnfreezeObjectApi(client),
		ZosListAllPartsApi:                           NewZosListAllPartsApi(client),
		ZosDeleteDirectoryApi:                        NewZosDeleteDirectoryApi(client),
		ZosCreateDirectoryApi:                        NewZosCreateDirectoryApi(client),
		ZosListObjectVersionsApi:                     NewZosListObjectVersionsApi(client),
		ZosCompleteMultipartUploadApi:                NewZosCompleteMultipartUploadApi(client),
		ZosListPartsApi:                              NewZosListPartsApi(client),
		ZosGenerateObjectUploadLinkApi:               NewZosGenerateObjectUploadLinkApi(client),
		ZosGetKeysApi:                                NewZosGetKeysApi(client),
		ZosPutObjectHeaderApi:                        NewZosPutObjectHeaderApi(client),
		ZosDeleteObjectTaggingApi:                    NewZosDeleteObjectTaggingApi(client),
		ZosGetObjectTaggingApi:                       NewZosGetObjectTaggingApi(client),
		ZosPutObjectTaggingApi:                       NewZosPutObjectTaggingApi(client),
		ZosGetObjectAclApi:                           NewZosGetObjectAclApi(client),
		ZosPutObjectAclApi:                           NewZosPutObjectAclApi(client),
		ZosAbortMultipartUploadApi:                   NewZosAbortMultipartUploadApi(client),
		ZosListMultipartUploadsApi:                   NewZosListMultipartUploadsApi(client),
		ZosCreateMultipartUploadApi:                  NewZosCreateMultipartUploadApi(client),
		ZosHeadObjectApi:                             NewZosHeadObjectApi(client),
		ZosGenerateObjectDownloadLinkApi:             NewZosGenerateObjectDownloadLinkApi(client),
		ZosDeleteObjectsApi:                          NewZosDeleteObjectsApi(client),
		ZosCopyObjectApi:                             NewZosCopyObjectApi(client),
		ZosDeleteObjectApi:                           NewZosDeleteObjectApi(client),
		ZosListObjectsApi:                            NewZosListObjectsApi(client),
		ZosGetBucketInfoApi:                          NewZosGetBucketInfoApi(client),
		ZosPutBucketVersioningApi:                    NewZosPutBucketVersioningApi(client),
		ZosDeleteBucketLifecycleConfApi:              NewZosDeleteBucketLifecycleConfApi(client),
		ZosPutBucketLifecycleConfApi:                 NewZosPutBucketLifecycleConfApi(client),
		ZosPutBucketAclApi:                           NewZosPutBucketAclApi(client),
		ZosDeleteBucketReplicationApi:                NewZosDeleteBucketReplicationApi(client),
		ZosPutBucketLoggingApi:                       NewZosPutBucketLoggingApi(client),
		ZosDeleteBucketLoggingApi:                    NewZosDeleteBucketLoggingApi(client),
		ZosGetBucketLocationApi:                      NewZosGetBucketLocationApi(client),
		ZosDeleteBucketCorsApi:                       NewZosDeleteBucketCorsApi(client),
		ZosPutBucketCorsApi:                          NewZosPutBucketCorsApi(client),
		ZosGetBucketCorsApi:                          NewZosGetBucketCorsApi(client),
		ZosHeadBucketApi:                             NewZosHeadBucketApi(client),
		ZosDeleteBucketApi:                           NewZosDeleteBucketApi(client),
		ZosListBucketsApi:                            NewZosListBucketsApi(client),
		ZosCreateBucketApi:                           NewZosCreateBucketApi(client),
		ZosGetBucketEncryptionApi:                    NewZosGetBucketEncryptionApi(client),
		ZosPutBucketEncryptionApi:                    NewZosPutBucketEncryptionApi(client),
		ZosDeleteBucketEncryptionApi:                 NewZosDeleteBucketEncryptionApi(client),
		ZosDeleteBucketTaggingApi:                    NewZosDeleteBucketTaggingApi(client),
		ZosPutBucketTaggingApi:                       NewZosPutBucketTaggingApi(client),
		ZosDeleteBucketPolicyApi:                     NewZosDeleteBucketPolicyApi(client),
		ZosPutBucketPolicyApi:                        NewZosPutBucketPolicyApi(client),
		ZosGetBucketTaggingApi:                       NewZosGetBucketTaggingApi(client),
		ZosGetBucketLoggingApi:                       NewZosGetBucketLoggingApi(client),
		ZosGetBucketPolicyApi:                        NewZosGetBucketPolicyApi(client),
		ZosGetBucketVersioningApi:                    NewZosGetBucketVersioningApi(client),
		ZosGetBucketLifecycleConfApi:                 NewZosGetBucketLifecycleConfApi(client),
		ZosGetBucketAclApi:                           NewZosGetBucketAclApi(client),
		ZosGetObjectRetentionApi:                     NewZosGetObjectRetentionApi(client),
		ZosPutObjectRetentionApi:                     NewZosPutObjectRetentionApi(client),
		ZosGetObjectLockConfApi:                      NewZosGetObjectLockConfApi(client),
		ZosPutObjectLockConfApi:                      NewZosPutObjectLockConfApi(client),
		ZosGetBucketReplicationCompleteApi:           NewZosGetBucketReplicationCompleteApi(client),
		ZosGetBucketReplicationRegionApi:             NewZosGetBucketReplicationRegionApi(client),
		ZosGetBucketReplicationApi:                   NewZosGetBucketReplicationApi(client),
		ZosPutBucketReplicationApi:                   NewZosPutBucketReplicationApi(client),
		ZosNewOssApi:                                 NewZosNewOssApi(client),
	}
}
