package ctelb

import (
	"github.com/ctyun-it/terraform-provider-ctyun/internal/core/core"
)

const EndpointName = "ctelb"

type Apis struct {
	CtelbElbDisableIDCApi                   *CtelbElbDisableIDCApi
	CtelbElbEnableIDCApi                    *CtelbElbEnableIDCApi
	CtelbGwlbCreateApi                      *CtelbGwlbCreateApi
	CtelbGwlbUpdateApi                      *CtelbGwlbUpdateApi
	CtelbGwlbDeleteApi                      *CtelbGwlbDeleteApi
	CtelbGwlbDisableDeleteProtectionApi     *CtelbGwlbDisableDeleteProtectionApi
	CtelbGwlbDisableIpv6Api                 *CtelbGwlbDisableIpv6Api
	CtelbGwlbEnableIpv6Api                  *CtelbGwlbEnableIpv6Api
	CtelbGwlbEnableDeleteProtectionApi      *CtelbGwlbEnableDeleteProtectionApi
	CtelbGwlbShowApi                        *CtelbGwlbShowApi
	CtelbGwlbListApi                        *CtelbGwlbListApi
	CtelbGwlbCreateTargetApi                *CtelbGwlbCreateTargetApi
	CtelbGwlbUpdateTargetApi                *CtelbGwlbUpdateTargetApi
	CtelbGwlbDeleteTargetApi                *CtelbGwlbDeleteTargetApi
	CtelbGwlbShowTargetApi                  *CtelbGwlbShowTargetApi
	CtelbGwlbListTargetApi                  *CtelbGwlbListTargetApi
	CtelbGwlbCreateTargetGroupApi           *CtelbGwlbCreateTargetGroupApi
	CtelbGwlbUpdateTargetGroupApi           *CtelbGwlbUpdateTargetGroupApi
	CtelbGwlbDeleteTargetGroupApi           *CtelbGwlbDeleteTargetGroupApi
	CtelbGwlbShowTargetGroupApi             *CtelbGwlbShowTargetGroupApi
	CtelbGwlbListTargetGroupApi             *CtelbGwlbListTargetGroupApi
	CtelbIplistenerCreateApi                *CtelbIplistenerCreateApi
	CtelbIplistenerUpdateApi                *CtelbIplistenerUpdateApi
	CtelbIplistenerDeleteApi                *CtelbIplistenerDeleteApi
	CtelbIplistenerShowApi                  *CtelbIplistenerShowApi
	CtelbIplistenerListApi                  *CtelbIplistenerListApi
	CtelbElbModifyAccessLogApi              *CtelbElbModifyAccessLogApi
	CtelbElbDeleteAccessLogApi              *CtelbElbDeleteAccessLogApi
	CtelbElbCreateAccessLogApi              *CtelbElbCreateAccessLogApi
	CtelbCheckServerCertApi                 *CtelbCheckServerCertApi
	CtelbCheckCaCertApi                     *CtelbCheckCaCertApi
	CtelbListDomainCertLinksApi             *CtelbListDomainCertLinksApi
	CtelbUpdateDomainCertLinksApi           *CtelbUpdateDomainCertLinksApi
	CtelbDeleteDomainCertLinksApi           *CtelbDeleteDomainCertLinksApi
	CtelbCreateDomainCertLinkApi            *CtelbCreateDomainCertLinkApi
	CtelbRefundPgelbApi                     *CtelbRefundPgelbApi
	CtelbUpdateListenerResponseTimeoutApi   *CtelbUpdateListenerResponseTimeoutApi
	CtelbUpdateListenerQpsApi               *CtelbUpdateListenerQpsApi
	CtelbUpdateListenerNat64Api             *CtelbUpdateListenerNat64Api
	CtelbUpdateListenerIdleTimeoutApi       *CtelbUpdateListenerIdleTimeoutApi
	CtelbUpdateListenerEstabTimeoutApi      *CtelbUpdateListenerEstabTimeoutApi
	CtelbUpdateListenerCpsApi               *CtelbUpdateListenerCpsApi
	CtelbElbUnbindLabelsApi                 *CtelbElbUnbindLabelsApi
	CtelbElbBindLabelsApi                   *CtelbElbBindLabelsApi
	CtelbListElbLabelsApi                   *CtelbListElbLabelsApi
	CtelbUpgradeToPgelbApi                  *CtelbUpgradeToPgelbApi
	CtelbQueryRenewPgelbPriceApi            *CtelbQueryRenewPgelbPriceApi
	CtelbRenewPgelbApi                      *CtelbRenewPgelbApi
	CtelbQueryModifyPgelbSpecPriceApi       *CtelbQueryModifyPgelbSpecPriceApi
	CtelbModifyPgelbSpecApi                 *CtelbModifyPgelbSpecApi
	CtelbQueryCreatePgelbPriceApi           *CtelbQueryCreatePgelbPriceApi
	CtelbCreatePgelbApi                     *CtelbCreatePgelbApi
	CtelbNewQueryElbReatimeMonitorApi       *CtelbNewQueryElbReatimeMonitorApi
	CtelbNewQueryElbHistoryMonitorApi       *CtelbNewQueryElbHistoryMonitorApi
	CtelbUpdateVmPoolAttrApi                *CtelbUpdateVmPoolAttrApi
	CtelbUpdatePolicyAttrApi                *CtelbUpdatePolicyAttrApi
	CtelbAsyncCreatePolicyApi               *CtelbAsyncCreatePolicyApi
	CtelbRemoveVmApi                        *CtelbRemoveVmApi
	CtelbListVmApi                          *CtelbListVmApi
	CtelbAsyncCreateTargetApi               *CtelbAsyncCreateTargetApi
	CtelbUpdateListenerAttrApi              *CtelbUpdateListenerAttrApi
	CtelbAsyncCreateListenerApi             *CtelbAsyncCreateListenerApi
	CtelbListVmPoolApi                      *CtelbListVmPoolApi
	CtelbAsyncCreateCertificateApi          *CtelbAsyncCreateCertificateApi
	CtelbAsyncCreateLoadbalanceApi          *CtelbAsyncCreateLoadbalanceApi
	CtelbQueryElbHistoryMetricApi           *CtelbQueryElbHistoryMetricApi
	CtelbUpdateCertificateApi               *CtelbUpdateCertificateApi
	CtelbEnableElbIpv6Api                   *CtelbEnableElbIpv6Api
	CtelbDisableElbIpv6Api                  *CtelbDisableElbIpv6Api
	CtelbShowAccessControlApi               *CtelbShowAccessControlApi
	CtelbShowHealthCheckApi                 *CtelbShowHealthCheckApi
	CtelbQueryElbReatimeMetricApi           *CtelbQueryElbReatimeMetricApi
	CtelbQuerySlaApi                        *CtelbQuerySlaApi
	CtelbListQueryApi                       *CtelbListQueryApi
	CtelbShowRuleApi                        *CtelbShowRuleApi
	CtelbUpdateRuleApi                      *CtelbUpdateRuleApi
	CtelbDeleteRuleApi                      *CtelbDeleteRuleApi
	CtelbCreateRuleApi                      *CtelbCreateRuleApi
	CtelbListAccessControlApi               *CtelbListAccessControlApi
	CtelbUpdateAccessControlApi             *CtelbUpdateAccessControlApi
	CtelbDeleteAccessControlApi             *CtelbDeleteAccessControlApi
	CtelbCreateAccessControlApi             *CtelbCreateAccessControlApi
	CtelbListCertificateApi                 *CtelbListCertificateApi
	CtelbShowCertificateApi                 *CtelbShowCertificateApi
	CtelbDeleteCertificateApi               *CtelbDeleteCertificateApi
	CtelbCreateCertificateApi               *CtelbCreateCertificateApi
	CtelbListHealthCheckApi                 *CtelbListHealthCheckApi
	CtelbUpdateHealthCheckApi               *CtelbUpdateHealthCheckApi
	CtelbDeleteHealthCheckApi               *CtelbDeleteHealthCheckApi
	CtelbCreateHealthCheckApi               *CtelbCreateHealthCheckApi
	CtelbListTargetApi                      *CtelbListTargetApi
	CtelbShowTargetApi                      *CtelbShowTargetApi
	CtelbUpdateTargetApi                    *CtelbUpdateTargetApi
	CtelbDeleteTargetApi                    *CtelbDeleteTargetApi
	CtelbCreateTargetApi                    *CtelbCreateTargetApi
	CtelbListTargetGroupApi                 *CtelbListTargetGroupApi
	CtelbShowTargetGroupApi                 *CtelbShowTargetGroupApi
	CtelbDeleteTargetGroupApi               *CtelbDeleteTargetGroupApi
	CtelbUpdateTargetGroupApi               *CtelbUpdateTargetGroupApi
	CtelbCreateTargetGroupApi               *CtelbCreateTargetGroupApi
	CtelbStopListenerApi                    *CtelbStopListenerApi
	CtelbStartListenerApi                   *CtelbStartListenerApi
	CtelbListListenerApi                    *CtelbListListenerApi
	CtelbShowListenerApi                    *CtelbShowListenerApi
	CtelbUpdateListenerApi                  *CtelbUpdateListenerApi
	CtelbDeleteListenerApi                  *CtelbDeleteListenerApi
	CtelbCreateListenerApi                  *CtelbCreateListenerApi
	CtelbDisassociateEipFromLoadBalancerApi *CtelbDisassociateEipFromLoadBalancerApi
	CtelbAssociateEipToLoadBalancerApi      *CtelbAssociateEipToLoadBalancerApi
	CtelbListLoadBalancerApi                *CtelbListLoadBalancerApi
	CtelbShowLoadBalancerApi                *CtelbShowLoadBalancerApi
	CtelbUpdateLoadBalancerApi              *CtelbUpdateLoadBalancerApi
	CtelbDeleteLoadBalancerApi              *CtelbDeleteLoadBalancerApi
	CtelbCreateLoadBalancerApi              *CtelbCreateLoadBalancerApi
}

func NewApis(endpointUrl string, client *core.CtyunClient) *Apis {
	client.RegisterEndpoint(core.Endpoint{
		Name: EndpointName,
		Url:  endpointUrl,
	})
	return &Apis{
		CtelbElbDisableIDCApi:                   NewCtelbElbDisableIDCApi(client),
		CtelbElbEnableIDCApi:                    NewCtelbElbEnableIDCApi(client),
		CtelbGwlbCreateApi:                      NewCtelbGwlbCreateApi(client),
		CtelbGwlbUpdateApi:                      NewCtelbGwlbUpdateApi(client),
		CtelbGwlbDeleteApi:                      NewCtelbGwlbDeleteApi(client),
		CtelbGwlbDisableDeleteProtectionApi:     NewCtelbGwlbDisableDeleteProtectionApi(client),
		CtelbGwlbDisableIpv6Api:                 NewCtelbGwlbDisableIpv6Api(client),
		CtelbGwlbEnableIpv6Api:                  NewCtelbGwlbEnableIpv6Api(client),
		CtelbGwlbEnableDeleteProtectionApi:      NewCtelbGwlbEnableDeleteProtectionApi(client),
		CtelbGwlbShowApi:                        NewCtelbGwlbShowApi(client),
		CtelbGwlbListApi:                        NewCtelbGwlbListApi(client),
		CtelbGwlbCreateTargetApi:                NewCtelbGwlbCreateTargetApi(client),
		CtelbGwlbUpdateTargetApi:                NewCtelbGwlbUpdateTargetApi(client),
		CtelbGwlbDeleteTargetApi:                NewCtelbGwlbDeleteTargetApi(client),
		CtelbGwlbShowTargetApi:                  NewCtelbGwlbShowTargetApi(client),
		CtelbGwlbListTargetApi:                  NewCtelbGwlbListTargetApi(client),
		CtelbGwlbCreateTargetGroupApi:           NewCtelbGwlbCreateTargetGroupApi(client),
		CtelbGwlbUpdateTargetGroupApi:           NewCtelbGwlbUpdateTargetGroupApi(client),
		CtelbGwlbDeleteTargetGroupApi:           NewCtelbGwlbDeleteTargetGroupApi(client),
		CtelbGwlbShowTargetGroupApi:             NewCtelbGwlbShowTargetGroupApi(client),
		CtelbGwlbListTargetGroupApi:             NewCtelbGwlbListTargetGroupApi(client),
		CtelbIplistenerCreateApi:                NewCtelbIplistenerCreateApi(client),
		CtelbIplistenerUpdateApi:                NewCtelbIplistenerUpdateApi(client),
		CtelbIplistenerDeleteApi:                NewCtelbIplistenerDeleteApi(client),
		CtelbIplistenerShowApi:                  NewCtelbIplistenerShowApi(client),
		CtelbIplistenerListApi:                  NewCtelbIplistenerListApi(client),
		CtelbElbModifyAccessLogApi:              NewCtelbElbModifyAccessLogApi(client),
		CtelbElbDeleteAccessLogApi:              NewCtelbElbDeleteAccessLogApi(client),
		CtelbElbCreateAccessLogApi:              NewCtelbElbCreateAccessLogApi(client),
		CtelbCheckServerCertApi:                 NewCtelbCheckServerCertApi(client),
		CtelbCheckCaCertApi:                     NewCtelbCheckCaCertApi(client),
		CtelbListDomainCertLinksApi:             NewCtelbListDomainCertLinksApi(client),
		CtelbUpdateDomainCertLinksApi:           NewCtelbUpdateDomainCertLinksApi(client),
		CtelbDeleteDomainCertLinksApi:           NewCtelbDeleteDomainCertLinksApi(client),
		CtelbCreateDomainCertLinkApi:            NewCtelbCreateDomainCertLinkApi(client),
		CtelbRefundPgelbApi:                     NewCtelbRefundPgelbApi(client),
		CtelbUpdateListenerResponseTimeoutApi:   NewCtelbUpdateListenerResponseTimeoutApi(client),
		CtelbUpdateListenerQpsApi:               NewCtelbUpdateListenerQpsApi(client),
		CtelbUpdateListenerNat64Api:             NewCtelbUpdateListenerNat64Api(client),
		CtelbUpdateListenerIdleTimeoutApi:       NewCtelbUpdateListenerIdleTimeoutApi(client),
		CtelbUpdateListenerEstabTimeoutApi:      NewCtelbUpdateListenerEstabTimeoutApi(client),
		CtelbUpdateListenerCpsApi:               NewCtelbUpdateListenerCpsApi(client),
		CtelbElbUnbindLabelsApi:                 NewCtelbElbUnbindLabelsApi(client),
		CtelbElbBindLabelsApi:                   NewCtelbElbBindLabelsApi(client),
		CtelbListElbLabelsApi:                   NewCtelbListElbLabelsApi(client),
		CtelbUpgradeToPgelbApi:                  NewCtelbUpgradeToPgelbApi(client),
		CtelbQueryRenewPgelbPriceApi:            NewCtelbQueryRenewPgelbPriceApi(client),
		CtelbRenewPgelbApi:                      NewCtelbRenewPgelbApi(client),
		CtelbQueryModifyPgelbSpecPriceApi:       NewCtelbQueryModifyPgelbSpecPriceApi(client),
		CtelbModifyPgelbSpecApi:                 NewCtelbModifyPgelbSpecApi(client),
		CtelbQueryCreatePgelbPriceApi:           NewCtelbQueryCreatePgelbPriceApi(client),
		CtelbCreatePgelbApi:                     NewCtelbCreatePgelbApi(client),
		CtelbNewQueryElbReatimeMonitorApi:       NewCtelbNewQueryElbReatimeMonitorApi(client),
		CtelbNewQueryElbHistoryMonitorApi:       NewCtelbNewQueryElbHistoryMonitorApi(client),
		CtelbUpdateVmPoolAttrApi:                NewCtelbUpdateVmPoolAttrApi(client),
		CtelbUpdatePolicyAttrApi:                NewCtelbUpdatePolicyAttrApi(client),
		CtelbAsyncCreatePolicyApi:               NewCtelbAsyncCreatePolicyApi(client),
		CtelbRemoveVmApi:                        NewCtelbRemoveVmApi(client),
		CtelbListVmApi:                          NewCtelbListVmApi(client),
		CtelbAsyncCreateTargetApi:               NewCtelbAsyncCreateTargetApi(client),
		CtelbUpdateListenerAttrApi:              NewCtelbUpdateListenerAttrApi(client),
		CtelbAsyncCreateListenerApi:             NewCtelbAsyncCreateListenerApi(client),
		CtelbListVmPoolApi:                      NewCtelbListVmPoolApi(client),
		CtelbAsyncCreateCertificateApi:          NewCtelbAsyncCreateCertificateApi(client),
		CtelbAsyncCreateLoadbalanceApi:          NewCtelbAsyncCreateLoadbalanceApi(client),
		CtelbQueryElbHistoryMetricApi:           NewCtelbQueryElbHistoryMetricApi(client),
		CtelbUpdateCertificateApi:               NewCtelbUpdateCertificateApi(client),
		CtelbEnableElbIpv6Api:                   NewCtelbEnableElbIpv6Api(client),
		CtelbDisableElbIpv6Api:                  NewCtelbDisableElbIpv6Api(client),
		CtelbShowAccessControlApi:               NewCtelbShowAccessControlApi(client),
		CtelbShowHealthCheckApi:                 NewCtelbShowHealthCheckApi(client),
		CtelbQueryElbReatimeMetricApi:           NewCtelbQueryElbReatimeMetricApi(client),
		CtelbQuerySlaApi:                        NewCtelbQuerySlaApi(client),
		CtelbListQueryApi:                       NewCtelbListQueryApi(client),
		CtelbShowRuleApi:                        NewCtelbShowRuleApi(client),
		CtelbUpdateRuleApi:                      NewCtelbUpdateRuleApi(client),
		CtelbDeleteRuleApi:                      NewCtelbDeleteRuleApi(client),
		CtelbCreateRuleApi:                      NewCtelbCreateRuleApi(client),
		CtelbListAccessControlApi:               NewCtelbListAccessControlApi(client),
		CtelbUpdateAccessControlApi:             NewCtelbUpdateAccessControlApi(client),
		CtelbDeleteAccessControlApi:             NewCtelbDeleteAccessControlApi(client),
		CtelbCreateAccessControlApi:             NewCtelbCreateAccessControlApi(client),
		CtelbListCertificateApi:                 NewCtelbListCertificateApi(client),
		CtelbShowCertificateApi:                 NewCtelbShowCertificateApi(client),
		CtelbDeleteCertificateApi:               NewCtelbDeleteCertificateApi(client),
		CtelbCreateCertificateApi:               NewCtelbCreateCertificateApi(client),
		CtelbListHealthCheckApi:                 NewCtelbListHealthCheckApi(client),
		CtelbUpdateHealthCheckApi:               NewCtelbUpdateHealthCheckApi(client),
		CtelbDeleteHealthCheckApi:               NewCtelbDeleteHealthCheckApi(client),
		CtelbCreateHealthCheckApi:               NewCtelbCreateHealthCheckApi(client),
		CtelbListTargetApi:                      NewCtelbListTargetApi(client),
		CtelbShowTargetApi:                      NewCtelbShowTargetApi(client),
		CtelbUpdateTargetApi:                    NewCtelbUpdateTargetApi(client),
		CtelbDeleteTargetApi:                    NewCtelbDeleteTargetApi(client),
		CtelbCreateTargetApi:                    NewCtelbCreateTargetApi(client),
		CtelbListTargetGroupApi:                 NewCtelbListTargetGroupApi(client),
		CtelbShowTargetGroupApi:                 NewCtelbShowTargetGroupApi(client),
		CtelbDeleteTargetGroupApi:               NewCtelbDeleteTargetGroupApi(client),
		CtelbUpdateTargetGroupApi:               NewCtelbUpdateTargetGroupApi(client),
		CtelbCreateTargetGroupApi:               NewCtelbCreateTargetGroupApi(client),
		CtelbStopListenerApi:                    NewCtelbStopListenerApi(client),
		CtelbStartListenerApi:                   NewCtelbStartListenerApi(client),
		CtelbListListenerApi:                    NewCtelbListListenerApi(client),
		CtelbShowListenerApi:                    NewCtelbShowListenerApi(client),
		CtelbUpdateListenerApi:                  NewCtelbUpdateListenerApi(client),
		CtelbDeleteListenerApi:                  NewCtelbDeleteListenerApi(client),
		CtelbCreateListenerApi:                  NewCtelbCreateListenerApi(client),
		CtelbDisassociateEipFromLoadBalancerApi: NewCtelbDisassociateEipFromLoadBalancerApi(client),
		CtelbAssociateEipToLoadBalancerApi:      NewCtelbAssociateEipToLoadBalancerApi(client),
		CtelbListLoadBalancerApi:                NewCtelbListLoadBalancerApi(client),
		CtelbShowLoadBalancerApi:                NewCtelbShowLoadBalancerApi(client),
		CtelbUpdateLoadBalancerApi:              NewCtelbUpdateLoadBalancerApi(client),
		CtelbDeleteLoadBalancerApi:              NewCtelbDeleteLoadBalancerApi(client),
		CtelbCreateLoadBalancerApi:              NewCtelbCreateLoadBalancerApi(client),
	}
}
