package dcs2

import (
	"github.com/ctyun-it/terraform-provider-ctyun/internal/core/core"
)

const EndpointName = "dcs2"

type Apis struct {
	Dcs2DescribeClusterMemberInfoApi            *Dcs2DescribeClusterMemberInfoApi
	Dcs2DescribeLogicInstanceTopologyApi        *Dcs2DescribeLogicInstanceTopologyApi
	Dcs2DescribeInstanceMaintainTimeApi         *Dcs2DescribeInstanceMaintainTimeApi
	Dcs2ModifyInstanceMaintainTimeApi           *Dcs2ModifyInstanceMaintainTimeApi
	Dcs2SwitchInstanceHAApi                     *Dcs2SwitchInstanceHAApi
	Dcs2DescribeDbKeyCountApi                   *Dcs2DescribeDbKeyCountApi
	Dcs2DescribeMemoryInfoApi                   *Dcs2DescribeMemoryInfoApi
	Dcs2GetRedisNodeListApi                     *Dcs2GetRedisNodeListApi
	Dcs2FlushExpireKeysApi                      *Dcs2FlushExpireKeysApi
	Dcs2CreateAccountApi                        *Dcs2CreateAccountApi
	Dcs2DescribeAccountsApi                     *Dcs2DescribeAccountsApi
	Dcs2GrantAccountPrivilegeApi                *Dcs2GrantAccountPrivilegeApi
	Dcs2ModifyAccountDescriptionApi             *Dcs2ModifyAccountDescriptionApi
	Dcs2ModifyAccountPasswordApi                *Dcs2ModifyAccountPasswordApi
	Dcs2ResetAccountPasswordApi                 *Dcs2ResetAccountPasswordApi
	Dcs2DeleteAccountApi                        *Dcs2DeleteAccountApi
	Dcs2CreateBackupApi                         *Dcs2CreateBackupApi
	Dcs2DescribeBackupTasksApi                  *Dcs2DescribeBackupTasksApi
	Dcs2DescribeBackupPolicyApi                 *Dcs2DescribeBackupPolicyApi
	Dcs2ModifyBackupPolicyApi                   *Dcs2ModifyBackupPolicyApi
	Dcs2DescribeBackupsApi                      *Dcs2DescribeBackupsApi
	Dcs2RestoreInstanceApi                      *Dcs2RestoreInstanceApi
	Dcs2DescribeNodeMonitorItemsApi             *Dcs2DescribeNodeMonitorItemsApi
	Dcs2DescribeNodeMonitorValuesApi            *Dcs2DescribeNodeMonitorValuesApi
	Dcs2DescribeDbGroupApi                      *Dcs2DescribeDbGroupApi
	Dcs2DeleteDbGroupApi                        *Dcs2DeleteDbGroupApi
	Dcs2CreateDbGroupApi                        *Dcs2CreateDbGroupApi
	Dcs2FlushDbGroupDataApi                     *Dcs2FlushDbGroupDataApi
	Dcs2DescribeInstanceStrategyApi             *Dcs2DescribeInstanceStrategyApi
	Dcs2ModifyInstanceStrategyApi               *Dcs2ModifyInstanceStrategyApi
	Dcs2DescribeHotKeysApi                      *Dcs2DescribeHotKeysApi
	Dcs2DescribeBigAndHotKeysApi                *Dcs2DescribeBigAndHotKeysApi
	Dcs2DescribeKeyTaskRecordApi                *Dcs2DescribeKeyTaskRecordApi
	Dcs2QueryRenameCommandApi                   *Dcs2QueryRenameCommandApi
	Dcs2TransToPrePaidApi                       *Dcs2TransToPrePaidApi
	Dcs2TransChargeTypeApi                      *Dcs2TransChargeTypeApi
	Dcs2DescribeSecurityIpsApi                  *Dcs2DescribeSecurityIpsApi
	Dcs2ModifySecurityIpsApi                    *Dcs2ModifySecurityIpsApi
	Dcs2EnableRenameCommandApi                  *Dcs2EnableRenameCommandApi
	Dcs2DescribeRunningLogRecordsApi            *Dcs2DescribeRunningLogRecordsApi
	Dcs2BindElasticIPApi                        *Dcs2BindElasticIPApi
	Dcs2UnBindElasticIPApi                      *Dcs2UnBindElasticIPApi
	Dcs2ChangeAutoRenewStatusApi                *Dcs2ChangeAutoRenewStatusApi
	Dcs2DescribeAvailableRegionApi              *Dcs2DescribeAvailableRegionApi
	Dcs2DescribeInstancesApi                    *Dcs2DescribeInstancesApi
	Dcs2DescribeCycleBinInstancesApi            *Dcs2DescribeCycleBinInstancesApi
	Dcs2DescribeDedicatedClusterInstanceListApi *Dcs2DescribeDedicatedClusterInstanceListApi
	Dcs2DescribePriceApi                        *Dcs2DescribePriceApi
	Dcs2RenewInstanceApi                        *Dcs2RenewInstanceApi
	Dcs2CreateInstanceApi                       *Dcs2CreateInstanceApi
	Dcs2ModifyInstanceSpecApi                   *Dcs2ModifyInstanceSpecApi
	Dcs2DeleteInstanceApi                       *Dcs2DeleteInstanceApi
	Dcs2DescribeAvailableResourceApi            *Dcs2DescribeAvailableResourceApi
	Dcs2DescribeInstancesOverviewApi            *Dcs2DescribeInstancesOverviewApi
	Dcs2DescribeEngineVersionApi                *Dcs2DescribeEngineVersionApi
	Dcs2DescribeDBInstanceNetInfoApi            *Dcs2DescribeDBInstanceNetInfoApi
	Dcs2ModifyInstanceMajorVersionApi           *Dcs2ModifyInstanceMajorVersionApi
	Dcs2RestartInstanceApi                      *Dcs2RestartInstanceApi
	Dcs2FlushDataApi                            *Dcs2FlushDataApi
	Dcs2DescribeTopSlowLogRecoredsApi           *Dcs2DescribeTopSlowLogRecoredsApi
	Dcs2DescribeTopBigKeysApi                   *Dcs2DescribeTopBigKeysApi
	Dcs2EnableRenameCommandV2Api                *Dcs2EnableRenameCommandV2Api
	Dcs2DisableRenameCommandV2Api               *Dcs2DisableRenameCommandV2Api
	Dcs2DescribeInstanceConfigV2Api             *Dcs2DescribeInstanceConfigV2Api
	Dcs2ModifyInstanceConfigV2Api               *Dcs2ModifyInstanceConfigV2Api
	Dcs2QueryInstAutoRenewStatusApi             *Dcs2QueryInstAutoRenewStatusApi
	Dcs2DescribeDbGroupsApi                     *Dcs2DescribeDbGroupsApi
	Dcs2QueryGroupKeyNumberApi                  *Dcs2QueryGroupKeyNumberApi
	Dcs2QueryGroupKeyApi                        *Dcs2QueryGroupKeyApi
	Dcs2QueryManagerApi                         *Dcs2QueryManagerApi
	Dcs2PageQueryValuesApi                      *Dcs2PageQueryValuesApi
	Dcs2DeleteKeyApi                            *Dcs2DeleteKeyApi
	Dcs2UpdateKeyApi                            *Dcs2UpdateKeyApi
	Dcs2UpdateValueApi                          *Dcs2UpdateValueApi
	Dcs2AddValueApi                             *Dcs2AddValueApi
	Dcs2DeleteValueApi                          *Dcs2DeleteValueApi
	Dcs2DeleteBackupApi                         *Dcs2DeleteBackupApi
	Dcs2GetClientIPInfoApi                      *Dcs2GetClientIPInfoApi
	Dcs2KillSelectedClientApi                   *Dcs2KillSelectedClientApi
	Dcs2GetClientMapApi                         *Dcs2GetClientMapApi
	Dcs2FindHistoryBigAndHotKeyApi              *Dcs2FindHistoryBigAndHotKeyApi
	Dcs2FindHistorySlowLogApi                   *Dcs2FindHistorySlowLogApi
	Dcs2DescribeHistoryMonitorItemsApi          *Dcs2DescribeHistoryMonitorItemsApi
	Dcs2DescribeInstanceHistoryMonitorValuesApi *Dcs2DescribeInstanceHistoryMonitorValuesApi
	Dcs2DescribeNodeHistoryMonitorValuesApi     *Dcs2DescribeNodeHistoryMonitorValuesApi
	Dcs2ExecuteOffLineKeyAnalysisTaskApi        *Dcs2ExecuteOffLineKeyAnalysisTaskApi
	Dcs2DescribeOffLineKeyAnalysisTaskListApi   *Dcs2DescribeOffLineKeyAnalysisTaskListApi
	Dcs2DescribeOffLineKeyAnalysisTaskInfoApi   *Dcs2DescribeOffLineKeyAnalysisTaskInfoApi
	Dcs2DeleteOffLineKeyAnalysisTaskInfoApi     *Dcs2DeleteOffLineKeyAnalysisTaskInfoApi
	Dcs2DescribeInstanceConfigApi               *Dcs2DescribeInstanceConfigApi
	Dcs2DescribeParameterModificationHistoryApi *Dcs2DescribeParameterModificationHistoryApi
	Dcs2ModifyInstanceConfigApi                 *Dcs2ModifyInstanceConfigApi
	Dcs2CreateTransferTaskApi                   *Dcs2CreateTransferTaskApi
	Dcs2OperateTransferTaskApi                  *Dcs2OperateTransferTaskApi
	Dcs2ListTaskInfoApi                         *Dcs2ListTaskInfoApi
	Dcs2DescribeRedisTemplateApi                *Dcs2DescribeRedisTemplateApi
	Dcs2DescribeRedisTemplateDetailApi          *Dcs2DescribeRedisTemplateDetailApi
	Dcs2CreateRedisTemplateApi                  *Dcs2CreateRedisTemplateApi
	Dcs2DeleteRedisTemplateApi                  *Dcs2DeleteRedisTemplateApi
	Dcs2EditRedisTemplateApi                    *Dcs2EditRedisTemplateApi
	Dcs2GetRdbDownLoadUrlApi                    *Dcs2GetRdbDownLoadUrlApi
	Dcs2AutoScanExpiredKeysApi                  *Dcs2AutoScanExpiredKeysApi
	Dcs2QueryAutoScanConfSettingApi             *Dcs2QueryAutoScanConfSettingApi
	Dcs2ModifyInstanceAttributeApi              *Dcs2ModifyInstanceAttributeApi
	Dcs2QueryAnalysisInstanceTasksApi           *Dcs2QueryAnalysisInstanceTasksApi
	Dcs2DoAnalysisInstanceTasksApi              *Dcs2DoAnalysisInstanceTasksApi
	Dcs2QueryAnalysisInstanceTasksInfoApi       *Dcs2QueryAnalysisInstanceTasksInfoApi
	Dcs2DelAnalysisInstanceTaskApi              *Dcs2DelAnalysisInstanceTaskApi
	Dcs2LockDBInstanceWriteApi                  *Dcs2LockDBInstanceWriteApi
	Dcs2UnlockDBInstanceWriteApi                *Dcs2UnlockDBInstanceWriteApi
	Dcs2ListTasksApi                            *Dcs2ListTasksApi
	Dcs2ModifyInstancePasswordApi               *Dcs2ModifyInstancePasswordApi
	Dcs2ResetInstancePasswordApi                *Dcs2ResetInstancePasswordApi
	Dcs2DescribeInstanceSSLApi                  *Dcs2DescribeInstanceSSLApi
	Dcs2ModifyInstanceSSLApi                    *Dcs2ModifyInstanceSSLApi
	Dcs2SlowLogResetApi                         *Dcs2SlowLogResetApi
	Dcs2ModifyInstanceFeatureApi                *Dcs2ModifyInstanceFeatureApi
	Dcs2DescribeHotKeyTasksApi                  *Dcs2DescribeHotKeyTasksApi
	Dcs2DescribeBigKeyTasksApi                  *Dcs2DescribeBigKeyTasksApi
	Dcs2DeleteHotKeyTaskApi                     *Dcs2DeleteHotKeyTaskApi
	Dcs2DeleteBigKeyTaskApi                     *Dcs2DeleteBigKeyTaskApi
	Dcs2DeleteInstancesApi                      *Dcs2DeleteInstancesApi
	Dcs2PageListLabelApi                        *Dcs2PageListLabelApi
	Dcs2BatchAddLabelApi                        *Dcs2BatchAddLabelApi
	Dcs2GetLabelListByResourcesApi              *Dcs2GetLabelListByResourcesApi
	Dcs2QueryQuotaTotalAndUsedApi               *Dcs2QueryQuotaTotalAndUsedApi
	Dcs2GetZonesApi                             *Dcs2GetZonesApi
	Dcs2ExcuteCommandApi                        *Dcs2ExcuteCommandApi
	Dcs2StatusNumberApi                         *Dcs2StatusNumberApi
	Dcs2StatisticApi                            *Dcs2StatisticApi
	Dcs2CheckInstanceOperateApi                 *Dcs2CheckInstanceOperateApi
	Dcs2AsyncExportInstancesApi                 *Dcs2AsyncExportInstancesApi
	Dcs2UpdateSlavePriorityApi                  *Dcs2UpdateSlavePriorityApi
	Dcs2DescribeInstancesClusterMemberInfoApi   *Dcs2DescribeInstancesClusterMemberInfoApi
	Dcs2QueryFragmentReplicationStateApi        *Dcs2QueryFragmentReplicationStateApi
	Dcs2ExchangeVipApi                          *Dcs2ExchangeVipApi
	Dcs2DeleteTransferTaskApi                   *Dcs2DeleteTransferTaskApi
	Dcs2GetTransferTaskInfoApi                  *Dcs2GetTransferTaskInfoApi
	Dcs2ConfigAutoRetryTypeApi                  *Dcs2ConfigAutoRetryTypeApi
	Dcs2GetTaskProgressDetailInfoApi            *Dcs2GetTaskProgressDetailInfoApi
	Dcs2StopTransferTaskApi                     *Dcs2StopTransferTaskApi
	Dcs2UploadSyncRunningLogApi                 *Dcs2UploadSyncRunningLogApi
	Dcs2RestartTransferTaskApi                  *Dcs2RestartTransferTaskApi
	Dcs2DescribeTopBigKeysPolicyApi             *Dcs2DescribeTopBigKeysPolicyApi
	Dcs2ModifyBigKeyPolicyApi                   *Dcs2ModifyBigKeyPolicyApi
	Dcs2DescribeTopHotKeysPolicyApi             *Dcs2DescribeTopHotKeysPolicyApi
	Dcs2ModifyHotKeyPolicyApi                   *Dcs2ModifyHotKeyPolicyApi
	Dcs2DownloadRedisRunLogApi                  *Dcs2DownloadRedisRunLogApi
	Dcs2DownloadSslCertApi                      *Dcs2DownloadSslCertApi
	Dcs2DelTasksApi                             *Dcs2DelTasksApi
	Dcs2GetTaskInfoApi                          *Dcs2GetTaskInfoApi
	Dcs2CheckInstanceProdModifyApi              *Dcs2CheckInstanceProdModifyApi
	Dcs2QueryExportInstanceTaskApi              *Dcs2QueryExportInstanceTaskApi
	Dcs2GetKeyMisslogApi                        *Dcs2GetKeyMisslogApi
	Dcs2DescribeInstanceVersionApi              *Dcs2DescribeInstanceVersionApi
	Dcs2UpgradeInstanceMinorVersionApi          *Dcs2UpgradeInstanceMinorVersionApi
	Dcs2UpgradeInstanceProxyMinorVersionApi     *Dcs2UpgradeInstanceProxyMinorVersionApi
	Dcs2OpenAutoScaleApi                        *Dcs2OpenAutoScaleApi
	Dcs2CloseAutoScaleApi                       *Dcs2CloseAutoScaleApi
	Dcs2BatchRestartVmApi                       *Dcs2BatchRestartVmApi
	Dcs2QueryScanLogsApi                        *Dcs2QueryScanLogsApi
	Dcs2HostDownFaultInjectApi                  *Dcs2HostDownFaultInjectApi
	Dcs2HostTypeFaultInjectApi                  *Dcs2HostTypeFaultInjectApi
	Dcs2NetworkLossFaultInjectApi               *Dcs2NetworkLossFaultInjectApi
	Dcs2FaultRecoveryApi                        *Dcs2FaultRecoveryApi
	Dcs2ListInstanceExperimentsApi              *Dcs2ListInstanceExperimentsApi
	Dcs2EnableRWSepApi                          *Dcs2EnableRWSepApi
	Dcs2QueryRWSepApi                           *Dcs2QueryRWSepApi
	Dcs2DestroyInstanceApi                      *Dcs2DestroyInstanceApi
}

func NewApis(endpointUrl string, client *core.CtyunClient) *Apis {
	client.RegisterEndpoint(core.Endpoint{
		Name: EndpointName,
		Url:  endpointUrl,
	})
	return &Apis{
		Dcs2DescribeClusterMemberInfoApi:            NewDcs2DescribeClusterMemberInfoApi(client),
		Dcs2DescribeLogicInstanceTopologyApi:        NewDcs2DescribeLogicInstanceTopologyApi(client),
		Dcs2DescribeInstanceMaintainTimeApi:         NewDcs2DescribeInstanceMaintainTimeApi(client),
		Dcs2ModifyInstanceMaintainTimeApi:           NewDcs2ModifyInstanceMaintainTimeApi(client),
		Dcs2SwitchInstanceHAApi:                     NewDcs2SwitchInstanceHAApi(client),
		Dcs2DescribeDbKeyCountApi:                   NewDcs2DescribeDbKeyCountApi(client),
		Dcs2DescribeMemoryInfoApi:                   NewDcs2DescribeMemoryInfoApi(client),
		Dcs2GetRedisNodeListApi:                     NewDcs2GetRedisNodeListApi(client),
		Dcs2FlushExpireKeysApi:                      NewDcs2FlushExpireKeysApi(client),
		Dcs2CreateAccountApi:                        NewDcs2CreateAccountApi(client),
		Dcs2DescribeAccountsApi:                     NewDcs2DescribeAccountsApi(client),
		Dcs2GrantAccountPrivilegeApi:                NewDcs2GrantAccountPrivilegeApi(client),
		Dcs2ModifyAccountDescriptionApi:             NewDcs2ModifyAccountDescriptionApi(client),
		Dcs2ModifyAccountPasswordApi:                NewDcs2ModifyAccountPasswordApi(client),
		Dcs2ResetAccountPasswordApi:                 NewDcs2ResetAccountPasswordApi(client),
		Dcs2DeleteAccountApi:                        NewDcs2DeleteAccountApi(client),
		Dcs2CreateBackupApi:                         NewDcs2CreateBackupApi(client),
		Dcs2DescribeBackupTasksApi:                  NewDcs2DescribeBackupTasksApi(client),
		Dcs2DescribeBackupPolicyApi:                 NewDcs2DescribeBackupPolicyApi(client),
		Dcs2ModifyBackupPolicyApi:                   NewDcs2ModifyBackupPolicyApi(client),
		Dcs2DescribeBackupsApi:                      NewDcs2DescribeBackupsApi(client),
		Dcs2RestoreInstanceApi:                      NewDcs2RestoreInstanceApi(client),
		Dcs2DescribeNodeMonitorItemsApi:             NewDcs2DescribeNodeMonitorItemsApi(client),
		Dcs2DescribeNodeMonitorValuesApi:            NewDcs2DescribeNodeMonitorValuesApi(client),
		Dcs2DescribeDbGroupApi:                      NewDcs2DescribeDbGroupApi(client),
		Dcs2DeleteDbGroupApi:                        NewDcs2DeleteDbGroupApi(client),
		Dcs2CreateDbGroupApi:                        NewDcs2CreateDbGroupApi(client),
		Dcs2FlushDbGroupDataApi:                     NewDcs2FlushDbGroupDataApi(client),
		Dcs2DescribeInstanceStrategyApi:             NewDcs2DescribeInstanceStrategyApi(client),
		Dcs2ModifyInstanceStrategyApi:               NewDcs2ModifyInstanceStrategyApi(client),
		Dcs2DescribeHotKeysApi:                      NewDcs2DescribeHotKeysApi(client),
		Dcs2DescribeBigAndHotKeysApi:                NewDcs2DescribeBigAndHotKeysApi(client),
		Dcs2DescribeKeyTaskRecordApi:                NewDcs2DescribeKeyTaskRecordApi(client),
		Dcs2QueryRenameCommandApi:                   NewDcs2QueryRenameCommandApi(client),
		Dcs2TransToPrePaidApi:                       NewDcs2TransToPrePaidApi(client),
		Dcs2TransChargeTypeApi:                      NewDcs2TransChargeTypeApi(client),
		Dcs2DescribeSecurityIpsApi:                  NewDcs2DescribeSecurityIpsApi(client),
		Dcs2ModifySecurityIpsApi:                    NewDcs2ModifySecurityIpsApi(client),
		Dcs2EnableRenameCommandApi:                  NewDcs2EnableRenameCommandApi(client),
		Dcs2DescribeRunningLogRecordsApi:            NewDcs2DescribeRunningLogRecordsApi(client),
		Dcs2DescribeInstanceConfigApi:               NewDcs2DescribeInstanceConfigApi(client),
		Dcs2ModifyInstanceConfigApi:                 NewDcs2ModifyInstanceConfigApi(client),
		Dcs2BindElasticIPApi:                        NewDcs2BindElasticIPApi(client),
		Dcs2UnBindElasticIPApi:                      NewDcs2UnBindElasticIPApi(client),
		Dcs2ChangeAutoRenewStatusApi:                NewDcs2ChangeAutoRenewStatusApi(client),
		Dcs2DescribeAvailableRegionApi:              NewDcs2DescribeAvailableRegionApi(client),
		Dcs2DescribeInstancesApi:                    NewDcs2DescribeInstancesApi(client),
		Dcs2DescribeCycleBinInstancesApi:            NewDcs2DescribeCycleBinInstancesApi(client),
		Dcs2DescribeDedicatedClusterInstanceListApi: NewDcs2DescribeDedicatedClusterInstanceListApi(client),
		Dcs2DescribePriceApi:                        NewDcs2DescribePriceApi(client),
		Dcs2RenewInstanceApi:                        NewDcs2RenewInstanceApi(client),
		Dcs2CreateInstanceApi:                       NewDcs2CreateInstanceApi(client),
		Dcs2ModifyInstanceSpecApi:                   NewDcs2ModifyInstanceSpecApi(client),
		Dcs2DeleteInstanceApi:                       NewDcs2DeleteInstanceApi(client),
		Dcs2DescribeAvailableResourceApi:            NewDcs2DescribeAvailableResourceApi(client),
		Dcs2DescribeInstancesOverviewApi:            NewDcs2DescribeInstancesOverviewApi(client),
		Dcs2DescribeEngineVersionApi:                NewDcs2DescribeEngineVersionApi(client),
		Dcs2DescribeDBInstanceNetInfoApi:            NewDcs2DescribeDBInstanceNetInfoApi(client),
		Dcs2ModifyInstanceMajorVersionApi:           NewDcs2ModifyInstanceMajorVersionApi(client),
		Dcs2RestartInstanceApi:                      NewDcs2RestartInstanceApi(client),
		Dcs2FlushDataApi:                            NewDcs2FlushDataApi(client),
		Dcs2DescribeTopSlowLogRecoredsApi:           NewDcs2DescribeTopSlowLogRecoredsApi(client),
		Dcs2DescribeTopBigKeysApi:                   NewDcs2DescribeTopBigKeysApi(client),
		Dcs2EnableRenameCommandV2Api:                NewDcs2EnableRenameCommandV2Api(client),
		Dcs2DisableRenameCommandV2Api:               NewDcs2DisableRenameCommandV2Api(client),
		Dcs2DescribeInstanceConfigV2Api:             NewDcs2DescribeInstanceConfigV2Api(client),
		Dcs2ModifyInstanceConfigV2Api:               NewDcs2ModifyInstanceConfigV2Api(client),
		Dcs2QueryInstAutoRenewStatusApi:             NewDcs2QueryInstAutoRenewStatusApi(client),
		Dcs2DescribeDbGroupsApi:                     NewDcs2DescribeDbGroupsApi(client),
		Dcs2QueryGroupKeyNumberApi:                  NewDcs2QueryGroupKeyNumberApi(client),
		Dcs2QueryGroupKeyApi:                        NewDcs2QueryGroupKeyApi(client),
		Dcs2QueryManagerApi:                         NewDcs2QueryManagerApi(client),
		Dcs2PageQueryValuesApi:                      NewDcs2PageQueryValuesApi(client),
		Dcs2DeleteKeyApi:                            NewDcs2DeleteKeyApi(client),
		Dcs2UpdateKeyApi:                            NewDcs2UpdateKeyApi(client),
		Dcs2UpdateValueApi:                          NewDcs2UpdateValueApi(client),
		Dcs2AddValueApi:                             NewDcs2AddValueApi(client),
		Dcs2DeleteValueApi:                          NewDcs2DeleteValueApi(client),
		Dcs2DeleteBackupApi:                         NewDcs2DeleteBackupApi(client),
		Dcs2GetClientIPInfoApi:                      NewDcs2GetClientIPInfoApi(client),
		Dcs2KillSelectedClientApi:                   NewDcs2KillSelectedClientApi(client),
		Dcs2GetClientMapApi:                         NewDcs2GetClientMapApi(client),
		Dcs2FindHistoryBigAndHotKeyApi:              NewDcs2FindHistoryBigAndHotKeyApi(client),
		Dcs2FindHistorySlowLogApi:                   NewDcs2FindHistorySlowLogApi(client),
		Dcs2DescribeHistoryMonitorItemsApi:          NewDcs2DescribeHistoryMonitorItemsApi(client),
		Dcs2DescribeInstanceHistoryMonitorValuesApi: NewDcs2DescribeInstanceHistoryMonitorValuesApi(client),
		Dcs2DescribeNodeHistoryMonitorValuesApi:     NewDcs2DescribeNodeHistoryMonitorValuesApi(client),
		Dcs2ExecuteOffLineKeyAnalysisTaskApi:        NewDcs2ExecuteOffLineKeyAnalysisTaskApi(client),
		Dcs2DescribeOffLineKeyAnalysisTaskListApi:   NewDcs2DescribeOffLineKeyAnalysisTaskListApi(client),
		Dcs2DescribeOffLineKeyAnalysisTaskInfoApi:   NewDcs2DescribeOffLineKeyAnalysisTaskInfoApi(client),
		Dcs2DeleteOffLineKeyAnalysisTaskInfoApi:     NewDcs2DeleteOffLineKeyAnalysisTaskInfoApi(client),
		Dcs2DescribeParameterModificationHistoryApi: NewDcs2DescribeParameterModificationHistoryApi(client),
		Dcs2CreateTransferTaskApi:                   NewDcs2CreateTransferTaskApi(client),
		Dcs2OperateTransferTaskApi:                  NewDcs2OperateTransferTaskApi(client),
		Dcs2ListTaskInfoApi:                         NewDcs2ListTaskInfoApi(client),
		Dcs2DescribeRedisTemplateApi:                NewDcs2DescribeRedisTemplateApi(client),
		Dcs2DescribeRedisTemplateDetailApi:          NewDcs2DescribeRedisTemplateDetailApi(client),
		Dcs2CreateRedisTemplateApi:                  NewDcs2CreateRedisTemplateApi(client),
		Dcs2DeleteRedisTemplateApi:                  NewDcs2DeleteRedisTemplateApi(client),
		Dcs2EditRedisTemplateApi:                    NewDcs2EditRedisTemplateApi(client),
		Dcs2GetRdbDownLoadUrlApi:                    NewDcs2GetRdbDownLoadUrlApi(client),
		Dcs2AutoScanExpiredKeysApi:                  NewDcs2AutoScanExpiredKeysApi(client),
		Dcs2QueryAutoScanConfSettingApi:             NewDcs2QueryAutoScanConfSettingApi(client),
		Dcs2ModifyInstanceAttributeApi:              NewDcs2ModifyInstanceAttributeApi(client),
		Dcs2QueryAnalysisInstanceTasksApi:           NewDcs2QueryAnalysisInstanceTasksApi(client),
		Dcs2DoAnalysisInstanceTasksApi:              NewDcs2DoAnalysisInstanceTasksApi(client),
		Dcs2QueryAnalysisInstanceTasksInfoApi:       NewDcs2QueryAnalysisInstanceTasksInfoApi(client),
		Dcs2DelAnalysisInstanceTaskApi:              NewDcs2DelAnalysisInstanceTaskApi(client),
		Dcs2LockDBInstanceWriteApi:                  NewDcs2LockDBInstanceWriteApi(client),
		Dcs2UnlockDBInstanceWriteApi:                NewDcs2UnlockDBInstanceWriteApi(client),
		Dcs2ListTasksApi:                            NewDcs2ListTasksApi(client),
		Dcs2ModifyInstancePasswordApi:               NewDcs2ModifyInstancePasswordApi(client),
		Dcs2ResetInstancePasswordApi:                NewDcs2ResetInstancePasswordApi(client),
		Dcs2DescribeInstanceSSLApi:                  NewDcs2DescribeInstanceSSLApi(client),
		Dcs2ModifyInstanceSSLApi:                    NewDcs2ModifyInstanceSSLApi(client),
		Dcs2SlowLogResetApi:                         NewDcs2SlowLogResetApi(client),
		Dcs2ModifyInstanceFeatureApi:                NewDcs2ModifyInstanceFeatureApi(client),
		Dcs2DescribeHotKeyTasksApi:                  NewDcs2DescribeHotKeyTasksApi(client),
		Dcs2DescribeBigKeyTasksApi:                  NewDcs2DescribeBigKeyTasksApi(client),
		Dcs2DeleteHotKeyTaskApi:                     NewDcs2DeleteHotKeyTaskApi(client),
		Dcs2DeleteBigKeyTaskApi:                     NewDcs2DeleteBigKeyTaskApi(client),
		Dcs2DeleteInstancesApi:                      NewDcs2DeleteInstancesApi(client),
		Dcs2PageListLabelApi:                        NewDcs2PageListLabelApi(client),
		Dcs2BatchAddLabelApi:                        NewDcs2BatchAddLabelApi(client),
		Dcs2GetLabelListByResourcesApi:              NewDcs2GetLabelListByResourcesApi(client),
		Dcs2QueryQuotaTotalAndUsedApi:               NewDcs2QueryQuotaTotalAndUsedApi(client),
		Dcs2GetZonesApi:                             NewDcs2GetZonesApi(client),
		Dcs2ExcuteCommandApi:                        NewDcs2ExcuteCommandApi(client),
		Dcs2StatusNumberApi:                         NewDcs2StatusNumberApi(client),
		Dcs2StatisticApi:                            NewDcs2StatisticApi(client),
		Dcs2CheckInstanceOperateApi:                 NewDcs2CheckInstanceOperateApi(client),
		Dcs2AsyncExportInstancesApi:                 NewDcs2AsyncExportInstancesApi(client),
		Dcs2UpdateSlavePriorityApi:                  NewDcs2UpdateSlavePriorityApi(client),
		Dcs2DescribeInstancesClusterMemberInfoApi:   NewDcs2DescribeInstancesClusterMemberInfoApi(client),
		Dcs2QueryFragmentReplicationStateApi:        NewDcs2QueryFragmentReplicationStateApi(client),
		Dcs2ExchangeVipApi:                          NewDcs2ExchangeVipApi(client),
		Dcs2DeleteTransferTaskApi:                   NewDcs2DeleteTransferTaskApi(client),
		Dcs2GetTransferTaskInfoApi:                  NewDcs2GetTransferTaskInfoApi(client),
		Dcs2ConfigAutoRetryTypeApi:                  NewDcs2ConfigAutoRetryTypeApi(client),
		Dcs2GetTaskProgressDetailInfoApi:            NewDcs2GetTaskProgressDetailInfoApi(client),
		Dcs2StopTransferTaskApi:                     NewDcs2StopTransferTaskApi(client),
		Dcs2UploadSyncRunningLogApi:                 NewDcs2UploadSyncRunningLogApi(client),
		Dcs2RestartTransferTaskApi:                  NewDcs2RestartTransferTaskApi(client),
		Dcs2DescribeTopBigKeysPolicyApi:             NewDcs2DescribeTopBigKeysPolicyApi(client),
		Dcs2ModifyBigKeyPolicyApi:                   NewDcs2ModifyBigKeyPolicyApi(client),
		Dcs2DescribeTopHotKeysPolicyApi:             NewDcs2DescribeTopHotKeysPolicyApi(client),
		Dcs2ModifyHotKeyPolicyApi:                   NewDcs2ModifyHotKeyPolicyApi(client),
		Dcs2DownloadRedisRunLogApi:                  NewDcs2DownloadRedisRunLogApi(client),
		Dcs2DownloadSslCertApi:                      NewDcs2DownloadSslCertApi(client),
		Dcs2DelTasksApi:                             NewDcs2DelTasksApi(client),
		Dcs2GetTaskInfoApi:                          NewDcs2GetTaskInfoApi(client),
		Dcs2CheckInstanceProdModifyApi:              NewDcs2CheckInstanceProdModifyApi(client),
		Dcs2QueryExportInstanceTaskApi:              NewDcs2QueryExportInstanceTaskApi(client),
		Dcs2GetKeyMisslogApi:                        NewDcs2GetKeyMisslogApi(client),
		Dcs2DescribeInstanceVersionApi:              NewDcs2DescribeInstanceVersionApi(client),
		Dcs2UpgradeInstanceMinorVersionApi:          NewDcs2UpgradeInstanceMinorVersionApi(client),
		Dcs2UpgradeInstanceProxyMinorVersionApi:     NewDcs2UpgradeInstanceProxyMinorVersionApi(client),
		Dcs2OpenAutoScaleApi:                        NewDcs2OpenAutoScaleApi(client),
		Dcs2CloseAutoScaleApi:                       NewDcs2CloseAutoScaleApi(client),
		Dcs2BatchRestartVmApi:                       NewDcs2BatchRestartVmApi(client),
		Dcs2QueryScanLogsApi:                        NewDcs2QueryScanLogsApi(client),
		Dcs2HostDownFaultInjectApi:                  NewDcs2HostDownFaultInjectApi(client),
		Dcs2HostTypeFaultInjectApi:                  NewDcs2HostTypeFaultInjectApi(client),
		Dcs2NetworkLossFaultInjectApi:               NewDcs2NetworkLossFaultInjectApi(client),
		Dcs2FaultRecoveryApi:                        NewDcs2FaultRecoveryApi(client),
		Dcs2ListInstanceExperimentsApi:              NewDcs2ListInstanceExperimentsApi(client),
		Dcs2EnableRWSepApi:                          NewDcs2EnableRWSepApi(client),
		Dcs2QueryRWSepApi:                           NewDcs2QueryRWSepApi(client),
		Dcs2DestroyInstanceApi:                      NewDcs2DestroyInstanceApi(client),
	}
}
